// Autogenerated with StateSmith 0.19.0-alpha-1+3da98b58a6e506bc06d88cba576dcc4df8809849.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

package tankpack;

// Generated state machine
public class Sm_Engine_Generated extends StateMachine
{
//  ////////////////////////////////////////////////////////////////////////////////
    // Class code
    ////////////////////////////////////////////////////////////////////////////////
    
    // Must be overridden by inheriting class
    protected void adjustSpeed()
    {
    }

    ////////////////////////////////////////////////////////////////////////////////
    // End of class code
    ////////////////////////////////////////////////////////////////////////////////


    public enum EventId
    {
        DO, // The `do` event is special. State event handlers do not consume this event (ancestors all get it too) unless a transition occurs.
        LEFTSTICKBACKWARD,
        LEFTSTICKBACKWARDLEFT,
        LEFTSTICKBACKWARDRIGHT,
        LEFTSTICKFORWARD,
        LEFTSTICKFORWARDLEFT,
        LEFTSTICKFORWARDRIGHT,
        LEFTSTICKIDLE,
        LEFTSTICKLEFT,
        LEFTSTICKRIGHT,
        STARTPRESSED,
    }
    
    public final int EventIdCount = 11;
    
    public enum StateId
    {
        ROOT,
        IDLE,
        OFF,
        RUNNING,
        ACCELERATING,
        DECELERATING,
        HIGHRPM,
        LOWRPM,
        MEDIUMRPM,
        SHUTDOWN,
        STARTING,
    }
    
    public final int StateIdCount = 11;
    
    // Used internally by state machine. Feel free to inspect, but don't modify.
    public StateId stateId;
    
    // State machine variables. Can be used for inputs, outputs, user variables...
    public class Vars
    {
        // These variables can be referenced in diagram and are automatically prefixed with "this.vars." during code generation
        // Protected variables, must be set by inheriting class
        protected Driver_Sound ds;
        protected int currentSpeed;
        protected int targetSpeed;
        
        // Private variables, only used locally
        private final long WAITTIME = (800L / DOTIME()) * DOTIME(); // Set / Approach x ms, must be divisible by Main.DoPeriod, if DOTIME > x, WAITTIME will be 0
        private final int QUICKFADE = 200; // ms
        private final int SLOWFADE = 1500; // ms
        private long playTime;
        private boolean soundPlaying;
        private boolean soundAlmostDone;
    }
    
    // Variables. Can be used for inputs, outputs, user variables...
    public Vars vars = new Vars();
    
    // State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
    public Sm_Engine_Generated()
    {
    }
    
    // Starts the state machine. Must be called before dispatching events. Not thread safe.
    public void start()
    {
        ROOT_enter();
        // ROOT behavior
        // uml: TransitionTo(ROOT.<InitialState>)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
            // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
            
            // ROOT.<InitialState> behavior
            // uml: TransitionTo(OFF)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `OFF`.
                OFF_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for ROOT.<InitialState>
        } // end of behavior for ROOT
    }
    
    // Dispatches an event to the state machine. Not thread safe.
    // Note! This function assumes that the `eventId` parameter is valid.
    public void dispatchEvent(EventId eventId)
    {
        switch (this.stateId)
        {
            // STATE: Sm_Engine_Generated
            case ROOT:
                // No events handled by this state (or its ancestors).
                break;
            
            // STATE: IDLE
            case IDLE:
                switch (eventId)
                {
                    case LEFTSTICKFORWARD: IDLE_leftstickforward(); break;
                    case LEFTSTICKIDLE: IDLE_leftstickidle(); break;
                    case LEFTSTICKFORWARDRIGHT: IDLE_leftstickforwardright(); break;
                    case LEFTSTICKRIGHT: IDLE_leftstickright(); break;
                    case LEFTSTICKBACKWARDRIGHT: IDLE_leftstickbackwardright(); break;
                    case LEFTSTICKBACKWARD: IDLE_leftstickbackward(); break;
                    case LEFTSTICKBACKWARDLEFT: IDLE_leftstickbackwardleft(); break;
                    case LEFTSTICKLEFT: IDLE_leftstickleft(); break;
                    case LEFTSTICKFORWARDLEFT: IDLE_leftstickforwardleft(); break;
                    case STARTPRESSED: IDLE_startpressed(); break;
                }
                break;
            
            // STATE: OFF
            case OFF:
                switch (eventId)
                {
                    case LEFTSTICKFORWARD: OFF_leftstickforward(); break;
                    case LEFTSTICKIDLE: OFF_leftstickidle(); break;
                    case LEFTSTICKFORWARDRIGHT: OFF_leftstickforwardright(); break;
                    case LEFTSTICKRIGHT: OFF_leftstickright(); break;
                    case LEFTSTICKBACKWARDRIGHT: OFF_leftstickbackwardright(); break;
                    case LEFTSTICKBACKWARD: OFF_leftstickbackward(); break;
                    case LEFTSTICKBACKWARDLEFT: OFF_leftstickbackwardleft(); break;
                    case LEFTSTICKLEFT: OFF_leftstickleft(); break;
                    case LEFTSTICKFORWARDLEFT: OFF_leftstickforwardleft(); break;
                    case STARTPRESSED: OFF_startpressed(); break;
                }
                break;
            
            // STATE: RUNNING
            case RUNNING:
                switch (eventId)
                {
                    case LEFTSTICKFORWARD: RUNNING_leftstickforward(); break;
                    case LEFTSTICKFORWARDRIGHT: RUNNING_leftstickforwardright(); break;
                    case LEFTSTICKRIGHT: RUNNING_leftstickright(); break;
                    case LEFTSTICKBACKWARDRIGHT: RUNNING_leftstickbackwardright(); break;
                    case LEFTSTICKBACKWARD: RUNNING_leftstickbackward(); break;
                    case LEFTSTICKBACKWARDLEFT: RUNNING_leftstickbackwardleft(); break;
                    case LEFTSTICKLEFT: RUNNING_leftstickleft(); break;
                    case LEFTSTICKFORWARDLEFT: RUNNING_leftstickforwardleft(); break;
                    case STARTPRESSED: RUNNING_startpressed(); break;
                    case LEFTSTICKIDLE: RUNNING_leftstickidle(); break;
                    case DO: RUNNING_do(); break;
                }
                break;
            
            // STATE: ACCELERATING
            case ACCELERATING:
                switch (eventId)
                {
                    case DO: ACCELERATING_do(); break;
                    case LEFTSTICKFORWARD: RUNNING_leftstickforward(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARDRIGHT: RUNNING_leftstickforwardright(); break; // First ancestor handler for this event
                    case LEFTSTICKRIGHT: RUNNING_leftstickright(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARDRIGHT: RUNNING_leftstickbackwardright(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARD: RUNNING_leftstickbackward(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARDLEFT: RUNNING_leftstickbackwardleft(); break; // First ancestor handler for this event
                    case LEFTSTICKLEFT: RUNNING_leftstickleft(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARDLEFT: RUNNING_leftstickforwardleft(); break; // First ancestor handler for this event
                    case STARTPRESSED: RUNNING_startpressed(); break; // First ancestor handler for this event
                    case LEFTSTICKIDLE: RUNNING_leftstickidle(); break; // First ancestor handler for this event
                }
                break;
            
            // STATE: DECELERATING
            case DECELERATING:
                switch (eventId)
                {
                    case DO: DECELERATING_do(); break;
                    case LEFTSTICKFORWARD: RUNNING_leftstickforward(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARDRIGHT: RUNNING_leftstickforwardright(); break; // First ancestor handler for this event
                    case LEFTSTICKRIGHT: RUNNING_leftstickright(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARDRIGHT: RUNNING_leftstickbackwardright(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARD: RUNNING_leftstickbackward(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARDLEFT: RUNNING_leftstickbackwardleft(); break; // First ancestor handler for this event
                    case LEFTSTICKLEFT: RUNNING_leftstickleft(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARDLEFT: RUNNING_leftstickforwardleft(); break; // First ancestor handler for this event
                    case STARTPRESSED: RUNNING_startpressed(); break; // First ancestor handler for this event
                    case LEFTSTICKIDLE: RUNNING_leftstickidle(); break; // First ancestor handler for this event
                }
                break;
            
            // STATE: HIGHRPM
            case HIGHRPM:
                switch (eventId)
                {
                    case DO: HIGHRPM_do(); break;
                    case LEFTSTICKFORWARD: RUNNING_leftstickforward(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARDRIGHT: RUNNING_leftstickforwardright(); break; // First ancestor handler for this event
                    case LEFTSTICKRIGHT: RUNNING_leftstickright(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARDRIGHT: RUNNING_leftstickbackwardright(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARD: RUNNING_leftstickbackward(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARDLEFT: RUNNING_leftstickbackwardleft(); break; // First ancestor handler for this event
                    case LEFTSTICKLEFT: RUNNING_leftstickleft(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARDLEFT: RUNNING_leftstickforwardleft(); break; // First ancestor handler for this event
                    case STARTPRESSED: RUNNING_startpressed(); break; // First ancestor handler for this event
                    case LEFTSTICKIDLE: RUNNING_leftstickidle(); break; // First ancestor handler for this event
                }
                break;
            
            // STATE: LOWRPM
            case LOWRPM:
                switch (eventId)
                {
                    case DO: LOWRPM_do(); break;
                    case LEFTSTICKFORWARD: RUNNING_leftstickforward(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARDRIGHT: RUNNING_leftstickforwardright(); break; // First ancestor handler for this event
                    case LEFTSTICKRIGHT: RUNNING_leftstickright(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARDRIGHT: RUNNING_leftstickbackwardright(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARD: RUNNING_leftstickbackward(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARDLEFT: RUNNING_leftstickbackwardleft(); break; // First ancestor handler for this event
                    case LEFTSTICKLEFT: RUNNING_leftstickleft(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARDLEFT: RUNNING_leftstickforwardleft(); break; // First ancestor handler for this event
                    case STARTPRESSED: RUNNING_startpressed(); break; // First ancestor handler for this event
                    case LEFTSTICKIDLE: RUNNING_leftstickidle(); break; // First ancestor handler for this event
                }
                break;
            
            // STATE: MEDIUMRPM
            case MEDIUMRPM:
                switch (eventId)
                {
                    case DO: MEDIUMRPM_do(); break;
                    case LEFTSTICKFORWARD: RUNNING_leftstickforward(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARDRIGHT: RUNNING_leftstickforwardright(); break; // First ancestor handler for this event
                    case LEFTSTICKRIGHT: RUNNING_leftstickright(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARDRIGHT: RUNNING_leftstickbackwardright(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARD: RUNNING_leftstickbackward(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARDLEFT: RUNNING_leftstickbackwardleft(); break; // First ancestor handler for this event
                    case LEFTSTICKLEFT: RUNNING_leftstickleft(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARDLEFT: RUNNING_leftstickforwardleft(); break; // First ancestor handler for this event
                    case STARTPRESSED: RUNNING_startpressed(); break; // First ancestor handler for this event
                    case LEFTSTICKIDLE: RUNNING_leftstickidle(); break; // First ancestor handler for this event
                }
                break;
            
            // STATE: SHUTDOWN
            case SHUTDOWN:
                switch (eventId)
                {
                    case DO: SHUTDOWN_do(); break;
                    case LEFTSTICKFORWARD: SHUTDOWN_leftstickforward(); break;
                    case LEFTSTICKIDLE: SHUTDOWN_leftstickidle(); break;
                    case LEFTSTICKFORWARDRIGHT: SHUTDOWN_leftstickforwardright(); break;
                    case LEFTSTICKRIGHT: SHUTDOWN_leftstickright(); break;
                    case LEFTSTICKBACKWARDRIGHT: SHUTDOWN_leftstickbackwardright(); break;
                    case LEFTSTICKBACKWARD: SHUTDOWN_leftstickbackward(); break;
                    case LEFTSTICKBACKWARDLEFT: SHUTDOWN_leftstickbackwardleft(); break;
                    case LEFTSTICKLEFT: SHUTDOWN_leftstickleft(); break;
                    case LEFTSTICKFORWARDLEFT: SHUTDOWN_leftstickforwardleft(); break;
                    case STARTPRESSED: SHUTDOWN_startpressed(); break;
                }
                break;
            
            // STATE: STARTING
            case STARTING:
                switch (eventId)
                {
                    case DO: STARTING_do(); break;
                    case LEFTSTICKFORWARD: STARTING_leftstickforward(); break;
                    case LEFTSTICKIDLE: STARTING_leftstickidle(); break;
                    case LEFTSTICKFORWARDRIGHT: STARTING_leftstickforwardright(); break;
                    case LEFTSTICKRIGHT: STARTING_leftstickright(); break;
                    case LEFTSTICKBACKWARDRIGHT: STARTING_leftstickbackwardright(); break;
                    case LEFTSTICKBACKWARD: STARTING_leftstickbackward(); break;
                    case LEFTSTICKBACKWARDLEFT: STARTING_leftstickbackwardleft(); break;
                    case LEFTSTICKLEFT: STARTING_leftstickleft(); break;
                    case LEFTSTICKFORWARDLEFT: STARTING_leftstickforwardleft(); break;
                    case STARTPRESSED: STARTING_startpressed(); break;
                }
                break;
        }
        
    }
    
    // This function is used when StateSmith doesn't know what the active leaf state is at
    // compile time due to sub states or when multiple states need to be exited.
    private void exitUpToStateHandler(StateId desiredState)
    {
        while (this.stateId != desiredState)
        {
            switch (this.stateId)
            {
                case IDLE: IDLE_exit(); break;
                
                case OFF: OFF_exit(); break;
                
                case RUNNING: RUNNING_exit(); break;
                
                case ACCELERATING: ACCELERATING_exit(); break;
                
                case DECELERATING: DECELERATING_exit(); break;
                
                case HIGHRPM: HIGHRPM_exit(); break;
                
                case LOWRPM: LOWRPM_exit(); break;
                
                case MEDIUMRPM: MEDIUMRPM_exit(); break;
                
                case SHUTDOWN: SHUTDOWN_exit(); break;
                
                case STARTING: STARTING_exit(); break;
                
                default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
            }
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state ROOT
    ////////////////////////////////////////////////////////////////////////////////
    
    private void ROOT_enter()
    {
        this.stateId = StateId.ROOT;
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state IDLE
    ////////////////////////////////////////////////////////////////////////////////
    
    private void IDLE_enter()
    {
        this.stateId = StateId.IDLE;
        
        // IDLE behavior
        // uml: enter / { updateProcess();\ncurrentSpeed = 1;\ntargetSpeed = 0;\nadjustSpeed(); // Make sure speed is set to 0\nds.fadeIn("cyclone_idle", QUICKFADE); }
        {
            // Step 1: execute action `updateProcess();\ncurrentSpeed = 1;\ntargetSpeed = 0;\nadjustSpeed(); // Make sure speed is set to 0\nds.fadeIn("cyclone_idle", QUICKFADE);`
            updateProcess();
            this.vars.currentSpeed = 1;
            this.vars.targetSpeed = 0;
            adjustSpeed(); // Make sure speed is set to 0
            this.vars.ds.fadeIn("cyclone_idle", this.vars.QUICKFADE);
        } // end of behavior for IDLE
    }
    
    private void IDLE_exit()
    {
        // IDLE behavior
        // uml: exit / { ds.fadeOut("cyclone_idle", SLOWFADE); }
        {
            // Step 1: execute action `ds.fadeOut("cyclone_idle", SLOWFADE);`
            this.vars.ds.fadeOut("cyclone_idle", this.vars.SLOWFADE);
        } // end of behavior for IDLE
        
        this.stateId = StateId.ROOT;
    }
    
    private void IDLE_leftstickbackward()
    {
        // IDLE behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for IDLE
        
        // IDLE behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT) [targetSpeed >= 10] TransitionTo(ACCELERATING)
        if (this.vars.targetSpeed >= 10)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            IDLE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ACCELERATING`.
            RUNNING_enter();
            ACCELERATING_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_leftstickbackwardleft()
    {
        // IDLE behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for IDLE
        
        // IDLE behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT) [targetSpeed >= 10] TransitionTo(ACCELERATING)
        if (this.vars.targetSpeed >= 10)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            IDLE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ACCELERATING`.
            RUNNING_enter();
            ACCELERATING_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_leftstickbackwardright()
    {
        // IDLE behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for IDLE
        
        // IDLE behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT) [targetSpeed >= 10] TransitionTo(ACCELERATING)
        if (this.vars.targetSpeed >= 10)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            IDLE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ACCELERATING`.
            RUNNING_enter();
            ACCELERATING_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_leftstickforward()
    {
        // IDLE behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for IDLE
        
        // IDLE behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT) [targetSpeed >= 10] TransitionTo(ACCELERATING)
        if (this.vars.targetSpeed >= 10)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            IDLE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ACCELERATING`.
            RUNNING_enter();
            ACCELERATING_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_leftstickforwardleft()
    {
        // IDLE behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for IDLE
        
        // IDLE behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT) [targetSpeed >= 10] TransitionTo(ACCELERATING)
        if (this.vars.targetSpeed >= 10)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            IDLE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ACCELERATING`.
            RUNNING_enter();
            ACCELERATING_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_leftstickforwardright()
    {
        // IDLE behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for IDLE
        
        // IDLE behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT) [targetSpeed >= 10] TransitionTo(ACCELERATING)
        if (this.vars.targetSpeed >= 10)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            IDLE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ACCELERATING`.
            RUNNING_enter();
            ACCELERATING_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_leftstickidle()
    {
        // IDLE behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for IDLE
        
        // IDLE behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT) [targetSpeed >= 10] TransitionTo(ACCELERATING)
        if (this.vars.targetSpeed >= 10)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            IDLE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ACCELERATING`.
            RUNNING_enter();
            ACCELERATING_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_leftstickleft()
    {
        // IDLE behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for IDLE
        
        // IDLE behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT) [targetSpeed >= 10] TransitionTo(ACCELERATING)
        if (this.vars.targetSpeed >= 10)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            IDLE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ACCELERATING`.
            RUNNING_enter();
            ACCELERATING_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_leftstickright()
    {
        // IDLE behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for IDLE
        
        // IDLE behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT) [targetSpeed >= 10] TransitionTo(ACCELERATING)
        if (this.vars.targetSpeed >= 10)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            IDLE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ACCELERATING`.
            RUNNING_enter();
            ACCELERATING_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_startpressed()
    {
        // IDLE behavior
        // uml: STARTPRESSED TransitionTo(SHUTDOWN)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            IDLE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `SHUTDOWN`.
            SHUTDOWN_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state OFF
    ////////////////////////////////////////////////////////////////////////////////
    
    private void OFF_enter()
    {
        this.stateId = StateId.OFF;
        
        // OFF behavior
        // uml: enter / { updateProcess();\ncurrentSpeed = 1;\ntargetSpeed = 0;\nadjustSpeed(); // Make sure speed is set to 0 }
        {
            // Step 1: execute action `updateProcess();\ncurrentSpeed = 1;\ntargetSpeed = 0;\nadjustSpeed(); // Make sure speed is set to 0`
            updateProcess();
            this.vars.currentSpeed = 1;
            this.vars.targetSpeed = 0;
            adjustSpeed(); // Make sure speed is set to 0<EOF>
        } // end of behavior for OFF
    }
    
    private void OFF_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void OFF_leftstickbackward()
    {
        // OFF behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for OFF
        
        // No ancestor handles this event.
    }
    
    private void OFF_leftstickbackwardleft()
    {
        // OFF behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for OFF
        
        // No ancestor handles this event.
    }
    
    private void OFF_leftstickbackwardright()
    {
        // OFF behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for OFF
        
        // No ancestor handles this event.
    }
    
    private void OFF_leftstickforward()
    {
        // OFF behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for OFF
        
        // No ancestor handles this event.
    }
    
    private void OFF_leftstickforwardleft()
    {
        // OFF behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for OFF
        
        // No ancestor handles this event.
    }
    
    private void OFF_leftstickforwardright()
    {
        // OFF behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for OFF
        
        // No ancestor handles this event.
    }
    
    private void OFF_leftstickidle()
    {
        // OFF behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for OFF
        
        // No ancestor handles this event.
    }
    
    private void OFF_leftstickleft()
    {
        // OFF behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for OFF
        
        // No ancestor handles this event.
    }
    
    private void OFF_leftstickright()
    {
        // OFF behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for OFF
        
        // No ancestor handles this event.
    }
    
    private void OFF_startpressed()
    {
        // OFF behavior
        // uml: STARTPRESSED TransitionTo(STARTING)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            OFF_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `STARTING`.
            STARTING_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for OFF
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state RUNNING
    ////////////////////////////////////////////////////////////////////////////////
    
    private void RUNNING_enter()
    {
        this.stateId = StateId.RUNNING;
    }
    
    private void RUNNING_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void RUNNING_do()
    {
        // RUNNING behavior
        // uml: do [currentSpeed != targetSpeed] / { adjustSpeed(); }
        if (this.vars.currentSpeed != this.vars.targetSpeed)
        {
            // Step 1: execute action `adjustSpeed();`
            adjustSpeed();
        } // end of behavior for RUNNING
        
        // No ancestor handles this event.
    }
    
    private void RUNNING_leftstickbackward()
    {
        // RUNNING behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT, STARTPRESSED) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for RUNNING
        
        // No ancestor handles this event.
    }
    
    private void RUNNING_leftstickbackwardleft()
    {
        // RUNNING behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT, STARTPRESSED) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for RUNNING
        
        // No ancestor handles this event.
    }
    
    private void RUNNING_leftstickbackwardright()
    {
        // RUNNING behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT, STARTPRESSED) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for RUNNING
        
        // No ancestor handles this event.
    }
    
    private void RUNNING_leftstickforward()
    {
        // RUNNING behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT, STARTPRESSED) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for RUNNING
        
        // No ancestor handles this event.
    }
    
    private void RUNNING_leftstickforwardleft()
    {
        // RUNNING behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT, STARTPRESSED) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for RUNNING
        
        // No ancestor handles this event.
    }
    
    private void RUNNING_leftstickforwardright()
    {
        // RUNNING behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT, STARTPRESSED) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for RUNNING
        
        // No ancestor handles this event.
    }
    
    private void RUNNING_leftstickidle()
    {
        // RUNNING behavior
        // uml: LEFTSTICKIDLE / { updateProcess();\ntargetSpeed = 0; }
        {
            // Step 1: execute action `updateProcess();\ntargetSpeed = 0;`
            updateProcess();
            this.vars.targetSpeed = 0;
        } // end of behavior for RUNNING
        
        // No ancestor handles this event.
    }
    
    private void RUNNING_leftstickleft()
    {
        // RUNNING behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT, STARTPRESSED) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for RUNNING
        
        // No ancestor handles this event.
    }
    
    private void RUNNING_leftstickright()
    {
        // RUNNING behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT, STARTPRESSED) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for RUNNING
        
        // No ancestor handles this event.
    }
    
    private void RUNNING_startpressed()
    {
        // RUNNING behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT, STARTPRESSED) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for RUNNING
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state ACCELERATING
    ////////////////////////////////////////////////////////////////////////////////
    
    private void ACCELERATING_enter()
    {
        this.stateId = StateId.ACCELERATING;
        
        // ACCELERATING behavior
        // uml: enter / { updateProcess();\nplayTime = 0;\nds.playOneShot("cyclone_accelerate"); }
        {
            // Step 1: execute action `updateProcess();\nplayTime = 0;\nds.playOneShot("cyclone_accelerate");`
            updateProcess();
            this.vars.playTime = 0;
            this.vars.ds.playOneShot("cyclone_accelerate");
        } // end of behavior for ACCELERATING
    }
    
    private void ACCELERATING_exit()
    {
        this.stateId = StateId.RUNNING;
    }
    
    private void ACCELERATING_do()
    {
        boolean consume_event = false;
        
        // ACCELERATING behavior
        // uml: do / { playTime += DOTIME();\nsoundAlmostDone = \n ds.almostDone("cyclone_accelerate", playTime); }
        {
            // `do` events are not normally consumed.
            // Step 1: execute action `playTime += DOTIME();\nsoundAlmostDone = \n ds.almostDone("cyclone_accelerate", playTime);`
            this.vars.playTime += DOTIME();
            this.vars.soundAlmostDone = 
             this.vars.ds.almostDone("cyclone_accelerate", this.vars.playTime);
        } // end of behavior for ACCELERATING
        
        // ACCELERATING behavior
        // uml: do [soundAlmostDone] TransitionTo(LOWRPM)
        if (this.vars.soundAlmostDone)
        {
            // Step 1: Exit states until we reach `RUNNING` state (Least Common Ancestor for transition).
            ACCELERATING_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `LOWRPM`.
            LOWRPM_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ACCELERATING
        
        // Check if event has been consumed before calling ancestor handler.
        if (!consume_event)
        {
            RUNNING_do();
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state DECELERATING
    ////////////////////////////////////////////////////////////////////////////////
    
    private void DECELERATING_enter()
    {
        this.stateId = StateId.DECELERATING;
        
        // DECELERATING behavior
        // uml: enter / { updateProcess();\nplayTime = 0;\nds.fadeIn("cyclone_idle", QUICKFADE);\nds.fadeOut("cyclone_run", SLOWFADE);\nds.fadeOut("cyclone_run1", SLOWFADE); }
        {
            // Step 1: execute action `updateProcess();\nplayTime = 0;\nds.fadeIn("cyclone_idle", QUICKFADE);\nds.fadeOut("cyclone_run", SLOWFADE);\nds.fadeOut("cyclone_run1", SLOWFADE);`
            updateProcess();
            this.vars.playTime = 0;
            this.vars.ds.fadeIn("cyclone_idle", this.vars.QUICKFADE);
            this.vars.ds.fadeOut("cyclone_run", this.vars.SLOWFADE);
            this.vars.ds.fadeOut("cyclone_run1", this.vars.SLOWFADE);
        } // end of behavior for DECELERATING
    }
    
    private void DECELERATING_exit()
    {
        this.stateId = StateId.RUNNING;
    }
    
    private void DECELERATING_do()
    {
        boolean consume_event = false;
        
        // DECELERATING behavior
        // uml: do / { playTime += DOTIME(); }
        {
            // `do` events are not normally consumed.
            // Step 1: execute action `playTime += DOTIME();`
            this.vars.playTime += DOTIME();
        } // end of behavior for DECELERATING
        
        // DECELERATING behavior
        // uml: do [playTime == WAITTIME || WAITTIME == 0] / { ds.fadeOut("cyclone_lowrpm", SLOWFADE); }
        if (this.vars.playTime == this.vars.WAITTIME || this.vars.WAITTIME == 0)
        {
            // `do` events are not normally consumed.
            // Step 1: execute action `ds.fadeOut("cyclone_lowrpm", SLOWFADE);`
            this.vars.ds.fadeOut("cyclone_lowrpm", this.vars.SLOWFADE);
        } // end of behavior for DECELERATING
        
        // DECELERATING behavior
        // uml: do [targetSpeed > 0] / { ds.fadeOut("cyclone_idle", SLOWFADE); } TransitionTo(LOWRPM)
        if (this.vars.targetSpeed > 0)
        {
            // Step 1: Exit states until we reach `RUNNING` state (Least Common Ancestor for transition).
            DECELERATING_exit();
            
            // Step 2: Transition action: `ds.fadeOut("cyclone_idle", SLOWFADE);`.
            this.vars.ds.fadeOut("cyclone_idle", this.vars.SLOWFADE);
            
            // Step 3: Enter/move towards transition target `LOWRPM`.
            LOWRPM_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for DECELERATING
        
        // DECELERATING behavior
        // uml: do [playTime >= WAITTIME*2] / { ds.playOneShot("cyclone_slow"); } TransitionTo(IDLE)
        if (this.vars.playTime >= this.vars.WAITTIME*2)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            exitUpToStateHandler(StateId.ROOT);
            
            // Step 2: Transition action: `ds.playOneShot("cyclone_slow");`.
            this.vars.ds.playOneShot("cyclone_slow");
            
            // Step 3: Enter/move towards transition target `IDLE`.
            IDLE_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for DECELERATING
        
        // Check if event has been consumed before calling ancestor handler.
        if (!consume_event)
        {
            RUNNING_do();
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state HIGHRPM
    ////////////////////////////////////////////////////////////////////////////////
    
    private void HIGHRPM_enter()
    {
        this.stateId = StateId.HIGHRPM;
        
        // HIGHRPM behavior
        // uml: enter / { updateProcess();\nplayTime = 0;\nds.fadeIn("cyclone_run1", QUICKFADE);\nds.fadeOut("cyclone_lowrpm", SLOWFADE); }
        {
            // Step 1: execute action `updateProcess();\nplayTime = 0;\nds.fadeIn("cyclone_run1", QUICKFADE);\nds.fadeOut("cyclone_lowrpm", SLOWFADE);`
            updateProcess();
            this.vars.playTime = 0;
            this.vars.ds.fadeIn("cyclone_run1", this.vars.QUICKFADE);
            this.vars.ds.fadeOut("cyclone_lowrpm", this.vars.SLOWFADE);
        } // end of behavior for HIGHRPM
    }
    
    private void HIGHRPM_exit()
    {
        this.stateId = StateId.RUNNING;
    }
    
    private void HIGHRPM_do()
    {
        boolean consume_event = false;
        
        // HIGHRPM behavior
        // uml: do [playTime <= WAITTIME] / { playTime += DOTIME(); }
        if (this.vars.playTime <= this.vars.WAITTIME)
        {
            // `do` events are not normally consumed.
            // Step 1: execute action `playTime += DOTIME();`
            this.vars.playTime += DOTIME();
        } // end of behavior for HIGHRPM
        
        // HIGHRPM behavior
        // uml: do [playTime == WAITTIME || WAITTIME == 0] / { ds.fadeOut("cyclone_run", SLOWFADE); }
        if (this.vars.playTime == this.vars.WAITTIME || this.vars.WAITTIME == 0)
        {
            // `do` events are not normally consumed.
            // Step 1: execute action `ds.fadeOut("cyclone_run", SLOWFADE);`
            this.vars.ds.fadeOut("cyclone_run", this.vars.SLOWFADE);
        } // end of behavior for HIGHRPM
        
        // HIGHRPM behavior
        // uml: do [targetSpeed < 90] TransitionTo(MEDIUMRPM)
        if (this.vars.targetSpeed < 90)
        {
            // Step 1: Exit states until we reach `RUNNING` state (Least Common Ancestor for transition).
            HIGHRPM_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `MEDIUMRPM`.
            MEDIUMRPM_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for HIGHRPM
        
        // Check if event has been consumed before calling ancestor handler.
        if (!consume_event)
        {
            RUNNING_do();
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state LOWRPM
    ////////////////////////////////////////////////////////////////////////////////
    
    private void LOWRPM_enter()
    {
        this.stateId = StateId.LOWRPM;
        
        // LOWRPM behavior
        // uml: enter / { updateProcess();\nplayTime = 0;\nds.fadeIn("cyclone_lowrpm", QUICKFADE);\nds.fadeOut("cyclone_run1", SLOWFADE); }
        {
            // Step 1: execute action `updateProcess();\nplayTime = 0;\nds.fadeIn("cyclone_lowrpm", QUICKFADE);\nds.fadeOut("cyclone_run1", SLOWFADE);`
            updateProcess();
            this.vars.playTime = 0;
            this.vars.ds.fadeIn("cyclone_lowrpm", this.vars.QUICKFADE);
            this.vars.ds.fadeOut("cyclone_run1", this.vars.SLOWFADE);
        } // end of behavior for LOWRPM
    }
    
    private void LOWRPM_exit()
    {
        this.stateId = StateId.RUNNING;
    }
    
    private void LOWRPM_do()
    {
        boolean consume_event = false;
        
        // LOWRPM behavior
        // uml: do [playTime <= WAITTIME] / { playTime += DOTIME(); }
        if (this.vars.playTime <= this.vars.WAITTIME)
        {
            // `do` events are not normally consumed.
            // Step 1: execute action `playTime += DOTIME();`
            this.vars.playTime += DOTIME();
        } // end of behavior for LOWRPM
        
        // LOWRPM behavior
        // uml: do [playTime == WAITTIME || WAITTIME == 0] / { ds.fadeOut("cyclone_run", SLOWFADE); }
        if (this.vars.playTime == this.vars.WAITTIME || this.vars.WAITTIME == 0)
        {
            // `do` events are not normally consumed.
            // Step 1: execute action `ds.fadeOut("cyclone_run", SLOWFADE);`
            this.vars.ds.fadeOut("cyclone_run", this.vars.SLOWFADE);
        } // end of behavior for LOWRPM
        
        // LOWRPM behavior
        // uml: do [targetSpeed >= 50] TransitionTo(MEDIUMRPM)
        if (this.vars.targetSpeed >= 50)
        {
            // Step 1: Exit states until we reach `RUNNING` state (Least Common Ancestor for transition).
            LOWRPM_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `MEDIUMRPM`.
            MEDIUMRPM_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for LOWRPM
        
        // LOWRPM behavior
        // uml: do [targetSpeed == 0] TransitionTo(DECELERATING)
        if (this.vars.targetSpeed == 0)
        {
            // Step 1: Exit states until we reach `RUNNING` state (Least Common Ancestor for transition).
            LOWRPM_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `DECELERATING`.
            DECELERATING_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for LOWRPM
        
        // Check if event has been consumed before calling ancestor handler.
        if (!consume_event)
        {
            RUNNING_do();
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state MEDIUMRPM
    ////////////////////////////////////////////////////////////////////////////////
    
    private void MEDIUMRPM_enter()
    {
        this.stateId = StateId.MEDIUMRPM;
        
        // MEDIUMRPM behavior
        // uml: enter / { updateProcess();\nplayTime = 0;\nds.fadeIn("cyclone_run", QUICKFADE); }
        {
            // Step 1: execute action `updateProcess();\nplayTime = 0;\nds.fadeIn("cyclone_run", QUICKFADE);`
            updateProcess();
            this.vars.playTime = 0;
            this.vars.ds.fadeIn("cyclone_run", this.vars.QUICKFADE);
        } // end of behavior for MEDIUMRPM
    }
    
    private void MEDIUMRPM_exit()
    {
        this.stateId = StateId.RUNNING;
    }
    
    private void MEDIUMRPM_do()
    {
        boolean consume_event = false;
        
        // MEDIUMRPM behavior
        // uml: do [playTime <= WAITTIME] / { playTime += DOTIME(); }
        if (this.vars.playTime <= this.vars.WAITTIME)
        {
            // `do` events are not normally consumed.
            // Step 1: execute action `playTime += DOTIME();`
            this.vars.playTime += DOTIME();
        } // end of behavior for MEDIUMRPM
        
        // MEDIUMRPM behavior
        // uml: do [playTime == WAITTIME || WAITTIME == 0] / { ds.fadeOut("cyclone_lowrpm", SLOWFADE);\nds.fadeOut("cyclone_run1", SLOWFADE); }
        if (this.vars.playTime == this.vars.WAITTIME || this.vars.WAITTIME == 0)
        {
            // `do` events are not normally consumed.
            // Step 1: execute action `ds.fadeOut("cyclone_lowrpm", SLOWFADE);\nds.fadeOut("cyclone_run1", SLOWFADE);`
            this.vars.ds.fadeOut("cyclone_lowrpm", this.vars.SLOWFADE);
            this.vars.ds.fadeOut("cyclone_run1", this.vars.SLOWFADE);
        } // end of behavior for MEDIUMRPM
        
        // MEDIUMRPM behavior
        // uml: do [targetSpeed < 50] TransitionTo(LOWRPM)
        if (this.vars.targetSpeed < 50)
        {
            // Step 1: Exit states until we reach `RUNNING` state (Least Common Ancestor for transition).
            MEDIUMRPM_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `LOWRPM`.
            LOWRPM_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for MEDIUMRPM
        
        // MEDIUMRPM behavior
        // uml: do [targetSpeed >= 90] TransitionTo(HIGHRPM)
        if (this.vars.targetSpeed >= 90)
        {
            // Step 1: Exit states until we reach `RUNNING` state (Least Common Ancestor for transition).
            MEDIUMRPM_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `HIGHRPM`.
            HIGHRPM_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for MEDIUMRPM
        
        // Check if event has been consumed before calling ancestor handler.
        if (!consume_event)
        {
            RUNNING_do();
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state SHUTDOWN
    ////////////////////////////////////////////////////////////////////////////////
    
    private void SHUTDOWN_enter()
    {
        this.stateId = StateId.SHUTDOWN;
        
        // SHUTDOWN behavior
        // uml: enter / { updateProcess();\nds.playOneShot("cyclone_stop"); }
        {
            // Step 1: execute action `updateProcess();\nds.playOneShot("cyclone_stop");`
            updateProcess();
            this.vars.ds.playOneShot("cyclone_stop");
        } // end of behavior for SHUTDOWN
    }
    
    private void SHUTDOWN_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void SHUTDOWN_do()
    {
        // SHUTDOWN behavior
        // uml: do / { soundPlaying = ds.isPlaying("cyclone_stop"); }
        {
            // Step 1: execute action `soundPlaying = ds.isPlaying("cyclone_stop");`
            this.vars.soundPlaying = this.vars.ds.isPlaying("cyclone_stop");
        } // end of behavior for SHUTDOWN
        
        // SHUTDOWN behavior
        // uml: do [!soundPlaying] TransitionTo(OFF)
        if (!this.vars.soundPlaying)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            SHUTDOWN_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `OFF`.
            OFF_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for SHUTDOWN
        
        // No ancestor handles this event.
    }
    
    private void SHUTDOWN_leftstickbackward()
    {
        // SHUTDOWN behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT, STARTPRESSED) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for SHUTDOWN
        
        // No ancestor handles this event.
    }
    
    private void SHUTDOWN_leftstickbackwardleft()
    {
        // SHUTDOWN behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT, STARTPRESSED) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for SHUTDOWN
        
        // No ancestor handles this event.
    }
    
    private void SHUTDOWN_leftstickbackwardright()
    {
        // SHUTDOWN behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT, STARTPRESSED) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for SHUTDOWN
        
        // No ancestor handles this event.
    }
    
    private void SHUTDOWN_leftstickforward()
    {
        // SHUTDOWN behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT, STARTPRESSED) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for SHUTDOWN
        
        // No ancestor handles this event.
    }
    
    private void SHUTDOWN_leftstickforwardleft()
    {
        // SHUTDOWN behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT, STARTPRESSED) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for SHUTDOWN
        
        // No ancestor handles this event.
    }
    
    private void SHUTDOWN_leftstickforwardright()
    {
        // SHUTDOWN behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT, STARTPRESSED) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for SHUTDOWN
        
        // No ancestor handles this event.
    }
    
    private void SHUTDOWN_leftstickidle()
    {
        // SHUTDOWN behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT, STARTPRESSED) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for SHUTDOWN
        
        // No ancestor handles this event.
    }
    
    private void SHUTDOWN_leftstickleft()
    {
        // SHUTDOWN behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT, STARTPRESSED) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for SHUTDOWN
        
        // No ancestor handles this event.
    }
    
    private void SHUTDOWN_leftstickright()
    {
        // SHUTDOWN behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT, STARTPRESSED) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for SHUTDOWN
        
        // No ancestor handles this event.
    }
    
    private void SHUTDOWN_startpressed()
    {
        // SHUTDOWN behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT, STARTPRESSED) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for SHUTDOWN
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state STARTING
    ////////////////////////////////////////////////////////////////////////////////
    
    private void STARTING_enter()
    {
        this.stateId = StateId.STARTING;
        
        // STARTING behavior
        // uml: enter / { updateProcess();\nplayTime = 0;\nds.playOneShot("cyclone_start"); }
        {
            // Step 1: execute action `updateProcess();\nplayTime = 0;\nds.playOneShot("cyclone_start");`
            updateProcess();
            this.vars.playTime = 0;
            this.vars.ds.playOneShot("cyclone_start");
        } // end of behavior for STARTING
    }
    
    private void STARTING_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void STARTING_do()
    {
        // STARTING behavior
        // uml: do / { playTime += DOTIME();\nsoundAlmostDone = \n ds.almostDone("cyclone_start", playTime); }
        {
            // Step 1: execute action `playTime += DOTIME();\nsoundAlmostDone = \n ds.almostDone("cyclone_start", playTime);`
            this.vars.playTime += DOTIME();
            this.vars.soundAlmostDone = 
             this.vars.ds.almostDone("cyclone_start", this.vars.playTime);
        } // end of behavior for STARTING
        
        // STARTING behavior
        // uml: do [soundAlmostDone] TransitionTo(IDLE)
        if (this.vars.soundAlmostDone)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            STARTING_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `IDLE`.
            IDLE_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for STARTING
        
        // No ancestor handles this event.
    }
    
    private void STARTING_leftstickbackward()
    {
        // STARTING behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT, STARTPRESSED) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for STARTING
        
        // No ancestor handles this event.
    }
    
    private void STARTING_leftstickbackwardleft()
    {
        // STARTING behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT, STARTPRESSED) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for STARTING
        
        // No ancestor handles this event.
    }
    
    private void STARTING_leftstickbackwardright()
    {
        // STARTING behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT, STARTPRESSED) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for STARTING
        
        // No ancestor handles this event.
    }
    
    private void STARTING_leftstickforward()
    {
        // STARTING behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT, STARTPRESSED) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for STARTING
        
        // No ancestor handles this event.
    }
    
    private void STARTING_leftstickforwardleft()
    {
        // STARTING behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT, STARTPRESSED) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for STARTING
        
        // No ancestor handles this event.
    }
    
    private void STARTING_leftstickforwardright()
    {
        // STARTING behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT, STARTPRESSED) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for STARTING
        
        // No ancestor handles this event.
    }
    
    private void STARTING_leftstickidle()
    {
        // STARTING behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT, STARTPRESSED) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for STARTING
        
        // No ancestor handles this event.
    }
    
    private void STARTING_leftstickleft()
    {
        // STARTING behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT, STARTPRESSED) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for STARTING
        
        // No ancestor handles this event.
    }
    
    private void STARTING_leftstickright()
    {
        // STARTING behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT, STARTPRESSED) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for STARTING
        
        // No ancestor handles this event.
    }
    
    private void STARTING_startpressed()
    {
        // STARTING behavior
        // uml: (LEFTSTICKFORWARD, LEFTSTICKIDLE, LEFTSTICKFORWARDRIGHT, LEFTSTICKRIGHT, LEFTSTICKBACKWARDRIGHT, LEFTSTICKBACKWARD, LEFTSTICKBACKWARDLEFT, LEFTSTICKLEFT, LEFTSTICKFORWARDLEFT, STARTPRESSED) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for STARTING
        
        // No ancestor handles this event.
    }
    
    // Thread safe.
    public static String stateIdToString(StateId id)
    {
        switch (id)
        {
            case ROOT: return "ROOT";
            case IDLE: return "IDLE";
            case OFF: return "OFF";
            case RUNNING: return "RUNNING";
            case ACCELERATING: return "ACCELERATING";
            case DECELERATING: return "DECELERATING";
            case HIGHRPM: return "HIGHRPM";
            case LOWRPM: return "LOWRPM";
            case MEDIUMRPM: return "MEDIUMRPM";
            case SHUTDOWN: return "SHUTDOWN";
            case STARTING: return "STARTING";
            default: return "?";
        }
    }
    
    // Thread safe.
    public static String eventIdToString(EventId id)
    {
        switch (id)
        {
            case DO: return "DO";
            case LEFTSTICKBACKWARD: return "LEFTSTICKBACKWARD";
            case LEFTSTICKBACKWARDLEFT: return "LEFTSTICKBACKWARDLEFT";
            case LEFTSTICKBACKWARDRIGHT: return "LEFTSTICKBACKWARDRIGHT";
            case LEFTSTICKFORWARD: return "LEFTSTICKFORWARD";
            case LEFTSTICKFORWARDLEFT: return "LEFTSTICKFORWARDLEFT";
            case LEFTSTICKFORWARDRIGHT: return "LEFTSTICKFORWARDRIGHT";
            case LEFTSTICKIDLE: return "LEFTSTICKIDLE";
            case LEFTSTICKLEFT: return "LEFTSTICKLEFT";
            case LEFTSTICKRIGHT: return "LEFTSTICKRIGHT";
            case STARTPRESSED: return "STARTPRESSED";
            default: return "?";
        }
    }

    ////////////////////////////////////////////////////////////////////////////////
    // Inserted code by csx script
    ////////////////////////////////////////////////////////////////////////////////
    
    protected String[] getAllowedEvents(StateId id) {
        return switch (id) {
            case ROOT -> new String[0];  // No events
            case IDLE -> new String[]{"LEFTSTICKFORWARD", "LEFTSTICKIDLE", "LEFTSTICKFORWARDRIGHT", "LEFTSTICKRIGHT", "LEFTSTICKBACKWARDRIGHT", "LEFTSTICKBACKWARD", "LEFTSTICKBACKWARDLEFT", "LEFTSTICKLEFT", "LEFTSTICKFORWARDLEFT", "STARTPRESSED"};
            case OFF -> new String[]{"LEFTSTICKFORWARD", "LEFTSTICKIDLE", "LEFTSTICKFORWARDRIGHT", "LEFTSTICKRIGHT", "LEFTSTICKBACKWARDRIGHT", "LEFTSTICKBACKWARD", "LEFTSTICKBACKWARDLEFT", "LEFTSTICKLEFT", "LEFTSTICKFORWARDLEFT", "STARTPRESSED"};
            case RUNNING -> new String[]{"LEFTSTICKFORWARD", "LEFTSTICKFORWARDRIGHT", "LEFTSTICKRIGHT", "LEFTSTICKBACKWARDRIGHT", "LEFTSTICKBACKWARD", "LEFTSTICKBACKWARDLEFT", "LEFTSTICKLEFT", "LEFTSTICKFORWARDLEFT", "STARTPRESSED", "LEFTSTICKIDLE", "DO"};
            case ACCELERATING -> new String[]{"DO", "LEFTSTICKFORWARD", "LEFTSTICKFORWARDRIGHT", "LEFTSTICKRIGHT", "LEFTSTICKBACKWARDRIGHT", "LEFTSTICKBACKWARD", "LEFTSTICKBACKWARDLEFT", "LEFTSTICKLEFT", "LEFTSTICKFORWARDLEFT", "STARTPRESSED", "LEFTSTICKIDLE"};
            case DECELERATING -> new String[]{"DO", "LEFTSTICKFORWARD", "LEFTSTICKFORWARDRIGHT", "LEFTSTICKRIGHT", "LEFTSTICKBACKWARDRIGHT", "LEFTSTICKBACKWARD", "LEFTSTICKBACKWARDLEFT", "LEFTSTICKLEFT", "LEFTSTICKFORWARDLEFT", "STARTPRESSED", "LEFTSTICKIDLE"};
            case HIGHRPM -> new String[]{"DO", "LEFTSTICKFORWARD", "LEFTSTICKFORWARDRIGHT", "LEFTSTICKRIGHT", "LEFTSTICKBACKWARDRIGHT", "LEFTSTICKBACKWARD", "LEFTSTICKBACKWARDLEFT", "LEFTSTICKLEFT", "LEFTSTICKFORWARDLEFT", "STARTPRESSED", "LEFTSTICKIDLE"};
            case LOWRPM -> new String[]{"DO", "LEFTSTICKFORWARD", "LEFTSTICKFORWARDRIGHT", "LEFTSTICKRIGHT", "LEFTSTICKBACKWARDRIGHT", "LEFTSTICKBACKWARD", "LEFTSTICKBACKWARDLEFT", "LEFTSTICKLEFT", "LEFTSTICKFORWARDLEFT", "STARTPRESSED", "LEFTSTICKIDLE"};
            case MEDIUMRPM -> new String[]{"DO", "LEFTSTICKFORWARD", "LEFTSTICKFORWARDRIGHT", "LEFTSTICKRIGHT", "LEFTSTICKBACKWARDRIGHT", "LEFTSTICKBACKWARD", "LEFTSTICKBACKWARDLEFT", "LEFTSTICKLEFT", "LEFTSTICKFORWARDLEFT", "STARTPRESSED", "LEFTSTICKIDLE"};
            case SHUTDOWN -> new String[]{"DO", "LEFTSTICKFORWARD", "LEFTSTICKIDLE", "LEFTSTICKFORWARDRIGHT", "LEFTSTICKRIGHT", "LEFTSTICKBACKWARDRIGHT", "LEFTSTICKBACKWARD", "LEFTSTICKBACKWARDLEFT", "LEFTSTICKLEFT", "LEFTSTICKFORWARDLEFT", "STARTPRESSED"};
            case STARTING -> new String[]{"DO", "LEFTSTICKFORWARD", "LEFTSTICKIDLE", "LEFTSTICKFORWARDRIGHT", "LEFTSTICKRIGHT", "LEFTSTICKBACKWARDRIGHT", "LEFTSTICKBACKWARD", "LEFTSTICKBACKWARDLEFT", "LEFTSTICKLEFT", "LEFTSTICKFORWARDLEFT", "STARTPRESSED"};
            default -> new String[0];
        };
    }
    
    @Override
    protected String[] getAllEventNames()
    {
        EventId[] values = EventId.values();
        String[] names = new String[values.length];
        
        for (int i = 0; i < values.length; i++)
            names[i] = translateEventName(values[i].name());
        
        return names;
    }
    
    @Override
    protected String[] getAllStateNames()
    {
        StateId[] values = StateId.values();
        String[] names = new String[values.length];
        
        for (int i = 0; i < values.length; i++)
            names[i] = values[i].name();
        
        return names;
    }
    
    @Override
    protected String getCurrentStateString()
    {
        return stateIdToString(this.stateId);
    }
    
    @Override
    protected String[] getBaseAllowedEventsForCurrentState()
    {
        return getAllowedEvents(this.stateId);
    }
    
    // Allow sending strings to dispatchEvent(), with translate functionality
    @Override
    protected void dispatchEvent(String eventName)
    {
        String baseEventName = translateToBaseEventName(eventName);
        dispatchEvent(EventId.valueOf(baseEventName));
    }
    
    @Override
    protected void startSm()
    {
        start();
    }
    
    // See function name
    @SuppressWarnings("unused")
    private void suppressUnusedExitUpToStateHandler()
    {
        exitUpToStateHandler(StateId.ROOT);
    }
    
    ////////////////////////////////////////////////////////////////////////////////
    // End of csx-inserted code
    ////////////////////////////////////////////////////////////////////////////////
}
