// Autogenerated with StateSmith 0.19.0+ebc88ca27511ff019dec4076062d7ebc9acd4ee9.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

package tankpack;

// Generated state machine
public class Sm_Estop_Generated extends StateMachine
{
    public enum EventId
    {
        ESTOP,
        PS_BUTTONPRESSED,
        PS_BUTTONRELEASED,
        R1PRESSED,
        SHUTDOWN,
    }
    
    public final int EventIdCount = 5;
    
    public enum StateId
    {
        ROOT,
        ALERT,
        ESTOP,
        NORMAL,
    }
    
    public final int StateIdCount = 4;
    
    // Used internally by state machine. Feel free to inspect, but don't modify.
    public StateId stateId;
    
    // State machine variables. Can be used for inputs, outputs, user variables...
    public class Vars
    {
        // These variables can be referenced in diagram and are automatically prefixed with "this.vars." during code generation
        // Protected variables, must be set by inheriting class
        
        // Private variables, only used locally
        
        // Public variable, for outer classes to read
        public boolean eStop = false;
    }
    
    // Variables. Can be used for inputs, outputs, user variables...
    public Vars vars = new Vars();
    
    // State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
    public Sm_Estop_Generated()
    {
    }
    
    // Starts the state machine. Must be called before dispatching events. Not thread safe.
    public void start()
    {
        ROOT_enter();
        // ROOT behavior
        // uml: TransitionTo(ROOT.<InitialState>)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
            // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
            
            // ROOT.<InitialState> behavior
            // uml: TransitionTo(NORMAL)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `NORMAL`.
                NORMAL_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for ROOT.<InitialState>
        } // end of behavior for ROOT
    }
    
    // Dispatches an event to the state machine. Not thread safe.
    // Note! This function assumes that the `eventId` parameter is valid.
    public void dispatchEvent(EventId eventId)
    {
        switch (this.stateId)
        {
            // STATE: Sm_Estop_Generated
            case ROOT:
                // No events handled by this state (or its ancestors).
                break;
            
            // STATE: ALERT
            case ALERT:
                switch (eventId)
                {
                    case PS_BUTTONPRESSED: ALERT_ps_buttonpressed(); break;
                    case PS_BUTTONRELEASED: ALERT_ps_buttonreleased(); break;
                    case R1PRESSED: ALERT_r1pressed(); break;
                    case ESTOP: ALERT_estop(); break;
                }
                break;
            
            // STATE: ESTOP
            case ESTOP:
                // No events handled by this state (or its ancestors).
                break;
            
            // STATE: NORMAL
            case NORMAL:
                switch (eventId)
                {
                    case PS_BUTTONRELEASED: NORMAL_ps_buttonreleased(); break;
                    case R1PRESSED: NORMAL_r1pressed(); break;
                    case PS_BUTTONPRESSED: NORMAL_ps_buttonpressed(); break;
                    case SHUTDOWN: NORMAL_shutdown(); break;
                }
                break;
        }
        
    }
    
    // This function is used when StateSmith doesn't know what the active leaf state is at
    // compile time due to sub states or when multiple states need to be exited.
    private void exitUpToStateHandler(StateId desiredState)
    {
        while (this.stateId != desiredState)
        {
            switch (this.stateId)
            {
                case ALERT: ALERT_exit(); break;
                
                case ESTOP: ESTOP_exit(); break;
                
                case NORMAL: NORMAL_exit(); break;
                
                default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
            }
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state ROOT
    ////////////////////////////////////////////////////////////////////////////////
    
    private void ROOT_enter()
    {
        this.stateId = StateId.ROOT;
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state ALERT
    ////////////////////////////////////////////////////////////////////////////////
    
    private void ALERT_enter()
    {
        this.stateId = StateId.ALERT;
        
        // ALERT behavior
        // uml: enter / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for ALERT
    }
    
    private void ALERT_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void ALERT_estop()
    {
        // ALERT behavior
        // uml: (r1Pressed, eStop) TransitionTo(ESTOP)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            ALERT_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ESTOP`.
            ESTOP_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ALERT
        
        // No ancestor handles this event.
    }
    
    private void ALERT_ps_buttonpressed()
    {
        // ALERT behavior
        // uml: ps_buttonPressed / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for ALERT
        
        // No ancestor handles this event.
    }
    
    private void ALERT_ps_buttonreleased()
    {
        // ALERT behavior
        // uml: ps_buttonReleased TransitionTo(NORMAL)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            ALERT_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `NORMAL`.
            NORMAL_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ALERT
        
        // No ancestor handles this event.
    }
    
    private void ALERT_r1pressed()
    {
        // ALERT behavior
        // uml: (r1Pressed, eStop) TransitionTo(ESTOP)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            ALERT_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ESTOP`.
            ESTOP_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ALERT
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state ESTOP
    ////////////////////////////////////////////////////////////////////////////////
    
    private void ESTOP_enter()
    {
        this.stateId = StateId.ESTOP;
        
        // ESTOP behavior
        // uml: enter / { updateProcess();\neStop = TRUE(); }
        {
            // Step 1: execute action `updateProcess();\neStop = TRUE();`
            updateProcess();
            this.vars.eStop = TRUE();
        } // end of behavior for ESTOP
    }
    
    private void ESTOP_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state NORMAL
    ////////////////////////////////////////////////////////////////////////////////
    
    private void NORMAL_enter()
    {
        this.stateId = StateId.NORMAL;
        
        // NORMAL behavior
        // uml: enter / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for NORMAL
    }
    
    private void NORMAL_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void NORMAL_ps_buttonpressed()
    {
        // NORMAL behavior
        // uml: ps_buttonPressed TransitionTo(ALERT)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            NORMAL_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ALERT`.
            ALERT_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for NORMAL
        
        // No ancestor handles this event.
    }
    
    private void NORMAL_ps_buttonreleased()
    {
        // NORMAL behavior
        // uml: (ps_buttonReleased, r1Pressed) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for NORMAL
        
        // No ancestor handles this event.
    }
    
    private void NORMAL_r1pressed()
    {
        // NORMAL behavior
        // uml: (ps_buttonReleased, r1Pressed) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for NORMAL
        
        // No ancestor handles this event.
    }
    
    private void NORMAL_shutdown()
    {
        // NORMAL behavior
        // uml: shutdown TransitionTo(ESTOP)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            NORMAL_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ESTOP`.
            ESTOP_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for NORMAL
        
        // No ancestor handles this event.
    }
    
    // Thread safe.
    public static String stateIdToString(StateId id)
    {
        switch (id)
        {
            case ROOT: return "ROOT";
            case ALERT: return "ALERT";
            case ESTOP: return "ESTOP";
            case NORMAL: return "NORMAL";
            default: return "?";
        }
    }
    
    // Thread safe.
    public static String eventIdToString(EventId id)
    {
        switch (id)
        {
            case ESTOP: return "ESTOP";
            case PS_BUTTONPRESSED: return "PS_BUTTONPRESSED";
            case PS_BUTTONRELEASED: return "PS_BUTTONRELEASED";
            case R1PRESSED: return "R1PRESSED";
            case SHUTDOWN: return "SHUTDOWN";
            default: return "?";
        }
    }

    ////////////////////////////////////////////////////////////////////////////////
    // Inserted code by csx script
    ////////////////////////////////////////////////////////////////////////////////
    
    protected String[] getAllowedEvents(StateId id) {
        return switch (id) {
            case ROOT -> new String[0];  // No events
            case ALERT -> new String[]{"PS_BUTTONPRESSED", "PS_BUTTONRELEASED", "R1PRESSED", "ESTOP"};
            case ESTOP -> new String[]{"DO"};
            case NORMAL -> new String[]{"PS_BUTTONRELEASED", "R1PRESSED", "PS_BUTTONPRESSED", "SHUTDOWN"};
            default -> new String[0];
        };
    }
    
    @Override
    protected String[] getAllEventNames()
    {
        EventId[] values = EventId.values();
        String[] names = new String[values.length];
        
        for (int i = 0; i < values.length; i++)
            names[i] = translateEventName(values[i].name());
        
        return names;
    }
    
    @Override
    protected String[] getAllStateNames()
    {
        StateId[] values = StateId.values();
        String[] names = new String[values.length];
        
        for (int i = 0; i < values.length; i++)
            names[i] = values[i].name();
        
        return names;
    }
    
    @Override
    protected String getCurrentStateString()
    {
        return stateIdToString(this.stateId);
    }
    
    @Override
    protected String[] getBaseAllowedEventsForCurrentState()
    {
        return getAllowedEvents(this.stateId);
    }
    
    // Allow sending strings to dispatchEvent(), with translate functionality
    @Override
    protected void dispatchEvent(String eventName)
    {
        String baseEventName = translateToBaseEventName(eventName);
        dispatchEvent(EventId.valueOf(baseEventName));
    }
    
    @Override
    protected void startSm()
    {
        start();
    }
    
    // See function name
    @SuppressWarnings("unused")
    private void suppressUnusedExitUpToStateHandler()
    {
        exitUpToStateHandler(StateId.ROOT);
    }
    
    ////////////////////////////////////////////////////////////////////////////////
    // End of csx-inserted code
    ////////////////////////////////////////////////////////////////////////////////
}
