// Autogenerated with StateSmith 0.19.0-alpha-1+3da98b58a6e506bc06d88cba576dcc4df8809849.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

package tankpack;

// Generated state machine
public class Sm_GpioButton_Generated extends StateMachine
{
    public enum EventId
    {
        DO, // The `do` event is special. State event handlers do not consume this event (ancestors all get it too) unless a transition occurs.
    }
    
    public final int EventIdCount = 1;
    
    public enum StateId
    {
        ROOT,
        PRESSED,
        PRESSED1,
        PRESSED2,
        PRESSED3,
        RELEASED,
        RESTARTWIFI,
    }
    
    public final int StateIdCount = 7;
    
    // Used internally by state machine. Feel free to inspect, but don't modify.
    public StateId stateId;
    
    // State machine variables. Can be used for inputs, outputs, user variables...
    public class Vars
    {
        // These variables can be referenced in diagram and are automatically prefixed with "this.vars." during code generation
        // Protected variables, must be set by inheriting class
        protected Driver_Hardware dh;
        
        // Private variables, only used locally
        private boolean buttonPressed;
        private long timer;
    }
    
    // Variables. Can be used for inputs, outputs, user variables...
    public Vars vars = new Vars();
    
    // State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
    public Sm_GpioButton_Generated()
    {
    }
    
    // Starts the state machine. Must be called before dispatching events. Not thread safe.
    public void start()
    {
        ROOT_enter();
        // ROOT behavior
        // uml: TransitionTo(ROOT.<InitialState>)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
            // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
            
            // ROOT.<InitialState> behavior
            // uml: TransitionTo(RELEASED)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `RELEASED`.
                RELEASED_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for ROOT.<InitialState>
        } // end of behavior for ROOT
    }
    
    // Dispatches an event to the state machine. Not thread safe.
    // Note! This function assumes that the `eventId` parameter is valid.
    public void dispatchEvent(EventId eventId)
    {
        
        switch (this.stateId)
        {
            // STATE: Sm_GpioButton_Generated
            case ROOT:
                // state and ancestors have no handler for `do` event.
                break;
            
            // STATE: PRESSED
            case PRESSED:
                PRESSED_do(); 
                break;
            
            // STATE: PRESSED1
            case PRESSED1:
                PRESSED1_do(); 
                break;
            
            // STATE: PRESSED2
            case PRESSED2:
                PRESSED2_do(); 
                break;
            
            // STATE: PRESSED3
            case PRESSED3:
                PRESSED3_do(); 
                break;
            
            // STATE: RELEASED
            case RELEASED:
                RELEASED_do(); 
                break;
            
            // STATE: RESTARTWIFI
            case RESTARTWIFI:
                RESTARTWIFI_do(); 
                break;
        }
        
    }
    
    // This function is used when StateSmith doesn't know what the active leaf state is at
    // compile time due to sub states or when multiple states need to be exited.
    private void exitUpToStateHandler(StateId desiredState)
    {
        while (this.stateId != desiredState)
        {
            switch (this.stateId)
            {
                case PRESSED: PRESSED_exit(); break;
                
                case PRESSED1: PRESSED1_exit(); break;
                
                case PRESSED2: PRESSED2_exit(); break;
                
                case PRESSED3: PRESSED3_exit(); break;
                
                case RELEASED: RELEASED_exit(); break;
                
                case RESTARTWIFI: RESTARTWIFI_exit(); break;
                
                default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
            }
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state ROOT
    ////////////////////////////////////////////////////////////////////////////////
    
    private void ROOT_enter()
    {
        this.stateId = StateId.ROOT;
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state PRESSED
    ////////////////////////////////////////////////////////////////////////////////
    
    private void PRESSED_enter()
    {
        this.stateId = StateId.PRESSED;
        
        // PRESSED behavior
        // uml: enter / { timer = 0; }
        {
            // Step 1: execute action `timer = 0;`
            this.vars.timer = 0;
        } // end of behavior for PRESSED
    }
    
    private void PRESSED_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void PRESSED_do()
    {
        // PRESSED behavior
        // uml: do / { timer += DOTIME(); }
        {
            // Step 1: execute action `timer += DOTIME();`
            this.vars.timer += DOTIME();
        } // end of behavior for PRESSED
        
        // PRESSED behavior
        // uml: do [!buttonPressed] TransitionTo(RELEASED)
        if (!this.vars.buttonPressed)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            exitUpToStateHandler(StateId.ROOT);
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `RELEASED`.
            RELEASED_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for PRESSED
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state PRESSED1
    ////////////////////////////////////////////////////////////////////////////////
    
    private void PRESSED1_enter()
    {
        this.stateId = StateId.PRESSED1;
        
        // PRESSED1 behavior
        // uml: enter / { updateProcess();\nfireEvent("ledOn"); }
        {
            // Step 1: execute action `updateProcess();\nfireEvent("ledOn");`
            updateProcess();
            fireEvent("ledOn");
        } // end of behavior for PRESSED1
    }
    
    private void PRESSED1_exit()
    {
        // PRESSED1 behavior
        // uml: exit / { fireEvent("ledOff"); }
        {
            // Step 1: execute action `fireEvent("ledOff");`
            fireEvent("ledOff");
        } // end of behavior for PRESSED1
        
        this.stateId = StateId.PRESSED;
    }
    
    private void PRESSED1_do()
    {
        boolean consume_event = false;
        
        // PRESSED1 behavior
        // uml: do / { buttonPressed = dh.getButtonState(); }
        {
            // `do` events are not normally consumed.
            // Step 1: execute action `buttonPressed = dh.getButtonState();`
            this.vars.buttonPressed = this.vars.dh.getButtonState();
        } // end of behavior for PRESSED1
        
        // PRESSED1 behavior
        // uml: do [timer >= 2000] TransitionTo(PRESSED2)
        if (this.vars.timer >= 2000)
        {
            // Step 1: Exit states until we reach `PRESSED` state (Least Common Ancestor for transition).
            PRESSED1_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `PRESSED2`.
            PRESSED2_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for PRESSED1
        
        // Check if event has been consumed before calling ancestor handler.
        if (!consume_event)
        {
            PRESSED_do();
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state PRESSED2
    ////////////////////////////////////////////////////////////////////////////////
    
    private void PRESSED2_enter()
    {
        this.stateId = StateId.PRESSED2;
        
        // PRESSED2 behavior
        // uml: enter / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for PRESSED2
    }
    
    private void PRESSED2_exit()
    {
        this.stateId = StateId.PRESSED;
    }
    
    private void PRESSED2_do()
    {
        boolean consume_event = false;
        
        // PRESSED2 behavior
        // uml: do / { buttonPressed = dh.getButtonState(); }
        {
            // `do` events are not normally consumed.
            // Step 1: execute action `buttonPressed = dh.getButtonState();`
            this.vars.buttonPressed = this.vars.dh.getButtonState();
        } // end of behavior for PRESSED2
        
        // PRESSED2 behavior
        // uml: do [!buttonPressed] TransitionTo(PRESSED.<ExitPoint>(restartWifi))
        if (!this.vars.buttonPressed)
        {
            // Step 1: Exit states until we reach `PRESSED` state (Least Common Ancestor for transition).
            PRESSED2_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `PRESSED.<ExitPoint>(restartWifi)`.
            // PRESSED.<ExitPoint>(restartWifi) is a pseudo state and cannot have an `enter` trigger.
            
            // PRESSED.<ExitPoint>(restartWifi) behavior
            // uml: TransitionTo(RESTARTWIFI)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
                PRESSED_exit();
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `RESTARTWIFI`.
                RESTARTWIFI_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for PRESSED.<ExitPoint>(restartWifi)
        } // end of behavior for PRESSED2
        
        // PRESSED2 behavior
        // uml: do [timer >= 4000] TransitionTo(PRESSED3)
        if (this.vars.timer >= 4000)
        {
            // Step 1: Exit states until we reach `PRESSED` state (Least Common Ancestor for transition).
            PRESSED2_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `PRESSED3`.
            PRESSED3_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for PRESSED2
        
        // Check if event has been consumed before calling ancestor handler.
        if (!consume_event)
        {
            PRESSED_do();
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state PRESSED3
    ////////////////////////////////////////////////////////////////////////////////
    
    private void PRESSED3_enter()
    {
        this.stateId = StateId.PRESSED3;
        
        // PRESSED3 behavior
        // uml: enter / { updateProcess();\nfireEvent("ledOn"); }
        {
            // Step 1: execute action `updateProcess();\nfireEvent("ledOn");`
            updateProcess();
            fireEvent("ledOn");
        } // end of behavior for PRESSED3
    }
    
    private void PRESSED3_exit()
    {
        // PRESSED3 behavior
        // uml: exit / { fireEvent("ledOff"); }
        {
            // Step 1: execute action `fireEvent("ledOff");`
            fireEvent("ledOff");
        } // end of behavior for PRESSED3
        
        this.stateId = StateId.PRESSED;
    }
    
    private void PRESSED3_do()
    {
        boolean consume_event = false;
        
        // PRESSED3 behavior
        // uml: do / { buttonPressed = dh.getButtonState(); }
        {
            // `do` events are not normally consumed.
            // Step 1: execute action `buttonPressed = dh.getButtonState();`
            this.vars.buttonPressed = this.vars.dh.getButtonState();
        } // end of behavior for PRESSED3
        
        // PRESSED3 behavior
        // uml: do [timer >= 5000] / { fireEvent("shutdown"); }
        if (this.vars.timer >= 5000)
        {
            // `do` events are not normally consumed.
            // Step 1: execute action `fireEvent("shutdown");`
            fireEvent("shutdown");
        } // end of behavior for PRESSED3
        
        // Check if event has been consumed before calling ancestor handler.
        if (!consume_event)
        {
            PRESSED_do();
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state RELEASED
    ////////////////////////////////////////////////////////////////////////////////
    
    private void RELEASED_enter()
    {
        this.stateId = StateId.RELEASED;
        
        // RELEASED behavior
        // uml: enter / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for RELEASED
    }
    
    private void RELEASED_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void RELEASED_do()
    {
        // RELEASED behavior
        // uml: do / { buttonPressed = dh.getButtonState(); }
        {
            // Step 1: execute action `buttonPressed = dh.getButtonState();`
            this.vars.buttonPressed = this.vars.dh.getButtonState();
        } // end of behavior for RELEASED
        
        // RELEASED behavior
        // uml: do [buttonPressed] TransitionTo(PRESSED)
        if (this.vars.buttonPressed)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            RELEASED_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `PRESSED`.
            PRESSED_enter();
            
            // PRESSED.<InitialState> behavior
            // uml: TransitionTo(PRESSED1)
            {
                // Step 1: Exit states until we reach `PRESSED` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `PRESSED1`.
                PRESSED1_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for PRESSED.<InitialState>
        } // end of behavior for RELEASED
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state RESTARTWIFI
    ////////////////////////////////////////////////////////////////////////////////
    
    private void RESTARTWIFI_enter()
    {
        this.stateId = StateId.RESTARTWIFI;
        
        // RESTARTWIFI behavior
        // uml: enter / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for RESTARTWIFI
    }
    
    private void RESTARTWIFI_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void RESTARTWIFI_do()
    {
        // RESTARTWIFI behavior
        // uml: do / { fireEvent("restartWifi"); }
        {
            // Step 1: execute action `fireEvent("restartWifi");`
            fireEvent("restartWifi");
        } // end of behavior for RESTARTWIFI
        
        // RESTARTWIFI behavior
        // uml: do TransitionTo(RELEASED)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            RESTARTWIFI_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `RELEASED`.
            RELEASED_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for RESTARTWIFI
        
        // No ancestor handles this event.
    }
    
    // Thread safe.
    public static String stateIdToString(StateId id)
    {
        switch (id)
        {
            case ROOT: return "ROOT";
            case PRESSED: return "PRESSED";
            case PRESSED1: return "PRESSED1";
            case PRESSED2: return "PRESSED2";
            case PRESSED3: return "PRESSED3";
            case RELEASED: return "RELEASED";
            case RESTARTWIFI: return "RESTARTWIFI";
            default: return "?";
        }
    }
    
    // Thread safe.
    public static String eventIdToString(EventId id)
    {
        switch (id)
        {
            case DO: return "DO";
            default: return "?";
        }
    }

    ////////////////////////////////////////////////////////////////////////////////
    // Inserted code by csx script
    ////////////////////////////////////////////////////////////////////////////////
    
    protected String[] getAllowedEvents(StateId id) {
        return switch (id) {
            case ROOT -> new String[0];  // No events
            case PRESSED -> new String[]{"DO"};
            case PRESSED1 -> new String[]{"DO"};
            case PRESSED2 -> new String[]{"DO"};
            case PRESSED3 -> new String[]{"DO"};
            case RELEASED -> new String[]{"DO"};
            case RESTARTWIFI -> new String[]{"DO"};
            default -> new String[0];
        };
    }
    
    @Override
    protected String[] getAllEventNames()
    {
        EventId[] values = EventId.values();
        String[] names = new String[values.length];
        
        for (int i = 0; i < values.length; i++)
            names[i] = translateEventName(values[i].name());
        
        return names;
    }
    
    @Override
    protected String[] getAllStateNames()
    {
        StateId[] values = StateId.values();
        String[] names = new String[values.length];
        
        for (int i = 0; i < values.length; i++)
            names[i] = values[i].name();
        
        return names;
    }
    
    @Override
    protected String getCurrentStateString()
    {
        return stateIdToString(this.stateId);
    }
    
    @Override
    protected String[] getBaseAllowedEventsForCurrentState()
    {
        return getAllowedEvents(this.stateId);
    }
    
    // Allow sending strings to dispatchEvent(), with translate functionality
    @Override
    protected void dispatchEvent(String eventName)
    {
        String baseEventName = translateToBaseEventName(eventName);
        dispatchEvent(EventId.valueOf(baseEventName));
    }
    
    @Override
    protected void startSm()
    {
        start();
    }
    
    // See function name
    @SuppressWarnings("unused")
    private void suppressUnusedExitUpToStateHandler()
    {
        exitUpToStateHandler(StateId.ROOT);
    }
    
    ////////////////////////////////////////////////////////////////////////////////
    // End of csx-inserted code
    ////////////////////////////////////////////////////////////////////////////////
}
