// Autogenerated with StateSmith 0.19.0+ebc88ca27511ff019dec4076062d7ebc9acd4ee9.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

package tankpack;

import tankpack.enums.SensorPosition;

// Generated state machine
public class Sm_LineFollower_Generated extends StateMachine
{
//  ////////////////////////////////////////////////////////////////////////////////
    // Class code
    ////////////////////////////////////////////////////////////////////////////////
    
    // Must be overridden by inheriting class
    protected void debug()
    {
    }

    ////////////////////////////////////////////////////////////////////////////////
    // End of class code
    ////////////////////////////////////////////////////////////////////////////////


    public enum EventId
    {
        DO, // The `do` event is special. State event handlers do not consume this event (ancestors all get it too) unless a transition occurs.
        CROSSPRESSED,
        LEFTBLACK,
        LEFTWHITE,
        LOSTCONTROLLER,
        MIDDLEBLACK,
        MIDDLEWHITE,
        R2STICK,
        RIGHTBLACK,
        RIGHTWHITE,
        STARTFOLLOW,
        STOPFOLLOW,
    }
    
    public final int EventIdCount = 12;
    
    public enum StateId
    {
        ROOT,
        FOLLOWING,
        SEARCHING,
        STARTING,
        TRACKING_FORWARD,
        TRACKING_LEFT,
        TRACKING_RIGHT,
        TRACKING_ROTATELEFT,
        TRACKING_ROTATERIGHT,
        IDLE,
    }
    
    public final int StateIdCount = 10;
    
    public enum FOLLOWING_HistoryId
    {
        STARTING, // default transition
        SEARCHING,
        TRACKING_ROTATELEFT,
        TRACKING_FORWARD,
        TRACKING_ROTATERIGHT,
        TRACKING_RIGHT,
        TRACKING_LEFT,
    }

    
    // Used internally by state machine. Feel free to inspect, but don't modify.
    public StateId stateId;
    
    // State machine variables. Can be used for inputs, outputs, user variables...
    public class Vars
    {
        public FOLLOWING_HistoryId FOLLOWING_history;
        // These variables can be referenced in diagram and are automatically prefixed with "this.vars." during code generation
        // Protected variables, must be set by inheriting class
        protected boolean localDebug;
        protected Sm_Sensor[] sensors;
        protected int followSpeed;
        protected int maxEasyTurnCount;
        
        // Private variables, only used locally
        private final SensorPosition UNKNOWN = null;
        private final SensorPosition LEFT = SensorPosition.Left;
        private final SensorPosition RIGHT = SensorPosition.Right;
        
        private boolean leftBlack;
        private boolean rightBlack;
        private int count;
        private SensorPosition latestBlack;
    }
    
    // Variables. Can be used for inputs, outputs, user variables...
    public Vars vars = new Vars();
    
    // State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
    public Sm_LineFollower_Generated()
    {
    }
    
    // Starts the state machine. Must be called before dispatching events. Not thread safe.
    public void start()
    {
        ROOT_enter();
        // ROOT behavior
        // uml: TransitionTo(ROOT.<InitialState>)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
            // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
            
            // ROOT.<InitialState> behavior
            // uml: TransitionTo(IDLE)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `IDLE`.
                IDLE_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for ROOT.<InitialState>
        } // end of behavior for ROOT
    }
    
    // Dispatches an event to the state machine. Not thread safe.
    // Note! This function assumes that the `eventId` parameter is valid.
    public void dispatchEvent(EventId eventId)
    {
        switch (this.stateId)
        {
            // STATE: Sm_LineFollower_Generated
            case ROOT:
                // No events handled by this state (or its ancestors).
                break;
            
            // STATE: FOLLOWING
            case FOLLOWING:
                switch (eventId)
                {
                    case DO: FOLLOWING_do(); break;
                    case LEFTBLACK: FOLLOWING_leftblack(); break;
                    case LEFTWHITE: FOLLOWING_leftwhite(); break;
                    case RIGHTBLACK: FOLLOWING_rightblack(); break;
                    case RIGHTWHITE: FOLLOWING_rightwhite(); break;
                    case CROSSPRESSED: FOLLOWING_crosspressed(); break;
                    case LOSTCONTROLLER: FOLLOWING_lostcontroller(); break;
                    case STOPFOLLOW: FOLLOWING_stopfollow(); break;
                    case R2STICK: FOLLOWING_r2stick(); break;
                }
                break;
            
            // STATE: SEARCHING
            case SEARCHING:
                switch (eventId)
                {
                    case MIDDLEWHITE: SEARCHING_middlewhite(); break;
                    case MIDDLEBLACK: SEARCHING_middleblack(); break;
                    case DO: SEARCHING_do(); break;
                    case R2STICK: FOLLOWING_r2stick(); break; // First ancestor handler for this event
                    case STOPFOLLOW: FOLLOWING_stopfollow(); break; // First ancestor handler for this event
                    case LOSTCONTROLLER: FOLLOWING_lostcontroller(); break; // First ancestor handler for this event
                    case CROSSPRESSED: FOLLOWING_crosspressed(); break; // First ancestor handler for this event
                    case LEFTBLACK: FOLLOWING_leftblack(); break; // First ancestor handler for this event
                    case LEFTWHITE: FOLLOWING_leftwhite(); break; // First ancestor handler for this event
                    case RIGHTBLACK: FOLLOWING_rightblack(); break; // First ancestor handler for this event
                    case RIGHTWHITE: FOLLOWING_rightwhite(); break; // First ancestor handler for this event
                }
                break;
            
            // STATE: STARTING
            case STARTING:
                switch (eventId)
                {
                    case DO: STARTING_do(); break;
                    case R2STICK: FOLLOWING_r2stick(); break; // First ancestor handler for this event
                    case STOPFOLLOW: FOLLOWING_stopfollow(); break; // First ancestor handler for this event
                    case LOSTCONTROLLER: FOLLOWING_lostcontroller(); break; // First ancestor handler for this event
                    case CROSSPRESSED: FOLLOWING_crosspressed(); break; // First ancestor handler for this event
                    case LEFTBLACK: FOLLOWING_leftblack(); break; // First ancestor handler for this event
                    case LEFTWHITE: FOLLOWING_leftwhite(); break; // First ancestor handler for this event
                    case RIGHTBLACK: FOLLOWING_rightblack(); break; // First ancestor handler for this event
                    case RIGHTWHITE: FOLLOWING_rightwhite(); break; // First ancestor handler for this event
                }
                break;
            
            // STATE: TRACKING_FORWARD
            case TRACKING_FORWARD:
                switch (eventId)
                {
                    case MIDDLEWHITE: TRACKING_FORWARD_middlewhite(); break;
                    case R2STICK: FOLLOWING_r2stick(); break; // First ancestor handler for this event
                    case STOPFOLLOW: FOLLOWING_stopfollow(); break; // First ancestor handler for this event
                    case LOSTCONTROLLER: FOLLOWING_lostcontroller(); break; // First ancestor handler for this event
                    case CROSSPRESSED: FOLLOWING_crosspressed(); break; // First ancestor handler for this event
                    case DO: FOLLOWING_do(); break; // First ancestor handler for this event
                    case LEFTBLACK: FOLLOWING_leftblack(); break; // First ancestor handler for this event
                    case LEFTWHITE: FOLLOWING_leftwhite(); break; // First ancestor handler for this event
                    case RIGHTBLACK: FOLLOWING_rightblack(); break; // First ancestor handler for this event
                    case RIGHTWHITE: FOLLOWING_rightwhite(); break; // First ancestor handler for this event
                }
                break;
            
            // STATE: TRACKING_LEFT
            case TRACKING_LEFT:
                switch (eventId)
                {
                    case MIDDLEWHITE: TRACKING_LEFT_middlewhite(); break;
                    case DO: TRACKING_LEFT_do(); break;
                    case MIDDLEBLACK: TRACKING_LEFT_middleblack(); break;
                    case R2STICK: FOLLOWING_r2stick(); break; // First ancestor handler for this event
                    case STOPFOLLOW: FOLLOWING_stopfollow(); break; // First ancestor handler for this event
                    case LOSTCONTROLLER: FOLLOWING_lostcontroller(); break; // First ancestor handler for this event
                    case CROSSPRESSED: FOLLOWING_crosspressed(); break; // First ancestor handler for this event
                    case LEFTBLACK: FOLLOWING_leftblack(); break; // First ancestor handler for this event
                    case LEFTWHITE: FOLLOWING_leftwhite(); break; // First ancestor handler for this event
                    case RIGHTBLACK: FOLLOWING_rightblack(); break; // First ancestor handler for this event
                    case RIGHTWHITE: FOLLOWING_rightwhite(); break; // First ancestor handler for this event
                }
                break;
            
            // STATE: TRACKING_RIGHT
            case TRACKING_RIGHT:
                switch (eventId)
                {
                    case MIDDLEWHITE: TRACKING_RIGHT_middlewhite(); break;
                    case DO: TRACKING_RIGHT_do(); break;
                    case MIDDLEBLACK: TRACKING_RIGHT_middleblack(); break;
                    case R2STICK: FOLLOWING_r2stick(); break; // First ancestor handler for this event
                    case STOPFOLLOW: FOLLOWING_stopfollow(); break; // First ancestor handler for this event
                    case LOSTCONTROLLER: FOLLOWING_lostcontroller(); break; // First ancestor handler for this event
                    case CROSSPRESSED: FOLLOWING_crosspressed(); break; // First ancestor handler for this event
                    case LEFTBLACK: FOLLOWING_leftblack(); break; // First ancestor handler for this event
                    case LEFTWHITE: FOLLOWING_leftwhite(); break; // First ancestor handler for this event
                    case RIGHTBLACK: FOLLOWING_rightblack(); break; // First ancestor handler for this event
                    case RIGHTWHITE: FOLLOWING_rightwhite(); break; // First ancestor handler for this event
                }
                break;
            
            // STATE: TRACKING_ROTATELEFT
            case TRACKING_ROTATELEFT:
                switch (eventId)
                {
                    case MIDDLEWHITE: TRACKING_ROTATELEFT_middlewhite(); break;
                    case MIDDLEBLACK: TRACKING_ROTATELEFT_middleblack(); break;
                    case DO: TRACKING_ROTATELEFT_do(); break;
                    case R2STICK: FOLLOWING_r2stick(); break; // First ancestor handler for this event
                    case STOPFOLLOW: FOLLOWING_stopfollow(); break; // First ancestor handler for this event
                    case LOSTCONTROLLER: FOLLOWING_lostcontroller(); break; // First ancestor handler for this event
                    case CROSSPRESSED: FOLLOWING_crosspressed(); break; // First ancestor handler for this event
                    case LEFTBLACK: FOLLOWING_leftblack(); break; // First ancestor handler for this event
                    case LEFTWHITE: FOLLOWING_leftwhite(); break; // First ancestor handler for this event
                    case RIGHTBLACK: FOLLOWING_rightblack(); break; // First ancestor handler for this event
                    case RIGHTWHITE: FOLLOWING_rightwhite(); break; // First ancestor handler for this event
                }
                break;
            
            // STATE: TRACKING_ROTATERIGHT
            case TRACKING_ROTATERIGHT:
                switch (eventId)
                {
                    case MIDDLEWHITE: TRACKING_ROTATERIGHT_middlewhite(); break;
                    case MIDDLEBLACK: TRACKING_ROTATERIGHT_middleblack(); break;
                    case DO: TRACKING_ROTATERIGHT_do(); break;
                    case R2STICK: FOLLOWING_r2stick(); break; // First ancestor handler for this event
                    case STOPFOLLOW: FOLLOWING_stopfollow(); break; // First ancestor handler for this event
                    case LOSTCONTROLLER: FOLLOWING_lostcontroller(); break; // First ancestor handler for this event
                    case CROSSPRESSED: FOLLOWING_crosspressed(); break; // First ancestor handler for this event
                    case LEFTBLACK: FOLLOWING_leftblack(); break; // First ancestor handler for this event
                    case LEFTWHITE: FOLLOWING_leftwhite(); break; // First ancestor handler for this event
                    case RIGHTBLACK: FOLLOWING_rightblack(); break; // First ancestor handler for this event
                    case RIGHTWHITE: FOLLOWING_rightwhite(); break; // First ancestor handler for this event
                }
                break;
            
            // STATE: IDLE
            case IDLE:
                switch (eventId)
                {
                    case R2STICK: IDLE_r2stick(); break;
                    case STOPFOLLOW: IDLE_stopfollow(); break;
                    case LOSTCONTROLLER: IDLE_lostcontroller(); break;
                    case CROSSPRESSED: IDLE_crosspressed(); break;
                    case STARTFOLLOW: IDLE_startfollow(); break;
                }
                break;
        }
        
    }
    
    // This function is used when StateSmith doesn't know what the active leaf state is at
    // compile time due to sub states or when multiple states need to be exited.
    private void exitUpToStateHandler(StateId desiredState)
    {
        while (this.stateId != desiredState)
        {
            switch (this.stateId)
            {
                case FOLLOWING: FOLLOWING_exit(); break;
                
                case SEARCHING: SEARCHING_exit(); break;
                
                case STARTING: STARTING_exit(); break;
                
                case TRACKING_FORWARD: TRACKING_FORWARD_exit(); break;
                
                case TRACKING_LEFT: TRACKING_LEFT_exit(); break;
                
                case TRACKING_RIGHT: TRACKING_RIGHT_exit(); break;
                
                case TRACKING_ROTATELEFT: TRACKING_ROTATELEFT_exit(); break;
                
                case TRACKING_ROTATERIGHT: TRACKING_ROTATERIGHT_exit(); break;
                
                case IDLE: IDLE_exit(); break;
                
                default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
            }
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state ROOT
    ////////////////////////////////////////////////////////////////////////////////
    
    private void ROOT_enter()
    {
        this.stateId = StateId.ROOT;
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state FOLLOWING
    ////////////////////////////////////////////////////////////////////////////////
    
    private void FOLLOWING_enter()
    {
        this.stateId = StateId.FOLLOWING;
        
        // FOLLOWING behavior
        // uml: enter / { latestBlack = UNKNOWN; }
        {
            // Step 1: execute action `latestBlack = UNKNOWN;`
            this.vars.latestBlack = this.vars.UNKNOWN;
        } // end of behavior for FOLLOWING
    }
    
    private void FOLLOWING_exit()
    {
        // FOLLOWING behavior
        // uml: exit / { fireEvent("leftstickIdle"); }
        {
            // Step 1: execute action `fireEvent("leftstickIdle");`
            fireEvent("leftstickIdle");
        } // end of behavior for FOLLOWING
        
        this.stateId = StateId.ROOT;
    }
    
    private void FOLLOWING_crosspressed()
    {
        // FOLLOWING behavior
        // uml: (CROSSPRESSED, LOSTCONTROLLER) / { updateProcess();\nfireEvent("stopFollow"); }
        {
            // Step 1: execute action `updateProcess();\nfireEvent("stopFollow");`
            updateProcess();
            fireEvent("stopFollow");
        } // end of behavior for FOLLOWING
        
        // No ancestor handles this event.
    }
    
    private void FOLLOWING_do()
    {
        // FOLLOWING behavior
        // uml: do [localDebug] / { debug(); }
        if (this.vars.localDebug)
        {
            // Step 1: execute action `debug();`
            debug();
        } // end of behavior for FOLLOWING
        
        // No ancestor handles this event.
    }
    
    private void FOLLOWING_leftblack()
    {
        // FOLLOWING behavior
        // uml: LEFTBLACK / { updateProcess();\nleftBlack = TRUE();\nlatestBlack = LEFT; }
        {
            // Step 1: execute action `updateProcess();\nleftBlack = TRUE();\nlatestBlack = LEFT;`
            updateProcess();
            this.vars.leftBlack = TRUE();
            this.vars.latestBlack = this.vars.LEFT;
        } // end of behavior for FOLLOWING
        
        // No ancestor handles this event.
    }
    
    private void FOLLOWING_leftwhite()
    {
        // FOLLOWING behavior
        // uml: LEFTWHITE / { updateProcess();\nleftBlack = FALSE(); }
        {
            // Step 1: execute action `updateProcess();\nleftBlack = FALSE();`
            updateProcess();
            this.vars.leftBlack = FALSE();
        } // end of behavior for FOLLOWING
        
        // No ancestor handles this event.
    }
    
    private void FOLLOWING_lostcontroller()
    {
        // FOLLOWING behavior
        // uml: (CROSSPRESSED, LOSTCONTROLLER) / { updateProcess();\nfireEvent("stopFollow"); }
        {
            // Step 1: execute action `updateProcess();\nfireEvent("stopFollow");`
            updateProcess();
            fireEvent("stopFollow");
        } // end of behavior for FOLLOWING
        
        // No ancestor handles this event.
    }
    
    private void FOLLOWING_r2stick()
    {
        // FOLLOWING behavior
        // uml: R2Stick TransitionTo(FOLLOWING.<History>)
        {
            // Step 1: Exit states until we reach `FOLLOWING` state (Least Common Ancestor for transition).
            exitUpToStateHandler(StateId.FOLLOWING);
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `FOLLOWING.<History>`.
            // FOLLOWING.<History> is a pseudo state and cannot have an `enter` trigger.
            
            // FOLLOWING.<History> behavior
            // uml: [$gil(this.vars.FOLLOWING_history == FOLLOWING_HistoryId.SEARCHING)] TransitionTo(SEARCHING)
            if (this.vars.FOLLOWING_history == FOLLOWING_HistoryId.SEARCHING)
            {
                // Step 1: Exit states until we reach `FOLLOWING` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `SEARCHING`.
                SEARCHING_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for FOLLOWING.<History>
            
            // FOLLOWING.<History> behavior
            // uml: [$gil(this.vars.FOLLOWING_history == FOLLOWING_HistoryId.TRACKING_ROTATELEFT)] TransitionTo(TRACKING_ROTATELEFT)
            if (this.vars.FOLLOWING_history == FOLLOWING_HistoryId.TRACKING_ROTATELEFT)
            {
                // Step 1: Exit states until we reach `FOLLOWING` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `TRACKING_ROTATELEFT`.
                TRACKING_ROTATELEFT_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for FOLLOWING.<History>
            
            // FOLLOWING.<History> behavior
            // uml: [$gil(this.vars.FOLLOWING_history == FOLLOWING_HistoryId.TRACKING_FORWARD)] TransitionTo(TRACKING_FORWARD)
            if (this.vars.FOLLOWING_history == FOLLOWING_HistoryId.TRACKING_FORWARD)
            {
                // Step 1: Exit states until we reach `FOLLOWING` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `TRACKING_FORWARD`.
                TRACKING_FORWARD_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for FOLLOWING.<History>
            
            // FOLLOWING.<History> behavior
            // uml: [$gil(this.vars.FOLLOWING_history == FOLLOWING_HistoryId.TRACKING_ROTATERIGHT)] TransitionTo(TRACKING_ROTATERIGHT)
            if (this.vars.FOLLOWING_history == FOLLOWING_HistoryId.TRACKING_ROTATERIGHT)
            {
                // Step 1: Exit states until we reach `FOLLOWING` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `TRACKING_ROTATERIGHT`.
                TRACKING_ROTATERIGHT_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for FOLLOWING.<History>
            
            // FOLLOWING.<History> behavior
            // uml: [$gil(this.vars.FOLLOWING_history == FOLLOWING_HistoryId.TRACKING_RIGHT)] TransitionTo(TRACKING_RIGHT)
            if (this.vars.FOLLOWING_history == FOLLOWING_HistoryId.TRACKING_RIGHT)
            {
                // Step 1: Exit states until we reach `FOLLOWING` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `TRACKING_RIGHT`.
                TRACKING_RIGHT_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for FOLLOWING.<History>
            
            // FOLLOWING.<History> behavior
            // uml: [$gil(this.vars.FOLLOWING_history == FOLLOWING_HistoryId.TRACKING_LEFT)] TransitionTo(TRACKING_LEFT)
            if (this.vars.FOLLOWING_history == FOLLOWING_HistoryId.TRACKING_LEFT)
            {
                // Step 1: Exit states until we reach `FOLLOWING` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `TRACKING_LEFT`.
                TRACKING_LEFT_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for FOLLOWING.<History>
            
            // FOLLOWING.<History> behavior
            // uml: else TransitionTo(STARTING)
            {
                // Step 1: Exit states until we reach `FOLLOWING` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `STARTING`.
                STARTING_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for FOLLOWING.<History>
        } // end of behavior for FOLLOWING
        
        // No ancestor handles this event.
    }
    
    private void FOLLOWING_rightblack()
    {
        // FOLLOWING behavior
        // uml: RIGHTBLACK / { updateProcess();\nrightBlack = TRUE();\nlatestBlack = RIGHT; }
        {
            // Step 1: execute action `updateProcess();\nrightBlack = TRUE();\nlatestBlack = RIGHT;`
            updateProcess();
            this.vars.rightBlack = TRUE();
            this.vars.latestBlack = this.vars.RIGHT;
        } // end of behavior for FOLLOWING
        
        // No ancestor handles this event.
    }
    
    private void FOLLOWING_rightwhite()
    {
        // FOLLOWING behavior
        // uml: RIGHTWHITE / { updateProcess();\nrightBlack = FALSE(); }
        {
            // Step 1: execute action `updateProcess();\nrightBlack = FALSE();`
            updateProcess();
            this.vars.rightBlack = FALSE();
        } // end of behavior for FOLLOWING
        
        // No ancestor handles this event.
    }
    
    private void FOLLOWING_stopfollow()
    {
        // FOLLOWING behavior
        // uml: STOPFOLLOW TransitionTo(IDLE)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            exitUpToStateHandler(StateId.ROOT);
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `IDLE`.
            IDLE_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for FOLLOWING
        
        // No ancestor handles this event.
    }
    
    private void FOLLOWING_EntryPoint_left__transition()
    {
        // FOLLOWING.<EntryPoint>(left) behavior
        // uml: TransitionTo(TRACKING_ROTATELEFT)
        {
            // Step 1: Exit states until we reach `FOLLOWING` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `TRACKING_ROTATELEFT`.
            TRACKING_ROTATELEFT_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for FOLLOWING.<EntryPoint>(left)
    }
    
    private void FOLLOWING_EntryPoint_right__transition()
    {
        // FOLLOWING.<EntryPoint>(right) behavior
        // uml: TransitionTo(TRACKING_ROTATERIGHT)
        {
            // Step 1: Exit states until we reach `FOLLOWING` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `TRACKING_ROTATERIGHT`.
            TRACKING_ROTATERIGHT_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for FOLLOWING.<EntryPoint>(right)
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state SEARCHING
    ////////////////////////////////////////////////////////////////////////////////
    
    private void SEARCHING_enter()
    {
        this.stateId = StateId.SEARCHING;
        
        // SEARCHING behavior
        // uml: enter / { updateProcess();\n\n// Rotate right\nfireEvent("leftstickRight", followSpeed); }
        {
            // Step 1: execute action `updateProcess();\n\n// Rotate right\nfireEvent("leftstickRight", followSpeed);`
            updateProcess();
            
            // Rotate right
            fireEvent("leftstickRight", this.vars.followSpeed);
        } // end of behavior for SEARCHING
        
        // SEARCHING behavior
        // uml: enter / { $gil(this.vars.FOLLOWING_history = FOLLOWING_HistoryId.SEARCHING;) }
        {
            // Step 1: execute action `$gil(this.vars.FOLLOWING_history = FOLLOWING_HistoryId.SEARCHING;)`
            this.vars.FOLLOWING_history = FOLLOWING_HistoryId.SEARCHING;
        } // end of behavior for SEARCHING
    }
    
    private void SEARCHING_exit()
    {
        this.stateId = StateId.FOLLOWING;
    }
    
    private void SEARCHING_do()
    {
        boolean consume_event = false;
        
        // SEARCHING behavior
        // uml: do [rightBlack] TransitionTo(TRACKING_ROTATERIGHT)
        if (this.vars.rightBlack)
        {
            // Step 1: Exit states until we reach `FOLLOWING` state (Least Common Ancestor for transition).
            SEARCHING_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `TRACKING_ROTATERIGHT`.
            TRACKING_ROTATERIGHT_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for SEARCHING
        
        // SEARCHING behavior
        // uml: do [leftBlack] TransitionTo(TRACKING_ROTATELEFT)
        if (this.vars.leftBlack)
        {
            // Step 1: Exit states until we reach `FOLLOWING` state (Least Common Ancestor for transition).
            SEARCHING_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `TRACKING_ROTATELEFT`.
            TRACKING_ROTATELEFT_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for SEARCHING
        
        // Check if event has been consumed before calling ancestor handler.
        if (!consume_event)
        {
            FOLLOWING_do();
        }
    }
    
    private void SEARCHING_middleblack()
    {
        // SEARCHING behavior
        // uml: MIDDLEBLACK TransitionTo(TRACKING_FORWARD)
        {
            // Step 1: Exit states until we reach `FOLLOWING` state (Least Common Ancestor for transition).
            SEARCHING_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `TRACKING_FORWARD`.
            TRACKING_FORWARD_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for SEARCHING
        
        // No ancestor handles this event.
    }
    
    private void SEARCHING_middlewhite()
    {
        // SEARCHING behavior
        // uml: MIDDLEWHITE / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for SEARCHING
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state STARTING
    ////////////////////////////////////////////////////////////////////////////////
    
    private void STARTING_enter()
    {
        this.stateId = StateId.STARTING;
        
        // STARTING behavior
        // uml: enter / { count = 0;\nupdateProcess(); }
        {
            // Step 1: execute action `count = 0;\nupdateProcess();`
            this.vars.count = 0;
            updateProcess();
        } // end of behavior for STARTING
        
        // STARTING behavior
        // uml: enter / { $gil(this.vars.FOLLOWING_history = FOLLOWING_HistoryId.STARTING;) }
        {
            // Step 1: execute action `$gil(this.vars.FOLLOWING_history = FOLLOWING_HistoryId.STARTING;)`
            this.vars.FOLLOWING_history = FOLLOWING_HistoryId.STARTING;
        } // end of behavior for STARTING
    }
    
    private void STARTING_exit()
    {
        this.stateId = StateId.FOLLOWING;
    }
    
    private void STARTING_do()
    {
        boolean consume_event = false;
        
        // STARTING behavior
        // uml: do / { count++; }
        {
            // `do` events are not normally consumed.
            // Step 1: execute action `count++;`
            this.vars.count++;
        } // end of behavior for STARTING
        
        // STARTING behavior
        // uml: do [count > 0] TransitionTo(SEARCHING)
        if (this.vars.count > 0)
        {
            // Step 1: Exit states until we reach `FOLLOWING` state (Least Common Ancestor for transition).
            STARTING_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `SEARCHING`.
            SEARCHING_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for STARTING
        
        // Check if event has been consumed before calling ancestor handler.
        if (!consume_event)
        {
            FOLLOWING_do();
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state TRACKING_FORWARD
    ////////////////////////////////////////////////////////////////////////////////
    
    private void TRACKING_FORWARD_enter()
    {
        this.stateId = StateId.TRACKING_FORWARD;
        
        // TRACKING_FORWARD behavior
        // uml: enter / { updateProcess();\n\n// Forward\nfireEvent("leftstickForward", followSpeed); }
        {
            // Step 1: execute action `updateProcess();\n\n// Forward\nfireEvent("leftstickForward", followSpeed);`
            updateProcess();
            
            // Forward
            fireEvent("leftstickForward", this.vars.followSpeed);
        } // end of behavior for TRACKING_FORWARD
        
        // TRACKING_FORWARD behavior
        // uml: enter / { $gil(this.vars.FOLLOWING_history = FOLLOWING_HistoryId.TRACKING_FORWARD;) }
        {
            // Step 1: execute action `$gil(this.vars.FOLLOWING_history = FOLLOWING_HistoryId.TRACKING_FORWARD;)`
            this.vars.FOLLOWING_history = FOLLOWING_HistoryId.TRACKING_FORWARD;
        } // end of behavior for TRACKING_FORWARD
    }
    
    private void TRACKING_FORWARD_exit()
    {
        this.stateId = StateId.FOLLOWING;
    }
    
    private void TRACKING_FORWARD_middlewhite()
    {
        // TRACKING_FORWARD behavior
        // uml: MIDDLEWHITE [leftBlack] TransitionTo(TRACKING_ROTATELEFT)
        if (this.vars.leftBlack)
        {
            // Step 1: Exit states until we reach `FOLLOWING` state (Least Common Ancestor for transition).
            TRACKING_FORWARD_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `TRACKING_ROTATELEFT`.
            TRACKING_ROTATELEFT_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for TRACKING_FORWARD
        
        // TRACKING_FORWARD behavior
        // uml: MIDDLEWHITE [rightBlack] TransitionTo(TRACKING_ROTATERIGHT)
        if (this.vars.rightBlack)
        {
            // Step 1: Exit states until we reach `FOLLOWING` state (Least Common Ancestor for transition).
            TRACKING_FORWARD_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `TRACKING_ROTATERIGHT`.
            TRACKING_ROTATERIGHT_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for TRACKING_FORWARD
        
        // TRACKING_FORWARD behavior
        // uml: MIDDLEWHITE [!leftBlack && !rightBlack && latestBlack == LEFT] TransitionTo(TRACKING_LEFT)
        if (!this.vars.leftBlack && !this.vars.rightBlack && this.vars.latestBlack == this.vars.LEFT)
        {
            // Step 1: Exit states until we reach `FOLLOWING` state (Least Common Ancestor for transition).
            TRACKING_FORWARD_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `TRACKING_LEFT`.
            TRACKING_LEFT_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for TRACKING_FORWARD
        
        // TRACKING_FORWARD behavior
        // uml: MIDDLEWHITE [!leftBlack && !rightBlack && latestBlack == RIGHT] TransitionTo(TRACKING_RIGHT)
        if (!this.vars.leftBlack && !this.vars.rightBlack && this.vars.latestBlack == this.vars.RIGHT)
        {
            // Step 1: Exit states until we reach `FOLLOWING` state (Least Common Ancestor for transition).
            TRACKING_FORWARD_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `TRACKING_RIGHT`.
            TRACKING_RIGHT_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for TRACKING_FORWARD
        
        // TRACKING_FORWARD behavior
        // uml: MIDDLEWHITE [!leftBlack && !rightBlack && latestBlack == UNKNOWN] TransitionTo(SEARCHING)
        if (!this.vars.leftBlack && !this.vars.rightBlack && this.vars.latestBlack == this.vars.UNKNOWN)
        {
            // Step 1: Exit states until we reach `FOLLOWING` state (Least Common Ancestor for transition).
            TRACKING_FORWARD_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `SEARCHING`.
            SEARCHING_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for TRACKING_FORWARD
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state TRACKING_LEFT
    ////////////////////////////////////////////////////////////////////////////////
    
    private void TRACKING_LEFT_enter()
    {
        this.stateId = StateId.TRACKING_LEFT;
        
        // TRACKING_LEFT behavior
        // uml: enter / { updateProcess();\ncount = 0;\n\n// Easy left\nfireEvent("leftstickForwardLeft", followSpeed); }
        {
            // Step 1: execute action `updateProcess();\ncount = 0;\n\n// Easy left\nfireEvent("leftstickForwardLeft", followSpeed);`
            updateProcess();
            this.vars.count = 0;
            
            // Easy left
            fireEvent("leftstickForwardLeft", this.vars.followSpeed);
        } // end of behavior for TRACKING_LEFT
        
        // TRACKING_LEFT behavior
        // uml: enter / { $gil(this.vars.FOLLOWING_history = FOLLOWING_HistoryId.TRACKING_LEFT;) }
        {
            // Step 1: execute action `$gil(this.vars.FOLLOWING_history = FOLLOWING_HistoryId.TRACKING_LEFT;)`
            this.vars.FOLLOWING_history = FOLLOWING_HistoryId.TRACKING_LEFT;
        } // end of behavior for TRACKING_LEFT
    }
    
    private void TRACKING_LEFT_exit()
    {
        this.stateId = StateId.FOLLOWING;
    }
    
    private void TRACKING_LEFT_do()
    {
        boolean consume_event = false;
        
        // TRACKING_LEFT behavior
        // uml: do / { count++; }
        {
            // `do` events are not normally consumed.
            // Step 1: execute action `count++;`
            this.vars.count++;
        } // end of behavior for TRACKING_LEFT
        
        // TRACKING_LEFT behavior
        // uml: do [leftBlack || count > maxEasyTurnCount] TransitionTo(TRACKING_ROTATELEFT)
        if (this.vars.leftBlack || this.vars.count > this.vars.maxEasyTurnCount)
        {
            // Step 1: Exit states until we reach `FOLLOWING` state (Least Common Ancestor for transition).
            TRACKING_LEFT_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `TRACKING_ROTATELEFT`.
            TRACKING_ROTATELEFT_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for TRACKING_LEFT
        
        // TRACKING_LEFT behavior
        // uml: do [rightBlack] TransitionTo(FOLLOWING.<EntryPoint>(right))
        if (this.vars.rightBlack)
        {
            // Step 1: Exit states until we reach `FOLLOWING` state (Least Common Ancestor for transition).
            TRACKING_LEFT_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `FOLLOWING.<EntryPoint>(right)`.
            // FOLLOWING.<EntryPoint>(right) is a pseudo state and cannot have an `enter` trigger.
            
            // Finish transition by calling pseudo state transition function.
            FOLLOWING_EntryPoint_right__transition();
            return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
        } // end of behavior for TRACKING_LEFT
        
        // Check if event has been consumed before calling ancestor handler.
        if (!consume_event)
        {
            FOLLOWING_do();
        }
    }
    
    private void TRACKING_LEFT_middleblack()
    {
        // TRACKING_LEFT behavior
        // uml: MIDDLEBLACK TransitionTo(TRACKING_FORWARD)
        {
            // Step 1: Exit states until we reach `FOLLOWING` state (Least Common Ancestor for transition).
            TRACKING_LEFT_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `TRACKING_FORWARD`.
            TRACKING_FORWARD_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for TRACKING_LEFT
        
        // No ancestor handles this event.
    }
    
    private void TRACKING_LEFT_middlewhite()
    {
        // TRACKING_LEFT behavior
        // uml: MIDDLEWHITE / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for TRACKING_LEFT
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state TRACKING_RIGHT
    ////////////////////////////////////////////////////////////////////////////////
    
    private void TRACKING_RIGHT_enter()
    {
        this.stateId = StateId.TRACKING_RIGHT;
        
        // TRACKING_RIGHT behavior
        // uml: enter / { updateProcess();\ncount = 0;\n\n// Easy right\nfireEvent("leftstickForwardRight", followSpeed); }
        {
            // Step 1: execute action `updateProcess();\ncount = 0;\n\n// Easy right\nfireEvent("leftstickForwardRight", followSpeed);`
            updateProcess();
            this.vars.count = 0;
            
            // Easy right
            fireEvent("leftstickForwardRight", this.vars.followSpeed);
        } // end of behavior for TRACKING_RIGHT
        
        // TRACKING_RIGHT behavior
        // uml: enter / { $gil(this.vars.FOLLOWING_history = FOLLOWING_HistoryId.TRACKING_RIGHT;) }
        {
            // Step 1: execute action `$gil(this.vars.FOLLOWING_history = FOLLOWING_HistoryId.TRACKING_RIGHT;)`
            this.vars.FOLLOWING_history = FOLLOWING_HistoryId.TRACKING_RIGHT;
        } // end of behavior for TRACKING_RIGHT
    }
    
    private void TRACKING_RIGHT_exit()
    {
        this.stateId = StateId.FOLLOWING;
    }
    
    private void TRACKING_RIGHT_do()
    {
        boolean consume_event = false;
        
        // TRACKING_RIGHT behavior
        // uml: do / { count++; }
        {
            // `do` events are not normally consumed.
            // Step 1: execute action `count++;`
            this.vars.count++;
        } // end of behavior for TRACKING_RIGHT
        
        // TRACKING_RIGHT behavior
        // uml: do [leftBlack] TransitionTo(FOLLOWING.<EntryPoint>(left))
        if (this.vars.leftBlack)
        {
            // Step 1: Exit states until we reach `FOLLOWING` state (Least Common Ancestor for transition).
            TRACKING_RIGHT_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `FOLLOWING.<EntryPoint>(left)`.
            // FOLLOWING.<EntryPoint>(left) is a pseudo state and cannot have an `enter` trigger.
            
            // Finish transition by calling pseudo state transition function.
            FOLLOWING_EntryPoint_left__transition();
            return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
        } // end of behavior for TRACKING_RIGHT
        
        // TRACKING_RIGHT behavior
        // uml: do [rightBlack || count > maxEasyTurnCount] TransitionTo(TRACKING_ROTATERIGHT)
        if (this.vars.rightBlack || this.vars.count > this.vars.maxEasyTurnCount)
        {
            // Step 1: Exit states until we reach `FOLLOWING` state (Least Common Ancestor for transition).
            TRACKING_RIGHT_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `TRACKING_ROTATERIGHT`.
            TRACKING_ROTATERIGHT_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for TRACKING_RIGHT
        
        // Check if event has been consumed before calling ancestor handler.
        if (!consume_event)
        {
            FOLLOWING_do();
        }
    }
    
    private void TRACKING_RIGHT_middleblack()
    {
        // TRACKING_RIGHT behavior
        // uml: MIDDLEBLACK TransitionTo(TRACKING_FORWARD)
        {
            // Step 1: Exit states until we reach `FOLLOWING` state (Least Common Ancestor for transition).
            TRACKING_RIGHT_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `TRACKING_FORWARD`.
            TRACKING_FORWARD_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for TRACKING_RIGHT
        
        // No ancestor handles this event.
    }
    
    private void TRACKING_RIGHT_middlewhite()
    {
        // TRACKING_RIGHT behavior
        // uml: MIDDLEWHITE / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for TRACKING_RIGHT
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state TRACKING_ROTATELEFT
    ////////////////////////////////////////////////////////////////////////////////
    
    private void TRACKING_ROTATELEFT_enter()
    {
        this.stateId = StateId.TRACKING_ROTATELEFT;
        
        // TRACKING_ROTATELEFT behavior
        // uml: enter / { updateProcess();\n\n// Rotate left\nfireEvent("leftstickLeft", followSpeed); }
        {
            // Step 1: execute action `updateProcess();\n\n// Rotate left\nfireEvent("leftstickLeft", followSpeed);`
            updateProcess();
            
            // Rotate left
            fireEvent("leftstickLeft", this.vars.followSpeed);
        } // end of behavior for TRACKING_ROTATELEFT
        
        // TRACKING_ROTATELEFT behavior
        // uml: enter / { $gil(this.vars.FOLLOWING_history = FOLLOWING_HistoryId.TRACKING_ROTATELEFT;) }
        {
            // Step 1: execute action `$gil(this.vars.FOLLOWING_history = FOLLOWING_HistoryId.TRACKING_ROTATELEFT;)`
            this.vars.FOLLOWING_history = FOLLOWING_HistoryId.TRACKING_ROTATELEFT;
        } // end of behavior for TRACKING_ROTATELEFT
    }
    
    private void TRACKING_ROTATELEFT_exit()
    {
        this.stateId = StateId.FOLLOWING;
    }
    
    private void TRACKING_ROTATELEFT_do()
    {
        boolean consume_event = false;
        
        // TRACKING_ROTATELEFT behavior
        // uml: do [rightBlack && !leftBlack] TransitionTo(FOLLOWING.<EntryPoint>(right))
        if (this.vars.rightBlack && !this.vars.leftBlack)
        {
            // Step 1: Exit states until we reach `FOLLOWING` state (Least Common Ancestor for transition).
            TRACKING_ROTATELEFT_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `FOLLOWING.<EntryPoint>(right)`.
            // FOLLOWING.<EntryPoint>(right) is a pseudo state and cannot have an `enter` trigger.
            
            // Finish transition by calling pseudo state transition function.
            FOLLOWING_EntryPoint_right__transition();
            return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
        } // end of behavior for TRACKING_ROTATELEFT
        
        // Check if event has been consumed before calling ancestor handler.
        if (!consume_event)
        {
            FOLLOWING_do();
        }
    }
    
    private void TRACKING_ROTATELEFT_middleblack()
    {
        // TRACKING_ROTATELEFT behavior
        // uml: MIDDLEBLACK TransitionTo(TRACKING_FORWARD)
        {
            // Step 1: Exit states until we reach `FOLLOWING` state (Least Common Ancestor for transition).
            TRACKING_ROTATELEFT_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `TRACKING_FORWARD`.
            TRACKING_FORWARD_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for TRACKING_ROTATELEFT
        
        // No ancestor handles this event.
    }
    
    private void TRACKING_ROTATELEFT_middlewhite()
    {
        // TRACKING_ROTATELEFT behavior
        // uml: MIDDLEWHITE / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for TRACKING_ROTATELEFT
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state TRACKING_ROTATERIGHT
    ////////////////////////////////////////////////////////////////////////////////
    
    private void TRACKING_ROTATERIGHT_enter()
    {
        this.stateId = StateId.TRACKING_ROTATERIGHT;
        
        // TRACKING_ROTATERIGHT behavior
        // uml: enter / { updateProcess();\n\n// Rotate right\nfireEvent("leftstickRight", followSpeed); }
        {
            // Step 1: execute action `updateProcess();\n\n// Rotate right\nfireEvent("leftstickRight", followSpeed);`
            updateProcess();
            
            // Rotate right
            fireEvent("leftstickRight", this.vars.followSpeed);
        } // end of behavior for TRACKING_ROTATERIGHT
        
        // TRACKING_ROTATERIGHT behavior
        // uml: enter / { $gil(this.vars.FOLLOWING_history = FOLLOWING_HistoryId.TRACKING_ROTATERIGHT;) }
        {
            // Step 1: execute action `$gil(this.vars.FOLLOWING_history = FOLLOWING_HistoryId.TRACKING_ROTATERIGHT;)`
            this.vars.FOLLOWING_history = FOLLOWING_HistoryId.TRACKING_ROTATERIGHT;
        } // end of behavior for TRACKING_ROTATERIGHT
    }
    
    private void TRACKING_ROTATERIGHT_exit()
    {
        this.stateId = StateId.FOLLOWING;
    }
    
    private void TRACKING_ROTATERIGHT_do()
    {
        boolean consume_event = false;
        
        // TRACKING_ROTATERIGHT behavior
        // uml: do [!rightBlack && leftBlack] TransitionTo(FOLLOWING.<EntryPoint>(left))
        if (!this.vars.rightBlack && this.vars.leftBlack)
        {
            // Step 1: Exit states until we reach `FOLLOWING` state (Least Common Ancestor for transition).
            TRACKING_ROTATERIGHT_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `FOLLOWING.<EntryPoint>(left)`.
            // FOLLOWING.<EntryPoint>(left) is a pseudo state and cannot have an `enter` trigger.
            
            // Finish transition by calling pseudo state transition function.
            FOLLOWING_EntryPoint_left__transition();
            return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
        } // end of behavior for TRACKING_ROTATERIGHT
        
        // Check if event has been consumed before calling ancestor handler.
        if (!consume_event)
        {
            FOLLOWING_do();
        }
    }
    
    private void TRACKING_ROTATERIGHT_middleblack()
    {
        // TRACKING_ROTATERIGHT behavior
        // uml: MIDDLEBLACK TransitionTo(TRACKING_FORWARD)
        {
            // Step 1: Exit states until we reach `FOLLOWING` state (Least Common Ancestor for transition).
            TRACKING_ROTATERIGHT_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `TRACKING_FORWARD`.
            TRACKING_FORWARD_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for TRACKING_ROTATERIGHT
        
        // No ancestor handles this event.
    }
    
    private void TRACKING_ROTATERIGHT_middlewhite()
    {
        // TRACKING_ROTATERIGHT behavior
        // uml: MIDDLEWHITE / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for TRACKING_ROTATERIGHT
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state IDLE
    ////////////////////////////////////////////////////////////////////////////////
    
    private void IDLE_enter()
    {
        this.stateId = StateId.IDLE;
        
        // IDLE behavior
        // uml: enter / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for IDLE
    }
    
    private void IDLE_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void IDLE_crosspressed()
    {
        // IDLE behavior
        // uml: CROSSPRESSED / { updateProcess();\nfireEvent("startFollow"); }
        {
            // Step 1: execute action `updateProcess();\nfireEvent("startFollow");`
            updateProcess();
            fireEvent("startFollow");
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_lostcontroller()
    {
        // IDLE behavior
        // uml: (R2Stick, stopFollow, LOSTCONTROLLER) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_r2stick()
    {
        // IDLE behavior
        // uml: (R2Stick, stopFollow, LOSTCONTROLLER) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_startfollow()
    {
        // IDLE behavior
        // uml: STARTFOLLOW TransitionTo(FOLLOWING)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            IDLE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `FOLLOWING`.
            FOLLOWING_enter();
            
            // FOLLOWING.<InitialState> behavior
            // uml: TransitionTo(STARTING)
            {
                // Step 1: Exit states until we reach `FOLLOWING` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `STARTING`.
                STARTING_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for FOLLOWING.<InitialState>
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_stopfollow()
    {
        // IDLE behavior
        // uml: (R2Stick, stopFollow, LOSTCONTROLLER) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    // Thread safe.
    public static String stateIdToString(StateId id)
    {
        switch (id)
        {
            case ROOT: return "ROOT";
            case FOLLOWING: return "FOLLOWING";
            case SEARCHING: return "SEARCHING";
            case STARTING: return "STARTING";
            case TRACKING_FORWARD: return "TRACKING_FORWARD";
            case TRACKING_LEFT: return "TRACKING_LEFT";
            case TRACKING_RIGHT: return "TRACKING_RIGHT";
            case TRACKING_ROTATELEFT: return "TRACKING_ROTATELEFT";
            case TRACKING_ROTATERIGHT: return "TRACKING_ROTATERIGHT";
            case IDLE: return "IDLE";
            default: return "?";
        }
    }
    
    // Thread safe.
    public static String eventIdToString(EventId id)
    {
        switch (id)
        {
            case CROSSPRESSED: return "CROSSPRESSED";
            case DO: return "DO";
            case LEFTBLACK: return "LEFTBLACK";
            case LEFTWHITE: return "LEFTWHITE";
            case LOSTCONTROLLER: return "LOSTCONTROLLER";
            case MIDDLEBLACK: return "MIDDLEBLACK";
            case MIDDLEWHITE: return "MIDDLEWHITE";
            case R2STICK: return "R2STICK";
            case RIGHTBLACK: return "RIGHTBLACK";
            case RIGHTWHITE: return "RIGHTWHITE";
            case STARTFOLLOW: return "STARTFOLLOW";
            case STOPFOLLOW: return "STOPFOLLOW";
            default: return "?";
        }
    }

    ////////////////////////////////////////////////////////////////////////////////
    // Inserted code by csx script
    ////////////////////////////////////////////////////////////////////////////////
    
    protected String[] getAllowedEvents(StateId id) {
        return switch (id) {
            case ROOT -> new String[0];  // No events
            case FOLLOWING -> new String[]{"DO", "LEFTBLACK", "LEFTWHITE", "RIGHTBLACK", "RIGHTWHITE", "CROSSPRESSED", "LOSTCONTROLLER", "STOPFOLLOW", "R2STICK"};
            case SEARCHING -> new String[]{"MIDDLEWHITE", "MIDDLEBLACK", "DO", "R2STICK", "STOPFOLLOW", "LOSTCONTROLLER", "CROSSPRESSED", "LEFTBLACK", "LEFTWHITE", "RIGHTBLACK", "RIGHTWHITE"};
            case STARTING -> new String[]{"DO", "R2STICK", "STOPFOLLOW", "LOSTCONTROLLER", "CROSSPRESSED", "LEFTBLACK", "LEFTWHITE", "RIGHTBLACK", "RIGHTWHITE"};
            case TRACKING_FORWARD -> new String[]{"MIDDLEWHITE", "R2STICK", "STOPFOLLOW", "LOSTCONTROLLER", "CROSSPRESSED", "DO", "LEFTBLACK", "LEFTWHITE", "RIGHTBLACK", "RIGHTWHITE"};
            case TRACKING_LEFT -> new String[]{"MIDDLEWHITE", "DO", "MIDDLEBLACK", "R2STICK", "STOPFOLLOW", "LOSTCONTROLLER", "CROSSPRESSED", "LEFTBLACK", "LEFTWHITE", "RIGHTBLACK", "RIGHTWHITE"};
            case TRACKING_RIGHT -> new String[]{"MIDDLEWHITE", "DO", "MIDDLEBLACK", "R2STICK", "STOPFOLLOW", "LOSTCONTROLLER", "CROSSPRESSED", "LEFTBLACK", "LEFTWHITE", "RIGHTBLACK", "RIGHTWHITE"};
            case TRACKING_ROTATELEFT -> new String[]{"MIDDLEWHITE", "MIDDLEBLACK", "DO", "R2STICK", "STOPFOLLOW", "LOSTCONTROLLER", "CROSSPRESSED", "LEFTBLACK", "LEFTWHITE", "RIGHTBLACK", "RIGHTWHITE"};
            case TRACKING_ROTATERIGHT -> new String[]{"MIDDLEWHITE", "MIDDLEBLACK", "DO", "R2STICK", "STOPFOLLOW", "LOSTCONTROLLER", "CROSSPRESSED", "LEFTBLACK", "LEFTWHITE", "RIGHTBLACK", "RIGHTWHITE"};
            case IDLE -> new String[]{"R2STICK", "STOPFOLLOW", "LOSTCONTROLLER", "CROSSPRESSED", "STARTFOLLOW"};
            default -> new String[0];
        };
    }
    
    @Override
    protected String[] getAllEventNames()
    {
        EventId[] values = EventId.values();
        String[] names = new String[values.length];
        
        for (int i = 0; i < values.length; i++)
            names[i] = translateEventName(values[i].name());
        
        return names;
    }
    
    @Override
    protected String[] getAllStateNames()
    {
        StateId[] values = StateId.values();
        String[] names = new String[values.length];
        
        for (int i = 0; i < values.length; i++)
            names[i] = values[i].name();
        
        return names;
    }
    
    @Override
    protected String getCurrentStateString()
    {
        return stateIdToString(this.stateId);
    }
    
    @Override
    protected String[] getBaseAllowedEventsForCurrentState()
    {
        return getAllowedEvents(this.stateId);
    }
    
    // Allow sending strings to dispatchEvent(), with translate functionality
    @Override
    protected void dispatchEvent(String eventName)
    {
        String baseEventName = translateToBaseEventName(eventName);
        dispatchEvent(EventId.valueOf(baseEventName));
    }
    
    @Override
    protected void startSm()
    {
        start();
    }
    
    // See function name
    @SuppressWarnings("unused")
    private void suppressUnusedExitUpToStateHandler()
    {
        exitUpToStateHandler(StateId.ROOT);
    }
    
    ////////////////////////////////////////////////////////////////////////////////
    // End of csx-inserted code
    ////////////////////////////////////////////////////////////////////////////////
}
