// Autogenerated with StateSmith 0.19.0+ebc88ca27511ff019dec4076062d7ebc9acd4ee9.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

package tankpack;

// Generated state machine
public class Sm_Led1_Generated extends StateMachine
{
    public enum EventId
    {
        L3PRESSED,
        L3RELEASED,
        LEFTSTICKIDLE,
        LEFTSTICKUSED,
        STARTFOLLOW,
        STOPFOLLOW,
    }
    
    public final int EventIdCount = 6;
    
    public enum StateId
    {
        ROOT,
        OFF,
        OFF_INVERTED,
        ON,
        ON_INVERTED,
    }
    
    public final int StateIdCount = 5;
    
    // Used internally by state machine. Feel free to inspect, but don't modify.
    public StateId stateId;
    
    // State machine variables. Can be used for inputs, outputs, user variables...
    public class Vars
    {
        // These variables can be referenced in diagram and are automatically prefixed with "this.vars." during code generation
        // Protected variables, must be set by inheriting class
        protected Driver_Hardware dh;
        
        // Private variables, only used locally
        private int count;
    }
    
    // Variables. Can be used for inputs, outputs, user variables...
    public Vars vars = new Vars();
    
    // State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
    public Sm_Led1_Generated()
    {
    }
    
    // Starts the state machine. Must be called before dispatching events. Not thread safe.
    public void start()
    {
        ROOT_enter();
        // ROOT behavior
        // uml: TransitionTo(ROOT.<InitialState>)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
            // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
            
            // ROOT.<InitialState> behavior
            // uml: TransitionTo(OFF)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `OFF`.
                OFF_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for ROOT.<InitialState>
        } // end of behavior for ROOT
    }
    
    // Dispatches an event to the state machine. Not thread safe.
    // Note! This function assumes that the `eventId` parameter is valid.
    public void dispatchEvent(EventId eventId)
    {
        switch (this.stateId)
        {
            // STATE: Sm_Led1_Generated
            case ROOT:
                // No events handled by this state (or its ancestors).
                break;
            
            // STATE: OFF
            case OFF:
                switch (eventId)
                {
                    case STOPFOLLOW: OFF_stopfollow(); break;
                    case L3RELEASED: OFF_l3released(); break;
                    case LEFTSTICKIDLE: OFF_leftstickidle(); break;
                    case STARTFOLLOW: OFF_startfollow(); break;
                    case L3PRESSED: OFF_l3pressed(); break;
                    case LEFTSTICKUSED: OFF_leftstickused(); break;
                }
                break;
            
            // STATE: OFF_INVERTED
            case OFF_INVERTED:
                switch (eventId)
                {
                    case L3RELEASED: OFF_INVERTED_l3released(); break;
                    case LEFTSTICKIDLE: OFF_INVERTED_leftstickidle(); break;
                    case L3PRESSED: OFF_INVERTED_l3pressed(); break;
                    case LEFTSTICKUSED: OFF_INVERTED_leftstickused(); break;
                    case STOPFOLLOW: OFF_INVERTED_stopfollow(); break;
                    case STARTFOLLOW: OFF_INVERTED_startfollow(); break;
                }
                break;
            
            // STATE: ON
            case ON:
                switch (eventId)
                {
                    case STARTFOLLOW: ON_startfollow(); break;
                    case L3RELEASED: ON_l3released(); break;
                    case LEFTSTICKIDLE: ON_leftstickidle(); break;
                    case STOPFOLLOW: ON_stopfollow(); break;
                    case L3PRESSED: ON_l3pressed(); break;
                    case LEFTSTICKUSED: ON_leftstickused(); break;
                }
                break;
            
            // STATE: ON_INVERTED
            case ON_INVERTED:
                switch (eventId)
                {
                    case L3RELEASED: ON_INVERTED_l3released(); break;
                    case LEFTSTICKIDLE: ON_INVERTED_leftstickidle(); break;
                    case L3PRESSED: ON_INVERTED_l3pressed(); break;
                    case LEFTSTICKUSED: ON_INVERTED_leftstickused(); break;
                    case STARTFOLLOW: ON_INVERTED_startfollow(); break;
                    case STOPFOLLOW: ON_INVERTED_stopfollow(); break;
                }
                break;
        }
        
    }
    
    // This function is used when StateSmith doesn't know what the active leaf state is at
    // compile time due to sub states or when multiple states need to be exited.
    private void exitUpToStateHandler(StateId desiredState)
    {
        while (this.stateId != desiredState)
        {
            switch (this.stateId)
            {
                case OFF: OFF_exit(); break;
                
                case OFF_INVERTED: OFF_INVERTED_exit(); break;
                
                case ON: ON_exit(); break;
                
                case ON_INVERTED: ON_INVERTED_exit(); break;
                
                default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
            }
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state ROOT
    ////////////////////////////////////////////////////////////////////////////////
    
    private void ROOT_enter()
    {
        this.stateId = StateId.ROOT;
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state OFF
    ////////////////////////////////////////////////////////////////////////////////
    
    private void OFF_enter()
    {
        this.stateId = StateId.OFF;
        
        // OFF behavior
        // uml: enter / { updateProcess();\ncount = 0; }
        {
            // Step 1: execute action `updateProcess();\ncount = 0;`
            updateProcess();
            this.vars.count = 0;
        } // end of behavior for OFF
    }
    
    private void OFF_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void OFF_l3pressed()
    {
        // OFF behavior
        // uml: (L3Pressed, LEFTSTICKUSED) / { dh.toggleLed1();\ncount++; } TransitionTo(OFF_INVERTED)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            OFF_exit();
            
            // Step 2: Transition action: `dh.toggleLed1();\ncount++;`.
            this.vars.dh.toggleLed1();
            this.vars.count++;
            
            // Step 3: Enter/move towards transition target `OFF_INVERTED`.
            OFF_INVERTED_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for OFF
        
        // No ancestor handles this event.
    }
    
    private void OFF_l3released()
    {
        // OFF behavior
        // uml: (stopFollow, L3Released, LEFTSTICKIDLE) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for OFF
        
        // No ancestor handles this event.
    }
    
    private void OFF_leftstickidle()
    {
        // OFF behavior
        // uml: (stopFollow, L3Released, LEFTSTICKIDLE) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for OFF
        
        // No ancestor handles this event.
    }
    
    private void OFF_leftstickused()
    {
        // OFF behavior
        // uml: (L3Pressed, LEFTSTICKUSED) / { dh.toggleLed1();\ncount++; } TransitionTo(OFF_INVERTED)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            OFF_exit();
            
            // Step 2: Transition action: `dh.toggleLed1();\ncount++;`.
            this.vars.dh.toggleLed1();
            this.vars.count++;
            
            // Step 3: Enter/move towards transition target `OFF_INVERTED`.
            OFF_INVERTED_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for OFF
        
        // No ancestor handles this event.
    }
    
    private void OFF_startfollow()
    {
        // OFF behavior
        // uml: startFollow / { dh.setLed1On(); } TransitionTo(ON)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            OFF_exit();
            
            // Step 2: Transition action: `dh.setLed1On();`.
            this.vars.dh.setLed1On();
            
            // Step 3: Enter/move towards transition target `ON`.
            ON_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for OFF
        
        // No ancestor handles this event.
    }
    
    private void OFF_stopfollow()
    {
        // OFF behavior
        // uml: (stopFollow, L3Released, LEFTSTICKIDLE) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for OFF
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state OFF_INVERTED
    ////////////////////////////////////////////////////////////////////////////////
    
    private void OFF_INVERTED_enter()
    {
        this.stateId = StateId.OFF_INVERTED;
        
        // OFF_INVERTED behavior
        // uml: enter / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for OFF_INVERTED
    }
    
    private void OFF_INVERTED_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void OFF_INVERTED_l3pressed()
    {
        // OFF_INVERTED behavior
        // uml: (L3Pressed, LEFTSTICKUSED) / { updateProcess();\ncount++; }
        {
            // Step 1: execute action `updateProcess();\ncount++;`
            updateProcess();
            this.vars.count++;
        } // end of behavior for OFF_INVERTED
        
        // No ancestor handles this event.
    }
    
    private void OFF_INVERTED_l3released()
    {
        // OFF_INVERTED behavior
        // uml: 1.( L3Released, LEFTSTICKIDLE) / { count--; }
        {
            // Step 1: execute action `count--;`
            this.vars.count--;
        } // end of behavior for OFF_INVERTED
        
        // OFF_INVERTED behavior
        // uml: 2.( L3Released, LEFTSTICKIDLE) [count > 0] / { updateProcess(); }
        if (this.vars.count > 0)
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for OFF_INVERTED
        
        // OFF_INVERTED behavior
        // uml: (L3Released, LEFTSTICKIDLE) [count == 0] / { dh.toggleLed1(); } TransitionTo(OFF)
        if (this.vars.count == 0)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            OFF_INVERTED_exit();
            
            // Step 2: Transition action: `dh.toggleLed1();`.
            this.vars.dh.toggleLed1();
            
            // Step 3: Enter/move towards transition target `OFF`.
            OFF_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for OFF_INVERTED
        
        // No ancestor handles this event.
    }
    
    private void OFF_INVERTED_leftstickidle()
    {
        // OFF_INVERTED behavior
        // uml: 1.( L3Released, LEFTSTICKIDLE) / { count--; }
        {
            // Step 1: execute action `count--;`
            this.vars.count--;
        } // end of behavior for OFF_INVERTED
        
        // OFF_INVERTED behavior
        // uml: 2.( L3Released, LEFTSTICKIDLE) [count > 0] / { updateProcess(); }
        if (this.vars.count > 0)
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for OFF_INVERTED
        
        // OFF_INVERTED behavior
        // uml: (L3Released, LEFTSTICKIDLE) [count == 0] / { dh.toggleLed1(); } TransitionTo(OFF)
        if (this.vars.count == 0)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            OFF_INVERTED_exit();
            
            // Step 2: Transition action: `dh.toggleLed1();`.
            this.vars.dh.toggleLed1();
            
            // Step 3: Enter/move towards transition target `OFF`.
            OFF_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for OFF_INVERTED
        
        // No ancestor handles this event.
    }
    
    private void OFF_INVERTED_leftstickused()
    {
        // OFF_INVERTED behavior
        // uml: (L3Pressed, LEFTSTICKUSED) / { updateProcess();\ncount++; }
        {
            // Step 1: execute action `updateProcess();\ncount++;`
            updateProcess();
            this.vars.count++;
        } // end of behavior for OFF_INVERTED
        
        // No ancestor handles this event.
    }
    
    private void OFF_INVERTED_startfollow()
    {
        // OFF_INVERTED behavior
        // uml: startFollow / { dh.setLed1Off(); } TransitionTo(ON_INVERTED)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            OFF_INVERTED_exit();
            
            // Step 2: Transition action: `dh.setLed1Off();`.
            this.vars.dh.setLed1Off();
            
            // Step 3: Enter/move towards transition target `ON_INVERTED`.
            ON_INVERTED_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for OFF_INVERTED
        
        // No ancestor handles this event.
    }
    
    private void OFF_INVERTED_stopfollow()
    {
        // OFF_INVERTED behavior
        // uml: stopFollow / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for OFF_INVERTED
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state ON
    ////////////////////////////////////////////////////////////////////////////////
    
    private void ON_enter()
    {
        this.stateId = StateId.ON;
        
        // ON behavior
        // uml: enter / { updateProcess();\ncount = 0; }
        {
            // Step 1: execute action `updateProcess();\ncount = 0;`
            updateProcess();
            this.vars.count = 0;
        } // end of behavior for ON
    }
    
    private void ON_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void ON_l3pressed()
    {
        // ON behavior
        // uml: (L3Pressed, LEFTSTICKUSED) / { dh.toggleLed1();\ncount++; } TransitionTo(ON_INVERTED)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            ON_exit();
            
            // Step 2: Transition action: `dh.toggleLed1();\ncount++;`.
            this.vars.dh.toggleLed1();
            this.vars.count++;
            
            // Step 3: Enter/move towards transition target `ON_INVERTED`.
            ON_INVERTED_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ON
        
        // No ancestor handles this event.
    }
    
    private void ON_l3released()
    {
        // ON behavior
        // uml: (startFollow, L3Released, LEFTSTICKIDLE) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for ON
        
        // No ancestor handles this event.
    }
    
    private void ON_leftstickidle()
    {
        // ON behavior
        // uml: (startFollow, L3Released, LEFTSTICKIDLE) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for ON
        
        // No ancestor handles this event.
    }
    
    private void ON_leftstickused()
    {
        // ON behavior
        // uml: (L3Pressed, LEFTSTICKUSED) / { dh.toggleLed1();\ncount++; } TransitionTo(ON_INVERTED)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            ON_exit();
            
            // Step 2: Transition action: `dh.toggleLed1();\ncount++;`.
            this.vars.dh.toggleLed1();
            this.vars.count++;
            
            // Step 3: Enter/move towards transition target `ON_INVERTED`.
            ON_INVERTED_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ON
        
        // No ancestor handles this event.
    }
    
    private void ON_startfollow()
    {
        // ON behavior
        // uml: (startFollow, L3Released, LEFTSTICKIDLE) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for ON
        
        // No ancestor handles this event.
    }
    
    private void ON_stopfollow()
    {
        // ON behavior
        // uml: stopFollow / { dh.setLed1Off(); } TransitionTo(OFF)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            ON_exit();
            
            // Step 2: Transition action: `dh.setLed1Off();`.
            this.vars.dh.setLed1Off();
            
            // Step 3: Enter/move towards transition target `OFF`.
            OFF_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ON
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state ON_INVERTED
    ////////////////////////////////////////////////////////////////////////////////
    
    private void ON_INVERTED_enter()
    {
        this.stateId = StateId.ON_INVERTED;
        
        // ON_INVERTED behavior
        // uml: enter / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for ON_INVERTED
    }
    
    private void ON_INVERTED_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void ON_INVERTED_l3pressed()
    {
        // ON_INVERTED behavior
        // uml: (L3Pressed, LEFTSTICKUSED) / { updateProcess();\ncount++; }
        {
            // Step 1: execute action `updateProcess();\ncount++;`
            updateProcess();
            this.vars.count++;
        } // end of behavior for ON_INVERTED
        
        // No ancestor handles this event.
    }
    
    private void ON_INVERTED_l3released()
    {
        // ON_INVERTED behavior
        // uml: 1.( L3Released, LEFTSTICKIDLE) / { count--; }
        {
            // Step 1: execute action `count--;`
            this.vars.count--;
        } // end of behavior for ON_INVERTED
        
        // ON_INVERTED behavior
        // uml: 2.( L3Released, LEFTSTICKIDLE) [count > 0] / { updateProcess(); }
        if (this.vars.count > 0)
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for ON_INVERTED
        
        // ON_INVERTED behavior
        // uml: (L3Released, LEFTSTICKIDLE) [count == 0] / { dh.toggleLed1(); } TransitionTo(ON)
        if (this.vars.count == 0)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            ON_INVERTED_exit();
            
            // Step 2: Transition action: `dh.toggleLed1();`.
            this.vars.dh.toggleLed1();
            
            // Step 3: Enter/move towards transition target `ON`.
            ON_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ON_INVERTED
        
        // No ancestor handles this event.
    }
    
    private void ON_INVERTED_leftstickidle()
    {
        // ON_INVERTED behavior
        // uml: 1.( L3Released, LEFTSTICKIDLE) / { count--; }
        {
            // Step 1: execute action `count--;`
            this.vars.count--;
        } // end of behavior for ON_INVERTED
        
        // ON_INVERTED behavior
        // uml: 2.( L3Released, LEFTSTICKIDLE) [count > 0] / { updateProcess(); }
        if (this.vars.count > 0)
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for ON_INVERTED
        
        // ON_INVERTED behavior
        // uml: (L3Released, LEFTSTICKIDLE) [count == 0] / { dh.toggleLed1(); } TransitionTo(ON)
        if (this.vars.count == 0)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            ON_INVERTED_exit();
            
            // Step 2: Transition action: `dh.toggleLed1();`.
            this.vars.dh.toggleLed1();
            
            // Step 3: Enter/move towards transition target `ON`.
            ON_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ON_INVERTED
        
        // No ancestor handles this event.
    }
    
    private void ON_INVERTED_leftstickused()
    {
        // ON_INVERTED behavior
        // uml: (L3Pressed, LEFTSTICKUSED) / { updateProcess();\ncount++; }
        {
            // Step 1: execute action `updateProcess();\ncount++;`
            updateProcess();
            this.vars.count++;
        } // end of behavior for ON_INVERTED
        
        // No ancestor handles this event.
    }
    
    private void ON_INVERTED_startfollow()
    {
        // ON_INVERTED behavior
        // uml: startFollow / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for ON_INVERTED
        
        // No ancestor handles this event.
    }
    
    private void ON_INVERTED_stopfollow()
    {
        // ON_INVERTED behavior
        // uml: stopFollow / { dh.setLed1On(); } TransitionTo(OFF_INVERTED)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            ON_INVERTED_exit();
            
            // Step 2: Transition action: `dh.setLed1On();`.
            this.vars.dh.setLed1On();
            
            // Step 3: Enter/move towards transition target `OFF_INVERTED`.
            OFF_INVERTED_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ON_INVERTED
        
        // No ancestor handles this event.
    }
    
    // Thread safe.
    public static String stateIdToString(StateId id)
    {
        switch (id)
        {
            case ROOT: return "ROOT";
            case OFF: return "OFF";
            case OFF_INVERTED: return "OFF_INVERTED";
            case ON: return "ON";
            case ON_INVERTED: return "ON_INVERTED";
            default: return "?";
        }
    }
    
    // Thread safe.
    public static String eventIdToString(EventId id)
    {
        switch (id)
        {
            case L3PRESSED: return "L3PRESSED";
            case L3RELEASED: return "L3RELEASED";
            case LEFTSTICKIDLE: return "LEFTSTICKIDLE";
            case LEFTSTICKUSED: return "LEFTSTICKUSED";
            case STARTFOLLOW: return "STARTFOLLOW";
            case STOPFOLLOW: return "STOPFOLLOW";
            default: return "?";
        }
    }

    ////////////////////////////////////////////////////////////////////////////////
    // Inserted code by csx script
    ////////////////////////////////////////////////////////////////////////////////
    
    protected String[] getAllowedEvents(StateId id) {
        return switch (id) {
            case ROOT -> new String[0];  // No events
            case OFF -> new String[]{"STOPFOLLOW", "L3RELEASED", "LEFTSTICKIDLE", "STARTFOLLOW", "L3PRESSED", "LEFTSTICKUSED"};
            case OFF_INVERTED -> new String[]{"L3RELEASED", "LEFTSTICKIDLE", "L3PRESSED", "LEFTSTICKUSED", "STOPFOLLOW", "STARTFOLLOW"};
            case ON -> new String[]{"STARTFOLLOW", "L3RELEASED", "LEFTSTICKIDLE", "STOPFOLLOW", "L3PRESSED", "LEFTSTICKUSED"};
            case ON_INVERTED -> new String[]{"L3RELEASED", "LEFTSTICKIDLE", "L3PRESSED", "LEFTSTICKUSED", "STARTFOLLOW", "STOPFOLLOW"};
            default -> new String[0];
        };
    }
    
    @Override
    protected String[] getAllEventNames()
    {
        EventId[] values = EventId.values();
        String[] names = new String[values.length];
        
        for (int i = 0; i < values.length; i++)
            names[i] = translateEventName(values[i].name());
        
        return names;
    }
    
    @Override
    protected String[] getAllStateNames()
    {
        StateId[] values = StateId.values();
        String[] names = new String[values.length];
        
        for (int i = 0; i < values.length; i++)
            names[i] = values[i].name();
        
        return names;
    }
    
    @Override
    protected String getCurrentStateString()
    {
        return stateIdToString(this.stateId);
    }
    
    @Override
    protected String[] getBaseAllowedEventsForCurrentState()
    {
        return getAllowedEvents(this.stateId);
    }
    
    // Allow sending strings to dispatchEvent(), with translate functionality
    @Override
    protected void dispatchEvent(String eventName)
    {
        String baseEventName = translateToBaseEventName(eventName);
        dispatchEvent(EventId.valueOf(baseEventName));
    }
    
    @Override
    protected void startSm()
    {
        start();
    }
    
    // See function name
    @SuppressWarnings("unused")
    private void suppressUnusedExitUpToStateHandler()
    {
        exitUpToStateHandler(StateId.ROOT);
    }
    
    ////////////////////////////////////////////////////////////////////////////////
    // End of csx-inserted code
    ////////////////////////////////////////////////////////////////////////////////
}
