// Autogenerated with StateSmith 0.19.0-alpha-1+3da98b58a6e506bc06d88cba576dcc4df8809849.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

package tankpack;

// Generated state machine
public class Sm_Motor_Generated extends StateMachine
{
//  ////////////////////////////////////////////////////////////////////////////////
    // Class code
    ////////////////////////////////////////////////////////////////////////////////
    
    // Must be overridden by inheriting class
    protected void adjustSpeed()
    {
    }

    ////////////////////////////////////////////////////////////////////////////////
    // End of class code
    ////////////////////////////////////////////////////////////////////////////////


    public enum EventId
    {
        DO, // The `do` event is special. State event handlers do not consume this event (ancestors all get it too) unless a transition occurs.
        SETSPEEDEVENT,
    }
    
    public final int EventIdCount = 2;
    
    public enum StateId
    {
        ROOT,
        IDLE,
        MOVING,
        RAMPING,
    }
    
    public final int StateIdCount = 4;
    
    // Used internally by state machine. Feel free to inspect, but don't modify.
    public StateId stateId;
    
    // State machine variables. Can be used for inputs, outputs, user variables...
    public class Vars
    {
        // These variables can be referenced in diagram and are automatically prefixed with "this.vars." during code generation
        // Protected variables, must be set by inheriting class
        protected Driver_Hardware dh;
        protected int currentSpeed;
        protected int targetSpeed;
        
        // Private variables, only used locally
    }
    
    // Variables. Can be used for inputs, outputs, user variables...
    public Vars vars = new Vars();
    
    // State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
    public Sm_Motor_Generated()
    {
    }
    
    // Starts the state machine. Must be called before dispatching events. Not thread safe.
    public void start()
    {
        ROOT_enter();
        // ROOT behavior
        // uml: TransitionTo(ROOT.<InitialState>)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
            // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
            
            // ROOT.<InitialState> behavior
            // uml: TransitionTo(IDLE)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `IDLE`.
                IDLE_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for ROOT.<InitialState>
        } // end of behavior for ROOT
    }
    
    // Dispatches an event to the state machine. Not thread safe.
    // Note! This function assumes that the `eventId` parameter is valid.
    public void dispatchEvent(EventId eventId)
    {
        switch (this.stateId)
        {
            // STATE: Sm_Motor_Generated
            case ROOT:
                // No events handled by this state (or its ancestors).
                break;
            
            // STATE: IDLE
            case IDLE:
                switch (eventId)
                {
                    case SETSPEEDEVENT: IDLE_setspeedevent(); break;
                }
                break;
            
            // STATE: MOVING
            case MOVING:
                switch (eventId)
                {
                    case SETSPEEDEVENT: MOVING_setspeedevent(); break;
                }
                break;
            
            // STATE: RAMPING
            case RAMPING:
                switch (eventId)
                {
                    case DO: RAMPING_do(); break;
                    case SETSPEEDEVENT: RAMPING_setspeedevent(); break;
                }
                break;
        }
        
    }
    
    // This function is used when StateSmith doesn't know what the active leaf state is at
    // compile time due to sub states or when multiple states need to be exited.
    private void exitUpToStateHandler(StateId desiredState)
    {
        while (this.stateId != desiredState)
        {
            switch (this.stateId)
            {
                case IDLE: IDLE_exit(); break;
                
                case MOVING: MOVING_exit(); break;
                
                case RAMPING: RAMPING_exit(); break;
                
                default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
            }
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state ROOT
    ////////////////////////////////////////////////////////////////////////////////
    
    private void ROOT_enter()
    {
        this.stateId = StateId.ROOT;
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state IDLE
    ////////////////////////////////////////////////////////////////////////////////
    
    private void IDLE_enter()
    {
        this.stateId = StateId.IDLE;
        
        // IDLE behavior
        // uml: enter / { updateProcess();\ncurrentSpeed = 0;\ntargetSpeed = 0; }
        {
            // Step 1: execute action `updateProcess();\ncurrentSpeed = 0;\ntargetSpeed = 0;`
            updateProcess();
            this.vars.currentSpeed = 0;
            this.vars.targetSpeed = 0;
        } // end of behavior for IDLE
    }
    
    private void IDLE_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void IDLE_setspeedevent()
    {
        // IDLE behavior
        // uml: setSpeedEvent [targetSpeed == 0] / { updateProcess(); }
        if (this.vars.targetSpeed == 0)
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for IDLE
        
        // IDLE behavior
        // uml: setSpeedEvent [targetSpeed != 0] TransitionTo(RAMPING)
        if (this.vars.targetSpeed != 0)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            IDLE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `RAMPING`.
            RAMPING_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state MOVING
    ////////////////////////////////////////////////////////////////////////////////
    
    private void MOVING_enter()
    {
        this.stateId = StateId.MOVING;
        
        // MOVING behavior
        // uml: enter / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for MOVING
    }
    
    private void MOVING_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void MOVING_setspeedevent()
    {
        // MOVING behavior
        // uml: setSpeedEvent [currentSpeed == targetSpeed] / { updateProcess(); }
        if (this.vars.currentSpeed == this.vars.targetSpeed)
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for MOVING
        
        // MOVING behavior
        // uml: setSpeedEvent [currentSpeed != targetSpeed] TransitionTo(RAMPING)
        if (this.vars.currentSpeed != this.vars.targetSpeed)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            MOVING_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `RAMPING`.
            RAMPING_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for MOVING
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state RAMPING
    ////////////////////////////////////////////////////////////////////////////////
    
    private void RAMPING_enter()
    {
        this.stateId = StateId.RAMPING;
        
        // RAMPING behavior
        // uml: enter / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for RAMPING
    }
    
    private void RAMPING_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void RAMPING_do()
    {
        // RAMPING behavior
        // uml: 1. do / { adjustSpeed(); }
        {
            // Step 1: execute action `adjustSpeed();`
            adjustSpeed();
        } // end of behavior for RAMPING
        
        // RAMPING behavior
        // uml: do [currentSpeed == targetSpeed && currentSpeed == 0] TransitionTo(IDLE)
        if (this.vars.currentSpeed == this.vars.targetSpeed && this.vars.currentSpeed == 0)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            RAMPING_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `IDLE`.
            IDLE_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for RAMPING
        
        // RAMPING behavior
        // uml: do [currentSpeed == targetSpeed && currentSpeed != 0] TransitionTo(MOVING)
        if (this.vars.currentSpeed == this.vars.targetSpeed && this.vars.currentSpeed != 0)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            RAMPING_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `MOVING`.
            MOVING_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for RAMPING
        
        // No ancestor handles this event.
    }
    
    private void RAMPING_setspeedevent()
    {
        // RAMPING behavior
        // uml: setSpeedEvent / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for RAMPING
        
        // No ancestor handles this event.
    }
    
    // Thread safe.
    public static String stateIdToString(StateId id)
    {
        switch (id)
        {
            case ROOT: return "ROOT";
            case IDLE: return "IDLE";
            case MOVING: return "MOVING";
            case RAMPING: return "RAMPING";
            default: return "?";
        }
    }
    
    // Thread safe.
    public static String eventIdToString(EventId id)
    {
        switch (id)
        {
            case DO: return "DO";
            case SETSPEEDEVENT: return "SETSPEEDEVENT";
            default: return "?";
        }
    }

    ////////////////////////////////////////////////////////////////////////////////
    // Inserted code by csx script
    ////////////////////////////////////////////////////////////////////////////////
    
    protected String[] getAllowedEvents(StateId id) {
        return switch (id) {
            case ROOT -> new String[0];  // No events
            case IDLE -> new String[]{"SETSPEEDEVENT"};
            case MOVING -> new String[]{"SETSPEEDEVENT"};
            case RAMPING -> new String[]{"DO", "SETSPEEDEVENT"};
            default -> new String[0];
        };
    }
    
    @Override
    protected String[] getAllEventNames()
    {
        EventId[] values = EventId.values();
        String[] names = new String[values.length];
        
        for (int i = 0; i < values.length; i++)
            names[i] = translateEventName(values[i].name());
        
        return names;
    }
    
    @Override
    protected String[] getAllStateNames()
    {
        StateId[] values = StateId.values();
        String[] names = new String[values.length];
        
        for (int i = 0; i < values.length; i++)
            names[i] = values[i].name();
        
        return names;
    }
    
    @Override
    protected String getCurrentStateString()
    {
        return stateIdToString(this.stateId);
    }
    
    @Override
    protected String[] getBaseAllowedEventsForCurrentState()
    {
        return getAllowedEvents(this.stateId);
    }
    
    // Allow sending strings to dispatchEvent(), with translate functionality
    @Override
    protected void dispatchEvent(String eventName)
    {
        String baseEventName = translateToBaseEventName(eventName);
        dispatchEvent(EventId.valueOf(baseEventName));
    }
    
    @Override
    protected void startSm()
    {
        start();
    }
    
    // See function name
    @SuppressWarnings("unused")
    private void suppressUnusedExitUpToStateHandler()
    {
        exitUpToStateHandler(StateId.ROOT);
    }
    
    ////////////////////////////////////////////////////////////////////////////////
    // End of csx-inserted code
    ////////////////////////////////////////////////////////////////////////////////
}
