// Autogenerated with StateSmith 0.19.0+ebc88ca27511ff019dec4076062d7ebc9acd4ee9.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

package tankpack;

import tankpack.enums.Direction;
import tankpack.enums.PsComponent;


// Generated state machine
public class Sm_PsJoystick_Generated extends StateMachine
{
//  ////////////////////////////////////////////////////////////////////////////////
    // Class code
    ////////////////////////////////////////////////////////////////////////////////
    
    // Must be overridden by inheriting class
    protected void calculateAndFireStickEvent()
    {
    }

    ////////////////////////////////////////////////////////////////////////////////
    // End of class code
    ////////////////////////////////////////////////////////////////////////////////


    public enum EventId
    {
        DO, // The `do` event is special. State event handlers do not consume this event (ancestors all get it too) unless a transition occurs.
        FOUNDCONTROLLER,
        LOSTCONTROLLER,
        STARTFOLLOW,
        STOPFOLLOW,
    }
    
    public final int EventIdCount = 5;
    
    public enum StateId
    {
        ROOT,
        IDLE,
        NOCONNECTION,
        USED,
    }
    
    public final int StateIdCount = 4;
    
    // Used internally by state machine. Feel free to inspect, but don't modify.
    public StateId stateId;
    
    // State machine variables. Can be used for inputs, outputs, user variables...
    public class Vars
    {
        // These variables can be referenced in diagram and are automatically prefixed with "this.vars." during code generation
        // Protected variables, must be set by inheriting class
        protected Driver_PsController dpc;
        protected PsComponent stickX; // Stick to read
        protected PsComponent stickY; // Stick to read
        protected String stickIdleEvent; // Event to fire when stick is in the centre / not used
        protected String stickUsedEvent; // Event to fire when stick is in use
        
        // Shared variables with inheriting class
        protected int percentage;
        protected Direction direction;
        protected boolean enabled = true;
        
        // Private variables, only used locally
        private final Direction CENTER = Direction.Center;
        private boolean stickUsed;
    }
    
    // Variables. Can be used for inputs, outputs, user variables...
    public Vars vars = new Vars();
    
    // State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
    public Sm_PsJoystick_Generated()
    {
    }
    
    // Starts the state machine. Must be called before dispatching events. Not thread safe.
    public void start()
    {
        ROOT_enter();
        // ROOT behavior
        // uml: TransitionTo(ROOT.<InitialState>)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
            // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
            
            // ROOT.<InitialState> behavior
            // uml: TransitionTo(NOCONNECTION)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `NOCONNECTION`.
                NOCONNECTION_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for ROOT.<InitialState>
        } // end of behavior for ROOT
    }
    
    // Dispatches an event to the state machine. Not thread safe.
    // Note! This function assumes that the `eventId` parameter is valid.
    public void dispatchEvent(EventId eventId)
    {
        switch (this.stateId)
        {
            // STATE: Sm_PsJoystick_Generated
            case ROOT:
                // No events handled by this state (or its ancestors).
                break;
            
            // STATE: IDLE
            case IDLE:
                switch (eventId)
                {
                    case DO: IDLE_do(); break;
                    case STOPFOLLOW: IDLE_stopfollow(); break;
                    case STARTFOLLOW: IDLE_startfollow(); break;
                    case LOSTCONTROLLER: IDLE_lostcontroller(); break;
                }
                break;
            
            // STATE: NOCONNECTION
            case NOCONNECTION:
                switch (eventId)
                {
                    case STOPFOLLOW: NOCONNECTION_stopfollow(); break;
                    case STARTFOLLOW: NOCONNECTION_startfollow(); break;
                    case FOUNDCONTROLLER: NOCONNECTION_foundcontroller(); break;
                }
                break;
            
            // STATE: USED
            case USED:
                switch (eventId)
                {
                    case DO: USED_do(); break;
                    case STARTFOLLOW: USED_startfollow(); break;
                    case STOPFOLLOW: USED_stopfollow(); break;
                    case LOSTCONTROLLER: USED_lostcontroller(); break;
                }
                break;
        }
        
    }
    
    // This function is used when StateSmith doesn't know what the active leaf state is at
    // compile time due to sub states or when multiple states need to be exited.
    private void exitUpToStateHandler(StateId desiredState)
    {
        while (this.stateId != desiredState)
        {
            switch (this.stateId)
            {
                case IDLE: IDLE_exit(); break;
                
                case NOCONNECTION: NOCONNECTION_exit(); break;
                
                case USED: USED_exit(); break;
                
                default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
            }
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state ROOT
    ////////////////////////////////////////////////////////////////////////////////
    
    private void ROOT_enter()
    {
        this.stateId = StateId.ROOT;
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state IDLE
    ////////////////////////////////////////////////////////////////////////////////
    
    private void IDLE_enter()
    {
        this.stateId = StateId.IDLE;
        
        // IDLE behavior
        // uml: enter / { updateProcess();\npercentage = 0; // idle, so reset percentage\ndirection = CENTER; // idle, so set to center }
        {
            // Step 1: execute action `updateProcess();\npercentage = 0; // idle, so reset percentage\ndirection = CENTER; // idle, so set to center`
            updateProcess();
            this.vars.percentage = 0; // idle, so reset percentage
            this.vars.direction = this.vars.CENTER; // idle, so set to center<EOF>
        } // end of behavior for IDLE
    }
    
    private void IDLE_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void IDLE_do()
    {
        // IDLE behavior
        // uml: do / { stickUsed = (dpc.isUsed(stickX) || dpc.isUsed(stickY)); }
        {
            // Step 1: execute action `stickUsed = (dpc.isUsed(stickX) || dpc.isUsed(stickY));`
            this.vars.stickUsed = (this.vars.dpc.isUsed(this.vars.stickX) || this.vars.dpc.isUsed(this.vars.stickY));
        } // end of behavior for IDLE
        
        // IDLE behavior
        // uml: do [stickUsed && enabled] TransitionTo(USED)
        if (this.vars.stickUsed && this.vars.enabled)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            IDLE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `USED`.
            USED_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_lostcontroller()
    {
        // IDLE behavior
        // uml: lostController TransitionTo(NOCONNECTION)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            IDLE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `NOCONNECTION`.
            NOCONNECTION_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_startfollow()
    {
        // IDLE behavior
        // uml: (stopFollow, startFollow) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_stopfollow()
    {
        // IDLE behavior
        // uml: (stopFollow, startFollow) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state NOCONNECTION
    ////////////////////////////////////////////////////////////////////////////////
    
    private void NOCONNECTION_enter()
    {
        this.stateId = StateId.NOCONNECTION;
        
        // NOCONNECTION behavior
        // uml: enter / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for NOCONNECTION
    }
    
    private void NOCONNECTION_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void NOCONNECTION_foundcontroller()
    {
        // NOCONNECTION behavior
        // uml: foundController TransitionTo(IDLE)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            NOCONNECTION_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `IDLE`.
            IDLE_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for NOCONNECTION
        
        // No ancestor handles this event.
    }
    
    private void NOCONNECTION_startfollow()
    {
        // NOCONNECTION behavior
        // uml: (stopFollow, startFollow) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for NOCONNECTION
        
        // No ancestor handles this event.
    }
    
    private void NOCONNECTION_stopfollow()
    {
        // NOCONNECTION behavior
        // uml: (stopFollow, startFollow) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for NOCONNECTION
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state USED
    ////////////////////////////////////////////////////////////////////////////////
    
    private void USED_enter()
    {
        this.stateId = StateId.USED;
        
        // USED behavior
        // uml: enter / { updateProcess();\nfireEvent(stickUsedEvent);\ncalculateAndFireStickEvent(); }
        {
            // Step 1: execute action `updateProcess();\nfireEvent(stickUsedEvent);\ncalculateAndFireStickEvent();`
            updateProcess();
            fireEvent(this.vars.stickUsedEvent);
            calculateAndFireStickEvent();
        } // end of behavior for USED
    }
    
    private void USED_exit()
    {
        // USED behavior
        // uml: exit / { fireEvent(stickIdleEvent); }
        {
            // Step 1: execute action `fireEvent(stickIdleEvent);`
            fireEvent(this.vars.stickIdleEvent);
        } // end of behavior for USED
        
        this.stateId = StateId.ROOT;
    }
    
    private void USED_do()
    {
        // USED behavior
        // uml: 1. do / { stickUsed = (dpc.isUsed(stickX) || dpc.isUsed(stickY)); }
        {
            // Step 1: execute action `stickUsed = (dpc.isUsed(stickX) || dpc.isUsed(stickY));`
            this.vars.stickUsed = (this.vars.dpc.isUsed(this.vars.stickX) || this.vars.dpc.isUsed(this.vars.stickY));
        } // end of behavior for USED
        
        // USED behavior
        // uml: 2. do [stickUsed] / { calculateAndFireStickEvent(); }
        if (this.vars.stickUsed)
        {
            // Step 1: execute action `calculateAndFireStickEvent();`
            calculateAndFireStickEvent();
        } // end of behavior for USED
        
        // USED behavior
        // uml: DO [!stickUsed] TransitionTo(IDLE)
        if (!this.vars.stickUsed)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            USED_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `IDLE`.
            IDLE_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for USED
        
        // No ancestor handles this event.
    }
    
    private void USED_lostcontroller()
    {
        // USED behavior
        // uml: lostController TransitionTo(NOCONNECTION)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            USED_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `NOCONNECTION`.
            NOCONNECTION_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for USED
        
        // No ancestor handles this event.
    }
    
    private void USED_startfollow()
    {
        // USED behavior
        // uml: (startFollow, stopFollow) [enabled] / { updateProcess(); }
        if (this.vars.enabled)
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for USED
        
        // USED behavior
        // uml: startFollow [!enabled] TransitionTo(IDLE)
        if (!this.vars.enabled)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            USED_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `IDLE`.
            IDLE_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for USED
        
        // No ancestor handles this event.
    }
    
    private void USED_stopfollow()
    {
        // USED behavior
        // uml: (startFollow, stopFollow) [enabled] / { updateProcess(); }
        if (this.vars.enabled)
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for USED
        
        // No ancestor handles this event.
    }
    
    // Thread safe.
    public static String stateIdToString(StateId id)
    {
        switch (id)
        {
            case ROOT: return "ROOT";
            case IDLE: return "IDLE";
            case NOCONNECTION: return "NOCONNECTION";
            case USED: return "USED";
            default: return "?";
        }
    }
    
    // Thread safe.
    public static String eventIdToString(EventId id)
    {
        switch (id)
        {
            case DO: return "DO";
            case FOUNDCONTROLLER: return "FOUNDCONTROLLER";
            case LOSTCONTROLLER: return "LOSTCONTROLLER";
            case STARTFOLLOW: return "STARTFOLLOW";
            case STOPFOLLOW: return "STOPFOLLOW";
            default: return "?";
        }
    }

    ////////////////////////////////////////////////////////////////////////////////
    // Inserted code by csx script
    ////////////////////////////////////////////////////////////////////////////////
    
    protected String[] getAllowedEvents(StateId id) {
        return switch (id) {
            case ROOT -> new String[0];  // No events
            case IDLE -> new String[]{"DO", "STOPFOLLOW", "STARTFOLLOW", "LOSTCONTROLLER"};
            case NOCONNECTION -> new String[]{"STOPFOLLOW", "STARTFOLLOW", "FOUNDCONTROLLER"};
            case USED -> new String[]{"DO", "STARTFOLLOW", "STOPFOLLOW", "LOSTCONTROLLER"};
            default -> new String[0];
        };
    }
    
    @Override
    protected String[] getAllEventNames()
    {
        EventId[] values = EventId.values();
        String[] names = new String[values.length];
        
        for (int i = 0; i < values.length; i++)
            names[i] = translateEventName(values[i].name());
        
        return names;
    }
    
    @Override
    protected String[] getAllStateNames()
    {
        StateId[] values = StateId.values();
        String[] names = new String[values.length];
        
        for (int i = 0; i < values.length; i++)
            names[i] = values[i].name();
        
        return names;
    }
    
    @Override
    protected String getCurrentStateString()
    {
        return stateIdToString(this.stateId);
    }
    
    @Override
    protected String[] getBaseAllowedEventsForCurrentState()
    {
        return getAllowedEvents(this.stateId);
    }
    
    // Allow sending strings to dispatchEvent(), with translate functionality
    @Override
    protected void dispatchEvent(String eventName)
    {
        String baseEventName = translateToBaseEventName(eventName);
        dispatchEvent(EventId.valueOf(baseEventName));
    }
    
    @Override
    protected void startSm()
    {
        start();
    }
    
    // See function name
    @SuppressWarnings("unused")
    private void suppressUnusedExitUpToStateHandler()
    {
        exitUpToStateHandler(StateId.ROOT);
    }
    
    ////////////////////////////////////////////////////////////////////////////////
    // End of csx-inserted code
    ////////////////////////////////////////////////////////////////////////////////
}
