// Autogenerated with StateSmith 0.19.0-alpha-1+3da98b58a6e506bc06d88cba576dcc4df8809849.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

package tankpack;

// Generated state machine
public class Sm_PsController_Generated extends StateMachine
{
    public enum EventId
    {
        DO, // The `do` event is special. State event handlers do not consume this event (ancestors all get it too) unless a transition occurs.
    }
    
    public final int EventIdCount = 1;
    
    public enum StateId
    {
        ROOT,
        CONNECTED,
        DISCONNECTED,
    }
    
    public final int StateIdCount = 3;
    
    // Used internally by state machine. Feel free to inspect, but don't modify.
    public StateId stateId;
    
    // State machine variables. Can be used for inputs, outputs, user variables...
    public class Vars
    {
        // These variables can be referenced in diagram and are automatically prefixed with "this.vars." during code generation
        // Protected variables, must be set by inheriting class
        protected Driver_PsController dpc;
        
        // Private variables, only used locally
        private boolean controllerAvailable;
        private long timer;
    }
    
    // Variables. Can be used for inputs, outputs, user variables...
    public Vars vars = new Vars();
    
    // State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
    public Sm_PsController_Generated()
    {
    }
    
    // Starts the state machine. Must be called before dispatching events. Not thread safe.
    public void start()
    {
        ROOT_enter();
        // ROOT behavior
        // uml: TransitionTo(ROOT.<InitialState>)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
            // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
            
            // ROOT.<InitialState> behavior
            // uml: TransitionTo(DISCONNECTED)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `DISCONNECTED`.
                DISCONNECTED_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for ROOT.<InitialState>
        } // end of behavior for ROOT
    }
    
    // Dispatches an event to the state machine. Not thread safe.
    // Note! This function assumes that the `eventId` parameter is valid.
    public void dispatchEvent(EventId eventId)
    {
        
        switch (this.stateId)
        {
            // STATE: Sm_PsController_Generated
            case ROOT:
                // state and ancestors have no handler for `do` event.
                break;
            
            // STATE: CONNECTED
            case CONNECTED:
                CONNECTED_do(); 
                break;
            
            // STATE: DISCONNECTED
            case DISCONNECTED:
                DISCONNECTED_do(); 
                break;
        }
        
    }
    
    // This function is used when StateSmith doesn't know what the active leaf state is at
    // compile time due to sub states or when multiple states need to be exited.
    private void exitUpToStateHandler(StateId desiredState)
    {
        while (this.stateId != desiredState)
        {
            switch (this.stateId)
            {
                case CONNECTED: CONNECTED_exit(); break;
                
                case DISCONNECTED: DISCONNECTED_exit(); break;
                
                default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
            }
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state ROOT
    ////////////////////////////////////////////////////////////////////////////////
    
    private void ROOT_enter()
    {
        this.stateId = StateId.ROOT;
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state CONNECTED
    ////////////////////////////////////////////////////////////////////////////////
    
    private void CONNECTED_enter()
    {
        this.stateId = StateId.CONNECTED;
        
        // CONNECTED behavior
        // uml: enter / { updateProcess();\nfireEvent("foundController"); }
        {
            // Step 1: execute action `updateProcess();\nfireEvent("foundController");`
            updateProcess();
            fireEvent("foundController");
        } // end of behavior for CONNECTED
    }
    
    private void CONNECTED_exit()
    {
        // CONNECTED behavior
        // uml: exit / { fireEvent("lostController"); }
        {
            // Step 1: execute action `fireEvent("lostController");`
            fireEvent("lostController");
        } // end of behavior for CONNECTED
        
        this.stateId = StateId.ROOT;
    }
    
    private void CONNECTED_do()
    {
        // CONNECTED behavior
        // uml: 1. do / { controllerAvailable = dpc.pollController(); }
        {
            // Step 1: execute action `controllerAvailable = dpc.pollController();`
            this.vars.controllerAvailable = this.vars.dpc.pollController();
        } // end of behavior for CONNECTED
        
        // CONNECTED behavior
        // uml: do [!controllerAvailable] TransitionTo(DISCONNECTED)
        if (!this.vars.controllerAvailable)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            CONNECTED_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `DISCONNECTED`.
            DISCONNECTED_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for CONNECTED
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state DISCONNECTED
    ////////////////////////////////////////////////////////////////////////////////
    
    private void DISCONNECTED_enter()
    {
        this.stateId = StateId.DISCONNECTED;
        
        // DISCONNECTED behavior
        // uml: enter / { updateProcess();\ncontrollerAvailable = FALSE();\ntimer = 5000; // attempt to connect on enter }
        {
            // Step 1: execute action `updateProcess();\ncontrollerAvailable = FALSE();\ntimer = 5000; // attempt to connect on enter`
            updateProcess();
            this.vars.controllerAvailable = FALSE();
            this.vars.timer = 5000; // attempt to connect on enter<EOF>
        } // end of behavior for DISCONNECTED
    }
    
    private void DISCONNECTED_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void DISCONNECTED_do()
    {
        // DISCONNECTED behavior
        // uml: 1. do / { timer += DOTIME(); }
        {
            // Step 1: execute action `timer += DOTIME();`
            this.vars.timer += DOTIME();
        } // end of behavior for DISCONNECTED
        
        // DISCONNECTED behavior
        // uml: 2. do [timer >= 5000] / { controllerAvailable = dpc.checkController();\ntimer = 0; }
        if (this.vars.timer >= 5000)
        {
            // Step 1: execute action `controllerAvailable = dpc.checkController();\ntimer = 0;`
            this.vars.controllerAvailable = this.vars.dpc.checkController();
            this.vars.timer = 0;
        } // end of behavior for DISCONNECTED
        
        // DISCONNECTED behavior
        // uml: do [controllerAvailable] TransitionTo(CONNECTED)
        if (this.vars.controllerAvailable)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            DISCONNECTED_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `CONNECTED`.
            CONNECTED_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for DISCONNECTED
        
        // No ancestor handles this event.
    }
    
    // Thread safe.
    public static String stateIdToString(StateId id)
    {
        switch (id)
        {
            case ROOT: return "ROOT";
            case CONNECTED: return "CONNECTED";
            case DISCONNECTED: return "DISCONNECTED";
            default: return "?";
        }
    }
    
    // Thread safe.
    public static String eventIdToString(EventId id)
    {
        switch (id)
        {
            case DO: return "DO";
            default: return "?";
        }
    }

    ////////////////////////////////////////////////////////////////////////////////
    // Inserted code by csx script
    ////////////////////////////////////////////////////////////////////////////////
    
    protected String[] getAllowedEvents(StateId id) {
        return switch (id) {
            case ROOT -> new String[0];  // No events
            case CONNECTED -> new String[]{"DO"};
            case DISCONNECTED -> new String[]{"DO"};
            default -> new String[0];
        };
    }
    
    @Override
    protected String[] getAllEventNames()
    {
        EventId[] values = EventId.values();
        String[] names = new String[values.length];
        
        for (int i = 0; i < values.length; i++)
            names[i] = translateEventName(values[i].name());
        
        return names;
    }
    
    @Override
    protected String[] getAllStateNames()
    {
        StateId[] values = StateId.values();
        String[] names = new String[values.length];
        
        for (int i = 0; i < values.length; i++)
            names[i] = values[i].name();
        
        return names;
    }
    
    @Override
    protected String getCurrentStateString()
    {
        return stateIdToString(this.stateId);
    }
    
    @Override
    protected String[] getBaseAllowedEventsForCurrentState()
    {
        return getAllowedEvents(this.stateId);
    }
    
    // Allow sending strings to dispatchEvent(), with translate functionality
    @Override
    protected void dispatchEvent(String eventName)
    {
        String baseEventName = translateToBaseEventName(eventName);
        dispatchEvent(EventId.valueOf(baseEventName));
    }
    
    @Override
    protected void startSm()
    {
        start();
    }
    
    // See function name
    @SuppressWarnings("unused")
    private void suppressUnusedExitUpToStateHandler()
    {
        exitUpToStateHandler(StateId.ROOT);
    }
    
    ////////////////////////////////////////////////////////////////////////////////
    // End of csx-inserted code
    ////////////////////////////////////////////////////////////////////////////////
}
