// Autogenerated with StateSmith 0.19.0-alpha-1+3da98b58a6e506bc06d88cba576dcc4df8809849.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

package tankpack;

import tankpack.enums.SensorPosition;

// Generated state machine
public class Sm_Sensor_Generated extends StateMachine
{
    public enum EventId
    {
        DO, // The `do` event is special. State event handlers do not consume this event (ancestors all get it too) unless a transition occurs.
        STARTFOLLOW,
        STOPFOLLOW,
    }
    
    public final int EventIdCount = 3;
    
    public enum StateId
    {
        ROOT,
        IDLE,
        READING,
        BLACK,
        WHITE,
    }
    
    public final int StateIdCount = 5;
    
    // Used internally by state machine. Feel free to inspect, but don't modify.
    public StateId stateId;
    
    // State machine variables. Can be used for inputs, outputs, user variables...
    public class Vars
    {
        // These variables can be referenced in diagram and are automatically prefixed with "this.vars." during code generation
        // Protected variables, must be set by inheriting class
        protected Driver_Hardware dh;
        protected SensorPosition sensor;
        protected String sensorWhiteEvent;
        protected String sensorBlackEvent;
        
        // Private variables, only used locally
        private final int CERTAINTY = 2; // certainty threshold
        private int count;
        
        // Public variables, allows for reading / debugging
        public final int BLACK = 175;
        public int colorValue;
    }
    
    // Variables. Can be used for inputs, outputs, user variables...
    public Vars vars = new Vars();
    
    // State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
    public Sm_Sensor_Generated()
    {
    }
    
    // Starts the state machine. Must be called before dispatching events. Not thread safe.
    public void start()
    {
        ROOT_enter();
        // ROOT behavior
        // uml: TransitionTo(ROOT.<InitialState>)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
            // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
            
            // ROOT.<InitialState> behavior
            // uml: TransitionTo(IDLE)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `IDLE`.
                IDLE_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for ROOT.<InitialState>
        } // end of behavior for ROOT
    }
    
    // Dispatches an event to the state machine. Not thread safe.
    // Note! This function assumes that the `eventId` parameter is valid.
    public void dispatchEvent(EventId eventId)
    {
        switch (this.stateId)
        {
            // STATE: Sm_Sensor_Generated
            case ROOT:
                // No events handled by this state (or its ancestors).
                break;
            
            // STATE: IDLE
            case IDLE:
                switch (eventId)
                {
                    case STOPFOLLOW: IDLE_stopfollow(); break;
                    case STARTFOLLOW: IDLE_startfollow(); break;
                }
                break;
            
            // STATE: READING
            case READING:
                switch (eventId)
                {
                    case DO: READING_do(); break;
                    case STOPFOLLOW: READING_stopfollow(); break;
                }
                break;
            
            // STATE: BLACK
            case BLACK:
                switch (eventId)
                {
                    case DO: BLACK_do(); break;
                    case STOPFOLLOW: READING_stopfollow(); break; // First ancestor handler for this event
                }
                break;
            
            // STATE: WHITE
            case WHITE:
                switch (eventId)
                {
                    case DO: WHITE_do(); break;
                    case STOPFOLLOW: READING_stopfollow(); break; // First ancestor handler for this event
                }
                break;
        }
        
    }
    
    // This function is used when StateSmith doesn't know what the active leaf state is at
    // compile time due to sub states or when multiple states need to be exited.
    private void exitUpToStateHandler(StateId desiredState)
    {
        while (this.stateId != desiredState)
        {
            switch (this.stateId)
            {
                case IDLE: IDLE_exit(); break;
                
                case READING: READING_exit(); break;
                
                case BLACK: BLACK_exit(); break;
                
                case WHITE: WHITE_exit(); break;
                
                default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
            }
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state ROOT
    ////////////////////////////////////////////////////////////////////////////////
    
    private void ROOT_enter()
    {
        this.stateId = StateId.ROOT;
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state IDLE
    ////////////////////////////////////////////////////////////////////////////////
    
    private void IDLE_enter()
    {
        this.stateId = StateId.IDLE;
        
        // IDLE behavior
        // uml: enter / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for IDLE
    }
    
    private void IDLE_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void IDLE_startfollow()
    {
        // IDLE behavior
        // uml: STARTFOLLOW TransitionTo(READING)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            IDLE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `READING`.
            READING_enter();
            
            // READING.<InitialState> behavior
            // uml: TransitionTo(WHITE)
            {
                // Step 1: Exit states until we reach `READING` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `WHITE`.
                WHITE_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for READING.<InitialState>
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_stopfollow()
    {
        // IDLE behavior
        // uml: STOPFOLLOW / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state READING
    ////////////////////////////////////////////////////////////////////////////////
    
    private void READING_enter()
    {
        this.stateId = StateId.READING;
        
        // READING behavior
        // uml: enter / { updateProcess();\ncolorValue = 0; }
        {
            // Step 1: execute action `updateProcess();\ncolorValue = 0;`
            updateProcess();
            this.vars.colorValue = 0;
        } // end of behavior for READING
    }
    
    private void READING_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void READING_do()
    {
        // READING behavior
        // uml: do / { colorValue = dh.readSensor(sensor); }
        {
            // Step 1: execute action `colorValue = dh.readSensor(sensor);`
            this.vars.colorValue = this.vars.dh.readSensor(this.vars.sensor);
        } // end of behavior for READING
        
        // No ancestor handles this event.
    }
    
    private void READING_stopfollow()
    {
        // READING behavior
        // uml: STOPFOLLOW TransitionTo(IDLE)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            exitUpToStateHandler(StateId.ROOT);
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `IDLE`.
            IDLE_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for READING
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state BLACK
    ////////////////////////////////////////////////////////////////////////////////
    
    private void BLACK_enter()
    {
        this.stateId = StateId.BLACK;
        
        // BLACK behavior
        // uml: enter / { count = 0; }
        {
            // Step 1: execute action `count = 0;`
            this.vars.count = 0;
        } // end of behavior for BLACK
    }
    
    private void BLACK_exit()
    {
        this.stateId = StateId.READING;
    }
    
    private void BLACK_do()
    {
        boolean consume_event = false;
        
        // BLACK behavior
        // uml: 1. do [colorValue < BLACK] TransitionTo(WHITE)
        if (this.vars.colorValue < this.vars.BLACK)
        {
            // Step 1: Exit states until we reach `READING` state (Least Common Ancestor for transition).
            BLACK_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `WHITE`.
            WHITE_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for BLACK
        
        // BLACK behavior
        // uml: 2. do [count <= CERTAINTY] / { count++; }
        if (this.vars.count <= this.vars.CERTAINTY)
        {
            // `do` events are not normally consumed.
            // Step 1: execute action `count++;`
            this.vars.count++;
        } // end of behavior for BLACK
        
        // BLACK behavior
        // uml: 3. do [count == CERTAINTY] / { fireEvent(sensorBlackEvent); }
        if (this.vars.count == this.vars.CERTAINTY)
        {
            // `do` events are not normally consumed.
            // Step 1: execute action `fireEvent(sensorBlackEvent);`
            fireEvent(this.vars.sensorBlackEvent);
        } // end of behavior for BLACK
        
        // Check if event has been consumed before calling ancestor handler.
        if (!consume_event)
        {
            READING_do();
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state WHITE
    ////////////////////////////////////////////////////////////////////////////////
    
    private void WHITE_enter()
    {
        this.stateId = StateId.WHITE;
        
        // WHITE behavior
        // uml: enter / { count = 0; }
        {
            // Step 1: execute action `count = 0;`
            this.vars.count = 0;
        } // end of behavior for WHITE
    }
    
    private void WHITE_exit()
    {
        this.stateId = StateId.READING;
    }
    
    private void WHITE_do()
    {
        boolean consume_event = false;
        
        // WHITE behavior
        // uml: 1. do [colorValue >= BLACK] TransitionTo(BLACK)
        if (this.vars.colorValue >= this.vars.BLACK)
        {
            // Step 1: Exit states until we reach `READING` state (Least Common Ancestor for transition).
            WHITE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `BLACK`.
            BLACK_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for WHITE
        
        // WHITE behavior
        // uml: 2. do [count <= CERTAINTY] / { count++; }
        if (this.vars.count <= this.vars.CERTAINTY)
        {
            // `do` events are not normally consumed.
            // Step 1: execute action `count++;`
            this.vars.count++;
        } // end of behavior for WHITE
        
        // WHITE behavior
        // uml: 3. do [count == CERTAINTY] / { fireEvent(sensorWhiteEvent); }
        if (this.vars.count == this.vars.CERTAINTY)
        {
            // `do` events are not normally consumed.
            // Step 1: execute action `fireEvent(sensorWhiteEvent);`
            fireEvent(this.vars.sensorWhiteEvent);
        } // end of behavior for WHITE
        
        // Check if event has been consumed before calling ancestor handler.
        if (!consume_event)
        {
            READING_do();
        }
    }
    
    // Thread safe.
    public static String stateIdToString(StateId id)
    {
        switch (id)
        {
            case ROOT: return "ROOT";
            case IDLE: return "IDLE";
            case READING: return "READING";
            case BLACK: return "BLACK";
            case WHITE: return "WHITE";
            default: return "?";
        }
    }
    
    // Thread safe.
    public static String eventIdToString(EventId id)
    {
        switch (id)
        {
            case DO: return "DO";
            case STARTFOLLOW: return "STARTFOLLOW";
            case STOPFOLLOW: return "STOPFOLLOW";
            default: return "?";
        }
    }

    ////////////////////////////////////////////////////////////////////////////////
    // Inserted code by csx script
    ////////////////////////////////////////////////////////////////////////////////
    
    protected String[] getAllowedEvents(StateId id) {
        return switch (id) {
            case ROOT -> new String[0];  // No events
            case IDLE -> new String[]{"STOPFOLLOW", "STARTFOLLOW"};
            case READING -> new String[]{"DO", "STOPFOLLOW"};
            case BLACK -> new String[]{"DO", "STOPFOLLOW"};
            case WHITE -> new String[]{"DO", "STOPFOLLOW"};
            default -> new String[0];
        };
    }
    
    @Override
    protected String[] getAllEventNames()
    {
        EventId[] values = EventId.values();
        String[] names = new String[values.length];
        
        for (int i = 0; i < values.length; i++)
            names[i] = translateEventName(values[i].name());
        
        return names;
    }
    
    @Override
    protected String[] getAllStateNames()
    {
        StateId[] values = StateId.values();
        String[] names = new String[values.length];
        
        for (int i = 0; i < values.length; i++)
            names[i] = values[i].name();
        
        return names;
    }
    
    @Override
    protected String getCurrentStateString()
    {
        return stateIdToString(this.stateId);
    }
    
    @Override
    protected String[] getBaseAllowedEventsForCurrentState()
    {
        return getAllowedEvents(this.stateId);
    }
    
    // Allow sending strings to dispatchEvent(), with translate functionality
    @Override
    protected void dispatchEvent(String eventName)
    {
        String baseEventName = translateToBaseEventName(eventName);
        dispatchEvent(EventId.valueOf(baseEventName));
    }
    
    @Override
    protected void startSm()
    {
        start();
    }
    
    // See function name
    @SuppressWarnings("unused")
    private void suppressUnusedExitUpToStateHandler()
    {
        exitUpToStateHandler(StateId.ROOT);
    }
    
    ////////////////////////////////////////////////////////////////////////////////
    // End of csx-inserted code
    ////////////////////////////////////////////////////////////////////////////////
}
