// Autogenerated with StateSmith 0.19.0+ebc88ca27511ff019dec4076062d7ebc9acd4ee9.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

package tankpack;

import tankpack.enums.SensorPosition;

// Generated state machine
public class Sm_Sensor_Generated extends StateMachine
{
    public enum EventId
    {
        DO, // The `do` event is special. State event handlers do not consume this event (ancestors all get it too) unless a transition occurs.
        SIMULATEBLACKEVENT,
        SIMULATEWHITEEVENT,
        STARTFOLLOW,
        STOPFOLLOW,
    }
    
    public final int EventIdCount = 5;
    
    public enum StateId
    {
        ROOT,
        IDLE,
        READING,
        READING__BLACK,
        READING__WHITE,
        SIMULATION_MODE,
        SIMULATION_MODE__BLACK,
        SIMULATION_MODE__WHITE,
    }
    
    public final int StateIdCount = 8;
    
    // Used internally by state machine. Feel free to inspect, but don't modify.
    public StateId stateId;
    
    // State machine variables. Can be used for inputs, outputs, user variables...
    public class Vars
    {
        // These variables can be referenced in diagram and are automatically prefixed with "this.vars." during code generation
        // Protected variables, must be set by inheriting class
        protected Driver_Hardware dh;
        protected SensorPosition sensor;
        protected String sensorWhiteEvent;
        protected String sensorBlackEvent;
        protected boolean simulation;
        
        // Private variables, only used locally
        private final int CERTAINTY = 2; // certainty threshold
        private int count;
        
        // Public variables, allows for reading / debugging
        public final int BLACK = 175;
        public int colorValue;
    }
    
    // Variables. Can be used for inputs, outputs, user variables...
    public Vars vars = new Vars();
    
    // State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
    public Sm_Sensor_Generated()
    {
    }
    
    // Starts the state machine. Must be called before dispatching events. Not thread safe.
    public void start()
    {
        ROOT_enter();
        // ROOT behavior
        // uml: TransitionTo(ROOT.<InitialState>)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
            // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
            
            // ROOT.<InitialState> behavior
            // uml: TransitionTo(IDLE)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `IDLE`.
                IDLE_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for ROOT.<InitialState>
        } // end of behavior for ROOT
    }
    
    // Dispatches an event to the state machine. Not thread safe.
    // Note! This function assumes that the `eventId` parameter is valid.
    public void dispatchEvent(EventId eventId)
    {
        switch (this.stateId)
        {
            // STATE: Sm_Sensor_Generated
            case ROOT:
                // No events handled by this state (or its ancestors).
                break;
            
            // STATE: IDLE
            case IDLE:
                switch (eventId)
                {
                    case STOPFOLLOW: IDLE_stopfollow(); break;
                    case SIMULATEWHITEEVENT: IDLE_simulatewhiteevent(); break;
                    case SIMULATEBLACKEVENT: IDLE_simulateblackevent(); break;
                    case STARTFOLLOW: IDLE_startfollow(); break;
                }
                break;
            
            // STATE: READING
            case READING:
                switch (eventId)
                {
                    case DO: READING_do(); break;
                    case SIMULATEWHITEEVENT: READING_simulatewhiteevent(); break;
                    case SIMULATEBLACKEVENT: READING_simulateblackevent(); break;
                    case STOPFOLLOW: READING_stopfollow(); break;
                }
                break;
            
            // STATE: READING__BLACK
            case READING__BLACK:
                switch (eventId)
                {
                    case DO: READING__BLACK_do(); break;
                    case STOPFOLLOW: READING_stopfollow(); break; // First ancestor handler for this event
                    case SIMULATEWHITEEVENT: READING_simulatewhiteevent(); break; // First ancestor handler for this event
                    case SIMULATEBLACKEVENT: READING_simulateblackevent(); break; // First ancestor handler for this event
                }
                break;
            
            // STATE: READING__WHITE
            case READING__WHITE:
                switch (eventId)
                {
                    case DO: READING__WHITE_do(); break;
                    case STOPFOLLOW: READING_stopfollow(); break; // First ancestor handler for this event
                    case SIMULATEWHITEEVENT: READING_simulatewhiteevent(); break; // First ancestor handler for this event
                    case SIMULATEBLACKEVENT: READING_simulateblackevent(); break; // First ancestor handler for this event
                }
                break;
            
            // STATE: SIMULATION_MODE
            case SIMULATION_MODE:
                switch (eventId)
                {
                    case STOPFOLLOW: SIMULATION_MODE_stopfollow(); break;
                }
                break;
            
            // STATE: SIMULATION_MODE__BLACK
            case SIMULATION_MODE__BLACK:
                switch (eventId)
                {
                    case DO: SIMULATION_MODE__BLACK_do(); break;
                    case SIMULATEBLACKEVENT: SIMULATION_MODE__BLACK_simulateblackevent(); break;
                    case SIMULATEWHITEEVENT: SIMULATION_MODE__BLACK_simulatewhiteevent(); break;
                    case STOPFOLLOW: SIMULATION_MODE_stopfollow(); break; // First ancestor handler for this event
                }
                break;
            
            // STATE: SIMULATION_MODE__WHITE
            case SIMULATION_MODE__WHITE:
                switch (eventId)
                {
                    case DO: SIMULATION_MODE__WHITE_do(); break;
                    case SIMULATEWHITEEVENT: SIMULATION_MODE__WHITE_simulatewhiteevent(); break;
                    case SIMULATEBLACKEVENT: SIMULATION_MODE__WHITE_simulateblackevent(); break;
                    case STOPFOLLOW: SIMULATION_MODE_stopfollow(); break; // First ancestor handler for this event
                }
                break;
        }
        
    }
    
    // This function is used when StateSmith doesn't know what the active leaf state is at
    // compile time due to sub states or when multiple states need to be exited.
    private void exitUpToStateHandler(StateId desiredState)
    {
        while (this.stateId != desiredState)
        {
            switch (this.stateId)
            {
                case IDLE: IDLE_exit(); break;
                
                case READING: READING_exit(); break;
                
                case READING__BLACK: READING__BLACK_exit(); break;
                
                case READING__WHITE: READING__WHITE_exit(); break;
                
                case SIMULATION_MODE: SIMULATION_MODE_exit(); break;
                
                case SIMULATION_MODE__BLACK: SIMULATION_MODE__BLACK_exit(); break;
                
                case SIMULATION_MODE__WHITE: SIMULATION_MODE__WHITE_exit(); break;
                
                default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
            }
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state ROOT
    ////////////////////////////////////////////////////////////////////////////////
    
    private void ROOT_enter()
    {
        this.stateId = StateId.ROOT;
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state IDLE
    ////////////////////////////////////////////////////////////////////////////////
    
    private void IDLE_enter()
    {
        this.stateId = StateId.IDLE;
        
        // IDLE behavior
        // uml: enter / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for IDLE
    }
    
    private void IDLE_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void IDLE_simulateblackevent()
    {
        // IDLE behavior
        // uml: SIMULATEBLACKEVENT / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_simulatewhiteevent()
    {
        // IDLE behavior
        // uml: SIMULATEWHITEEVENT / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_startfollow()
    {
        // IDLE behavior
        // uml: STARTFOLLOW [!simulation] TransitionTo(READING)
        if (!this.vars.simulation)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            IDLE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `READING`.
            READING_enter();
            
            // READING.<InitialState> behavior
            // uml: TransitionTo(READING__WHITE)
            {
                // Step 1: Exit states until we reach `READING` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `READING__WHITE`.
                READING__WHITE_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for READING.<InitialState>
        } // end of behavior for IDLE
        
        // IDLE behavior
        // uml: STARTFOLLOW [simulation] TransitionTo(SIMULATION_MODE)
        if (this.vars.simulation)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            IDLE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `SIMULATION_MODE`.
            SIMULATION_MODE_enter();
            
            // SIMULATION_MODE.<InitialState> behavior
            // uml: TransitionTo(SIMULATION_MODE__WHITE)
            {
                // Step 1: Exit states until we reach `SIMULATION_MODE` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `SIMULATION_MODE__WHITE`.
                SIMULATION_MODE__WHITE_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for SIMULATION_MODE.<InitialState>
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_stopfollow()
    {
        // IDLE behavior
        // uml: STOPFOLLOW / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state READING
    ////////////////////////////////////////////////////////////////////////////////
    
    private void READING_enter()
    {
        this.stateId = StateId.READING;
        
        // READING behavior
        // uml: enter / { updateProcess();\ncolorValue = 0; }
        {
            // Step 1: execute action `updateProcess();\ncolorValue = 0;`
            updateProcess();
            this.vars.colorValue = 0;
        } // end of behavior for READING
    }
    
    private void READING_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void READING_do()
    {
        // READING behavior
        // uml: do / { colorValue = dh.readSensor(sensor); }
        {
            // Step 1: execute action `colorValue = dh.readSensor(sensor);`
            this.vars.colorValue = this.vars.dh.readSensor(this.vars.sensor);
        } // end of behavior for READING
        
        // No ancestor handles this event.
    }
    
    private void READING_simulateblackevent()
    {
        // READING behavior
        // uml: SIMULATEBLACKEVENT / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for READING
        
        // No ancestor handles this event.
    }
    
    private void READING_simulatewhiteevent()
    {
        // READING behavior
        // uml: SIMULATEWHITEEVENT / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for READING
        
        // No ancestor handles this event.
    }
    
    private void READING_stopfollow()
    {
        // READING behavior
        // uml: STOPFOLLOW TransitionTo(IDLE)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            exitUpToStateHandler(StateId.ROOT);
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `IDLE`.
            IDLE_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for READING
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state READING__BLACK
    ////////////////////////////////////////////////////////////////////////////////
    
    private void READING__BLACK_enter()
    {
        this.stateId = StateId.READING__BLACK;
        
        // READING__BLACK behavior
        // uml: enter / { count = 0; }
        {
            // Step 1: execute action `count = 0;`
            this.vars.count = 0;
        } // end of behavior for READING__BLACK
    }
    
    private void READING__BLACK_exit()
    {
        this.stateId = StateId.READING;
    }
    
    private void READING__BLACK_do()
    {
        boolean consume_event = false;
        
        // READING__BLACK behavior
        // uml: 1. do [colorValue < BLACK] TransitionTo(READING__WHITE)
        if (this.vars.colorValue < this.vars.BLACK)
        {
            // Step 1: Exit states until we reach `READING` state (Least Common Ancestor for transition).
            READING__BLACK_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `READING__WHITE`.
            READING__WHITE_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for READING__BLACK
        
        // READING__BLACK behavior
        // uml: 2. do [count <= CERTAINTY] / { count++; }
        if (this.vars.count <= this.vars.CERTAINTY)
        {
            // `do` events are not normally consumed.
            // Step 1: execute action `count++;`
            this.vars.count++;
        } // end of behavior for READING__BLACK
        
        // READING__BLACK behavior
        // uml: 3. do [count == CERTAINTY] / { fireEvent(sensorBlackEvent); }
        if (this.vars.count == this.vars.CERTAINTY)
        {
            // `do` events are not normally consumed.
            // Step 1: execute action `fireEvent(sensorBlackEvent);`
            fireEvent(this.vars.sensorBlackEvent);
        } // end of behavior for READING__BLACK
        
        // Check if event has been consumed before calling ancestor handler.
        if (!consume_event)
        {
            READING_do();
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state READING__WHITE
    ////////////////////////////////////////////////////////////////////////////////
    
    private void READING__WHITE_enter()
    {
        this.stateId = StateId.READING__WHITE;
        
        // READING__WHITE behavior
        // uml: enter / { count = 0; }
        {
            // Step 1: execute action `count = 0;`
            this.vars.count = 0;
        } // end of behavior for READING__WHITE
    }
    
    private void READING__WHITE_exit()
    {
        this.stateId = StateId.READING;
    }
    
    private void READING__WHITE_do()
    {
        boolean consume_event = false;
        
        // READING__WHITE behavior
        // uml: 1. do [colorValue >= BLACK] TransitionTo(READING__BLACK)
        if (this.vars.colorValue >= this.vars.BLACK)
        {
            // Step 1: Exit states until we reach `READING` state (Least Common Ancestor for transition).
            READING__WHITE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `READING__BLACK`.
            READING__BLACK_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for READING__WHITE
        
        // READING__WHITE behavior
        // uml: 2. do [count <= CERTAINTY] / { count++; }
        if (this.vars.count <= this.vars.CERTAINTY)
        {
            // `do` events are not normally consumed.
            // Step 1: execute action `count++;`
            this.vars.count++;
        } // end of behavior for READING__WHITE
        
        // READING__WHITE behavior
        // uml: 3. do [count == CERTAINTY] / { fireEvent(sensorWhiteEvent); }
        if (this.vars.count == this.vars.CERTAINTY)
        {
            // `do` events are not normally consumed.
            // Step 1: execute action `fireEvent(sensorWhiteEvent);`
            fireEvent(this.vars.sensorWhiteEvent);
        } // end of behavior for READING__WHITE
        
        // Check if event has been consumed before calling ancestor handler.
        if (!consume_event)
        {
            READING_do();
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state SIMULATION_MODE
    ////////////////////////////////////////////////////////////////////////////////
    
    private void SIMULATION_MODE_enter()
    {
        this.stateId = StateId.SIMULATION_MODE;
    }
    
    private void SIMULATION_MODE_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void SIMULATION_MODE_stopfollow()
    {
        // SIMULATION_MODE behavior
        // uml: STOPFOLLOW TransitionTo(IDLE)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            exitUpToStateHandler(StateId.ROOT);
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `IDLE`.
            IDLE_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for SIMULATION_MODE
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state SIMULATION_MODE__BLACK
    ////////////////////////////////////////////////////////////////////////////////
    
    private void SIMULATION_MODE__BLACK_enter()
    {
        this.stateId = StateId.SIMULATION_MODE__BLACK;
        
        // SIMULATION_MODE__BLACK behavior
        // uml: enter / { updateProcess();\ncount = 0; }
        {
            // Step 1: execute action `updateProcess();\ncount = 0;`
            updateProcess();
            this.vars.count = 0;
        } // end of behavior for SIMULATION_MODE__BLACK
    }
    
    private void SIMULATION_MODE__BLACK_exit()
    {
        this.stateId = StateId.SIMULATION_MODE;
    }
    
    private void SIMULATION_MODE__BLACK_do()
    {
        // SIMULATION_MODE__BLACK behavior
        // uml: 2. do [count <= CERTAINTY] / { count++; }
        if (this.vars.count <= this.vars.CERTAINTY)
        {
            // Step 1: execute action `count++;`
            this.vars.count++;
        } // end of behavior for SIMULATION_MODE__BLACK
        
        // SIMULATION_MODE__BLACK behavior
        // uml: 3. do [count == CERTAINTY] / { fireEvent(sensorBlackEvent); }
        if (this.vars.count == this.vars.CERTAINTY)
        {
            // Step 1: execute action `fireEvent(sensorBlackEvent);`
            fireEvent(this.vars.sensorBlackEvent);
        } // end of behavior for SIMULATION_MODE__BLACK
        
        // No ancestor handles this event.
    }
    
    private void SIMULATION_MODE__BLACK_simulateblackevent()
    {
        // SIMULATION_MODE__BLACK behavior
        // uml: SIMULATEBLACKEVENT / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for SIMULATION_MODE__BLACK
        
        // No ancestor handles this event.
    }
    
    private void SIMULATION_MODE__BLACK_simulatewhiteevent()
    {
        // SIMULATION_MODE__BLACK behavior
        // uml: SIMULATEWHITEEVENT TransitionTo(SIMULATION_MODE__WHITE)
        {
            // Step 1: Exit states until we reach `SIMULATION_MODE` state (Least Common Ancestor for transition).
            SIMULATION_MODE__BLACK_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `SIMULATION_MODE__WHITE`.
            SIMULATION_MODE__WHITE_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for SIMULATION_MODE__BLACK
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state SIMULATION_MODE__WHITE
    ////////////////////////////////////////////////////////////////////////////////
    
    private void SIMULATION_MODE__WHITE_enter()
    {
        this.stateId = StateId.SIMULATION_MODE__WHITE;
        
        // SIMULATION_MODE__WHITE behavior
        // uml: enter / { updateProcess();\ncount = 0; }
        {
            // Step 1: execute action `updateProcess();\ncount = 0;`
            updateProcess();
            this.vars.count = 0;
        } // end of behavior for SIMULATION_MODE__WHITE
    }
    
    private void SIMULATION_MODE__WHITE_exit()
    {
        this.stateId = StateId.SIMULATION_MODE;
    }
    
    private void SIMULATION_MODE__WHITE_do()
    {
        // SIMULATION_MODE__WHITE behavior
        // uml: 2. do [count <= CERTAINTY] / { count++; }
        if (this.vars.count <= this.vars.CERTAINTY)
        {
            // Step 1: execute action `count++;`
            this.vars.count++;
        } // end of behavior for SIMULATION_MODE__WHITE
        
        // SIMULATION_MODE__WHITE behavior
        // uml: 3. do [count == CERTAINTY] / { fireEvent(sensorWhiteEvent); }
        if (this.vars.count == this.vars.CERTAINTY)
        {
            // Step 1: execute action `fireEvent(sensorWhiteEvent);`
            fireEvent(this.vars.sensorWhiteEvent);
        } // end of behavior for SIMULATION_MODE__WHITE
        
        // No ancestor handles this event.
    }
    
    private void SIMULATION_MODE__WHITE_simulateblackevent()
    {
        // SIMULATION_MODE__WHITE behavior
        // uml: SIMULATEBLACKEVENT TransitionTo(SIMULATION_MODE__BLACK)
        {
            // Step 1: Exit states until we reach `SIMULATION_MODE` state (Least Common Ancestor for transition).
            SIMULATION_MODE__WHITE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `SIMULATION_MODE__BLACK`.
            SIMULATION_MODE__BLACK_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for SIMULATION_MODE__WHITE
        
        // No ancestor handles this event.
    }
    
    private void SIMULATION_MODE__WHITE_simulatewhiteevent()
    {
        // SIMULATION_MODE__WHITE behavior
        // uml: SIMULATEWHITEEVENT / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for SIMULATION_MODE__WHITE
        
        // No ancestor handles this event.
    }
    
    // Thread safe.
    public static String stateIdToString(StateId id)
    {
        switch (id)
        {
            case ROOT: return "ROOT";
            case IDLE: return "IDLE";
            case READING: return "READING";
            case READING__BLACK: return "READING__BLACK";
            case READING__WHITE: return "READING__WHITE";
            case SIMULATION_MODE: return "SIMULATION_MODE";
            case SIMULATION_MODE__BLACK: return "SIMULATION_MODE__BLACK";
            case SIMULATION_MODE__WHITE: return "SIMULATION_MODE__WHITE";
            default: return "?";
        }
    }
    
    // Thread safe.
    public static String eventIdToString(EventId id)
    {
        switch (id)
        {
            case DO: return "DO";
            case SIMULATEBLACKEVENT: return "SIMULATEBLACKEVENT";
            case SIMULATEWHITEEVENT: return "SIMULATEWHITEEVENT";
            case STARTFOLLOW: return "STARTFOLLOW";
            case STOPFOLLOW: return "STOPFOLLOW";
            default: return "?";
        }
    }

    ////////////////////////////////////////////////////////////////////////////////
    // Inserted code by csx script
    ////////////////////////////////////////////////////////////////////////////////
    
    protected String[] getAllowedEvents(StateId id) {
        return switch (id) {
            case ROOT -> new String[0];  // No events
            case IDLE -> new String[]{"STOPFOLLOW", "SIMULATEWHITEEVENT", "SIMULATEBLACKEVENT", "STARTFOLLOW"};
            case READING -> new String[]{"DO", "SIMULATEWHITEEVENT", "SIMULATEBLACKEVENT", "STOPFOLLOW"};
            case READING__BLACK -> new String[]{"DO", "STOPFOLLOW", "SIMULATEWHITEEVENT", "SIMULATEBLACKEVENT"};
            case READING__WHITE -> new String[]{"DO", "STOPFOLLOW", "SIMULATEWHITEEVENT", "SIMULATEBLACKEVENT"};
            case SIMULATION_MODE -> new String[]{"STOPFOLLOW"};
            case SIMULATION_MODE__BLACK -> new String[]{"DO", "SIMULATEBLACKEVENT", "SIMULATEWHITEEVENT", "STOPFOLLOW"};
            case SIMULATION_MODE__WHITE -> new String[]{"DO", "SIMULATEWHITEEVENT", "SIMULATEBLACKEVENT", "STOPFOLLOW"};
            default -> new String[0];
        };
    }
    
    @Override
    protected String[] getAllEventNames()
    {
        EventId[] values = EventId.values();
        String[] names = new String[values.length];
        
        for (int i = 0; i < values.length; i++)
            names[i] = translateEventName(values[i].name());
        
        return names;
    }
    
    @Override
    protected String[] getAllStateNames()
    {
        StateId[] values = StateId.values();
        String[] names = new String[values.length];
        
        for (int i = 0; i < values.length; i++)
            names[i] = values[i].name();
        
        return names;
    }
    
    @Override
    protected String getCurrentStateString()
    {
        return stateIdToString(this.stateId);
    }
    
    @Override
    protected String[] getBaseAllowedEventsForCurrentState()
    {
        return getAllowedEvents(this.stateId);
    }
    
    // Allow sending strings to dispatchEvent(), with translate functionality
    @Override
    protected void dispatchEvent(String eventName)
    {
        String baseEventName = translateToBaseEventName(eventName);
        dispatchEvent(EventId.valueOf(baseEventName));
    }
    
    @Override
    protected void startSm()
    {
        start();
    }
    
    // See function name
    @SuppressWarnings("unused")
    private void suppressUnusedExitUpToStateHandler()
    {
        exitUpToStateHandler(StateId.ROOT);
    }
    
    ////////////////////////////////////////////////////////////////////////////////
    // End of csx-inserted code
    ////////////////////////////////////////////////////////////////////////////////
}
