// Autogenerated with StateSmith 0.19.0+ebc88ca27511ff019dec4076062d7ebc9acd4ee9.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

package tankpack;

// Generated state machine
public class Sm_Tracks_Generated extends StateMachine
{
    public enum EventId
    {
        LEFTSTICKBACKWARD,
        LEFTSTICKBACKWARDLEFT,
        LEFTSTICKBACKWARDRIGHT,
        LEFTSTICKFORWARD,
        LEFTSTICKFORWARDLEFT,
        LEFTSTICKFORWARDRIGHT,
        LEFTSTICKIDLE,
        LEFTSTICKLEFT,
        LEFTSTICKRIGHT,
    }
    
    public final int EventIdCount = 9;
    
    public enum StateId
    {
        ROOT,
        IDLE,
        MANUAL_CONTROL,
        BACKWARD,
        BACKWARDLEFT,
        BACKWARDRIGHT,
        FORWARD,
        FORWARDLEFT,
        FORWARDRIGHT,
        LEFT,
        RIGHT,
    }
    
    public final int StateIdCount = 11;
    
    // Used internally by state machine. Feel free to inspect, but don't modify.
    public StateId stateId;
    
    // State machine variables. Can be used for inputs, outputs, user variables...
    public class Vars
    {
        // These variables can be referenced in diagram and are automatically prefixed with "this.vars." during code generation
        // Protected variables, must be set by inheriting class
        protected int speed = 0;
        
        // Private variables, only used locally
    }
    
    // Variables. Can be used for inputs, outputs, user variables...
    public Vars vars = new Vars();
    
    // State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
    public Sm_Tracks_Generated()
    {
    }
    
    // Starts the state machine. Must be called before dispatching events. Not thread safe.
    public void start()
    {
        ROOT_enter();
        // ROOT behavior
        // uml: TransitionTo(ROOT.<InitialState>)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
            // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
            
            // ROOT.<InitialState> behavior
            // uml: TransitionTo(IDLE)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `IDLE`.
                IDLE_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for ROOT.<InitialState>
        } // end of behavior for ROOT
    }
    
    // Dispatches an event to the state machine. Not thread safe.
    // Note! This function assumes that the `eventId` parameter is valid.
    public void dispatchEvent(EventId eventId)
    {
        switch (this.stateId)
        {
            // STATE: Sm_Tracks_Generated
            case ROOT:
                // No events handled by this state (or its ancestors).
                break;
            
            // STATE: IDLE
            case IDLE:
                switch (eventId)
                {
                    case LEFTSTICKIDLE: IDLE_leftstickidle(); break;
                    case LEFTSTICKFORWARD: IDLE_leftstickforward(); break;
                    case LEFTSTICKFORWARDRIGHT: IDLE_leftstickforwardright(); break;
                    case LEFTSTICKRIGHT: IDLE_leftstickright(); break;
                    case LEFTSTICKBACKWARDRIGHT: IDLE_leftstickbackwardright(); break;
                    case LEFTSTICKBACKWARD: IDLE_leftstickbackward(); break;
                    case LEFTSTICKBACKWARDLEFT: IDLE_leftstickbackwardleft(); break;
                    case LEFTSTICKLEFT: IDLE_leftstickleft(); break;
                    case LEFTSTICKFORWARDLEFT: IDLE_leftstickforwardleft(); break;
                }
                break;
            
            // STATE: MANUAL_CONTROL
            case MANUAL_CONTROL:
                switch (eventId)
                {
                    case LEFTSTICKIDLE: MANUAL_CONTROL_leftstickidle(); break;
                    case LEFTSTICKFORWARD: MANUAL_CONTROL_leftstickforward(); break;
                    case LEFTSTICKFORWARDRIGHT: MANUAL_CONTROL_leftstickforwardright(); break;
                    case LEFTSTICKRIGHT: MANUAL_CONTROL_leftstickright(); break;
                    case LEFTSTICKBACKWARDRIGHT: MANUAL_CONTROL_leftstickbackwardright(); break;
                    case LEFTSTICKBACKWARD: MANUAL_CONTROL_leftstickbackward(); break;
                    case LEFTSTICKBACKWARDLEFT: MANUAL_CONTROL_leftstickbackwardleft(); break;
                    case LEFTSTICKLEFT: MANUAL_CONTROL_leftstickleft(); break;
                    case LEFTSTICKFORWARDLEFT: MANUAL_CONTROL_leftstickforwardleft(); break;
                }
                break;
            
            // STATE: BACKWARD
            case BACKWARD:
                switch (eventId)
                {
                    case LEFTSTICKIDLE: MANUAL_CONTROL_leftstickidle(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARD: MANUAL_CONTROL_leftstickforward(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARDRIGHT: MANUAL_CONTROL_leftstickforwardright(); break; // First ancestor handler for this event
                    case LEFTSTICKRIGHT: MANUAL_CONTROL_leftstickright(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARDRIGHT: MANUAL_CONTROL_leftstickbackwardright(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARD: MANUAL_CONTROL_leftstickbackward(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARDLEFT: MANUAL_CONTROL_leftstickbackwardleft(); break; // First ancestor handler for this event
                    case LEFTSTICKLEFT: MANUAL_CONTROL_leftstickleft(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARDLEFT: MANUAL_CONTROL_leftstickforwardleft(); break; // First ancestor handler for this event
                }
                break;
            
            // STATE: BACKWARDLEFT
            case BACKWARDLEFT:
                switch (eventId)
                {
                    case LEFTSTICKIDLE: MANUAL_CONTROL_leftstickidle(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARD: MANUAL_CONTROL_leftstickforward(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARDRIGHT: MANUAL_CONTROL_leftstickforwardright(); break; // First ancestor handler for this event
                    case LEFTSTICKRIGHT: MANUAL_CONTROL_leftstickright(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARDRIGHT: MANUAL_CONTROL_leftstickbackwardright(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARD: MANUAL_CONTROL_leftstickbackward(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARDLEFT: MANUAL_CONTROL_leftstickbackwardleft(); break; // First ancestor handler for this event
                    case LEFTSTICKLEFT: MANUAL_CONTROL_leftstickleft(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARDLEFT: MANUAL_CONTROL_leftstickforwardleft(); break; // First ancestor handler for this event
                }
                break;
            
            // STATE: BACKWARDRIGHT
            case BACKWARDRIGHT:
                switch (eventId)
                {
                    case LEFTSTICKIDLE: MANUAL_CONTROL_leftstickidle(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARD: MANUAL_CONTROL_leftstickforward(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARDRIGHT: MANUAL_CONTROL_leftstickforwardright(); break; // First ancestor handler for this event
                    case LEFTSTICKRIGHT: MANUAL_CONTROL_leftstickright(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARDRIGHT: MANUAL_CONTROL_leftstickbackwardright(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARD: MANUAL_CONTROL_leftstickbackward(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARDLEFT: MANUAL_CONTROL_leftstickbackwardleft(); break; // First ancestor handler for this event
                    case LEFTSTICKLEFT: MANUAL_CONTROL_leftstickleft(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARDLEFT: MANUAL_CONTROL_leftstickforwardleft(); break; // First ancestor handler for this event
                }
                break;
            
            // STATE: FORWARD
            case FORWARD:
                switch (eventId)
                {
                    case LEFTSTICKIDLE: MANUAL_CONTROL_leftstickidle(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARD: MANUAL_CONTROL_leftstickforward(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARDRIGHT: MANUAL_CONTROL_leftstickforwardright(); break; // First ancestor handler for this event
                    case LEFTSTICKRIGHT: MANUAL_CONTROL_leftstickright(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARDRIGHT: MANUAL_CONTROL_leftstickbackwardright(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARD: MANUAL_CONTROL_leftstickbackward(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARDLEFT: MANUAL_CONTROL_leftstickbackwardleft(); break; // First ancestor handler for this event
                    case LEFTSTICKLEFT: MANUAL_CONTROL_leftstickleft(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARDLEFT: MANUAL_CONTROL_leftstickforwardleft(); break; // First ancestor handler for this event
                }
                break;
            
            // STATE: FORWARDLEFT
            case FORWARDLEFT:
                switch (eventId)
                {
                    case LEFTSTICKIDLE: MANUAL_CONTROL_leftstickidle(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARD: MANUAL_CONTROL_leftstickforward(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARDRIGHT: MANUAL_CONTROL_leftstickforwardright(); break; // First ancestor handler for this event
                    case LEFTSTICKRIGHT: MANUAL_CONTROL_leftstickright(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARDRIGHT: MANUAL_CONTROL_leftstickbackwardright(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARD: MANUAL_CONTROL_leftstickbackward(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARDLEFT: MANUAL_CONTROL_leftstickbackwardleft(); break; // First ancestor handler for this event
                    case LEFTSTICKLEFT: MANUAL_CONTROL_leftstickleft(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARDLEFT: MANUAL_CONTROL_leftstickforwardleft(); break; // First ancestor handler for this event
                }
                break;
            
            // STATE: FORWARDRIGHT
            case FORWARDRIGHT:
                switch (eventId)
                {
                    case LEFTSTICKIDLE: MANUAL_CONTROL_leftstickidle(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARD: MANUAL_CONTROL_leftstickforward(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARDRIGHT: MANUAL_CONTROL_leftstickforwardright(); break; // First ancestor handler for this event
                    case LEFTSTICKRIGHT: MANUAL_CONTROL_leftstickright(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARDRIGHT: MANUAL_CONTROL_leftstickbackwardright(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARD: MANUAL_CONTROL_leftstickbackward(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARDLEFT: MANUAL_CONTROL_leftstickbackwardleft(); break; // First ancestor handler for this event
                    case LEFTSTICKLEFT: MANUAL_CONTROL_leftstickleft(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARDLEFT: MANUAL_CONTROL_leftstickforwardleft(); break; // First ancestor handler for this event
                }
                break;
            
            // STATE: LEFT
            case LEFT:
                switch (eventId)
                {
                    case LEFTSTICKIDLE: MANUAL_CONTROL_leftstickidle(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARD: MANUAL_CONTROL_leftstickforward(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARDRIGHT: MANUAL_CONTROL_leftstickforwardright(); break; // First ancestor handler for this event
                    case LEFTSTICKRIGHT: MANUAL_CONTROL_leftstickright(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARDRIGHT: MANUAL_CONTROL_leftstickbackwardright(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARD: MANUAL_CONTROL_leftstickbackward(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARDLEFT: MANUAL_CONTROL_leftstickbackwardleft(); break; // First ancestor handler for this event
                    case LEFTSTICKLEFT: MANUAL_CONTROL_leftstickleft(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARDLEFT: MANUAL_CONTROL_leftstickforwardleft(); break; // First ancestor handler for this event
                }
                break;
            
            // STATE: RIGHT
            case RIGHT:
                switch (eventId)
                {
                    case LEFTSTICKIDLE: MANUAL_CONTROL_leftstickidle(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARD: MANUAL_CONTROL_leftstickforward(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARDRIGHT: MANUAL_CONTROL_leftstickforwardright(); break; // First ancestor handler for this event
                    case LEFTSTICKRIGHT: MANUAL_CONTROL_leftstickright(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARDRIGHT: MANUAL_CONTROL_leftstickbackwardright(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARD: MANUAL_CONTROL_leftstickbackward(); break; // First ancestor handler for this event
                    case LEFTSTICKBACKWARDLEFT: MANUAL_CONTROL_leftstickbackwardleft(); break; // First ancestor handler for this event
                    case LEFTSTICKLEFT: MANUAL_CONTROL_leftstickleft(); break; // First ancestor handler for this event
                    case LEFTSTICKFORWARDLEFT: MANUAL_CONTROL_leftstickforwardleft(); break; // First ancestor handler for this event
                }
                break;
        }
        
    }
    
    // This function is used when StateSmith doesn't know what the active leaf state is at
    // compile time due to sub states or when multiple states need to be exited.
    private void exitUpToStateHandler(StateId desiredState)
    {
        while (this.stateId != desiredState)
        {
            switch (this.stateId)
            {
                case IDLE: IDLE_exit(); break;
                
                case MANUAL_CONTROL: MANUAL_CONTROL_exit(); break;
                
                case BACKWARD: BACKWARD_exit(); break;
                
                case BACKWARDLEFT: BACKWARDLEFT_exit(); break;
                
                case BACKWARDRIGHT: BACKWARDRIGHT_exit(); break;
                
                case FORWARD: FORWARD_exit(); break;
                
                case FORWARDLEFT: FORWARDLEFT_exit(); break;
                
                case FORWARDRIGHT: FORWARDRIGHT_exit(); break;
                
                case LEFT: LEFT_exit(); break;
                
                case RIGHT: RIGHT_exit(); break;
                
                default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
            }
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state ROOT
    ////////////////////////////////////////////////////////////////////////////////
    
    private void ROOT_enter()
    {
        this.stateId = StateId.ROOT;
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state IDLE
    ////////////////////////////////////////////////////////////////////////////////
    
    private void IDLE_enter()
    {
        this.stateId = StateId.IDLE;
        
        // IDLE behavior
        // uml: enter / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for IDLE
    }
    
    private void IDLE_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void IDLE_leftstickbackward()
    {
        // IDLE behavior
        // uml: LEFTSTICKBACKWARD TransitionTo(MANUAL_CONTROL.<EntryPoint>(backward))
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            IDLE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `MANUAL_CONTROL.<EntryPoint>(backward)`.
            MANUAL_CONTROL_enter();
            // MANUAL_CONTROL.<EntryPoint>(backward) is a pseudo state and cannot have an `enter` trigger.
            
            // MANUAL_CONTROL.<EntryPoint>(backward) behavior
            // uml: TransitionTo(BACKWARD)
            {
                // Step 1: Exit states until we reach `MANUAL_CONTROL` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `BACKWARD`.
                BACKWARD_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for MANUAL_CONTROL.<EntryPoint>(backward)
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_leftstickbackwardleft()
    {
        // IDLE behavior
        // uml: LEFTSTICKBACKWARDLEFT TransitionTo(MANUAL_CONTROL.<EntryPoint>(backwardLeft))
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            IDLE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `MANUAL_CONTROL.<EntryPoint>(backwardLeft)`.
            MANUAL_CONTROL_enter();
            // MANUAL_CONTROL.<EntryPoint>(backwardLeft) is a pseudo state and cannot have an `enter` trigger.
            
            // MANUAL_CONTROL.<EntryPoint>(backwardLeft) behavior
            // uml: TransitionTo(BACKWARDLEFT)
            {
                // Step 1: Exit states until we reach `MANUAL_CONTROL` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `BACKWARDLEFT`.
                BACKWARDLEFT_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for MANUAL_CONTROL.<EntryPoint>(backwardLeft)
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_leftstickbackwardright()
    {
        // IDLE behavior
        // uml: LEFTSTICKBACKWARDRIGHT TransitionTo(MANUAL_CONTROL.<EntryPoint>(backwardRight))
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            IDLE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `MANUAL_CONTROL.<EntryPoint>(backwardRight)`.
            MANUAL_CONTROL_enter();
            // MANUAL_CONTROL.<EntryPoint>(backwardRight) is a pseudo state and cannot have an `enter` trigger.
            
            // MANUAL_CONTROL.<EntryPoint>(backwardRight) behavior
            // uml: TransitionTo(BACKWARDRIGHT)
            {
                // Step 1: Exit states until we reach `MANUAL_CONTROL` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `BACKWARDRIGHT`.
                BACKWARDRIGHT_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for MANUAL_CONTROL.<EntryPoint>(backwardRight)
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_leftstickforward()
    {
        // IDLE behavior
        // uml: LEFTSTICKFORWARD TransitionTo(MANUAL_CONTROL.<EntryPoint>(forward))
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            IDLE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `MANUAL_CONTROL.<EntryPoint>(forward)`.
            MANUAL_CONTROL_enter();
            // MANUAL_CONTROL.<EntryPoint>(forward) is a pseudo state and cannot have an `enter` trigger.
            
            // MANUAL_CONTROL.<EntryPoint>(forward) behavior
            // uml: TransitionTo(FORWARD)
            {
                // Step 1: Exit states until we reach `MANUAL_CONTROL` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `FORWARD`.
                FORWARD_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for MANUAL_CONTROL.<EntryPoint>(forward)
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_leftstickforwardleft()
    {
        // IDLE behavior
        // uml: LEFTSTICKFORWARDLEFT TransitionTo(MANUAL_CONTROL.<EntryPoint>(forwardLeft))
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            IDLE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `MANUAL_CONTROL.<EntryPoint>(forwardLeft)`.
            MANUAL_CONTROL_enter();
            // MANUAL_CONTROL.<EntryPoint>(forwardLeft) is a pseudo state and cannot have an `enter` trigger.
            
            // MANUAL_CONTROL.<EntryPoint>(forwardLeft) behavior
            // uml: TransitionTo(FORWARDLEFT)
            {
                // Step 1: Exit states until we reach `MANUAL_CONTROL` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `FORWARDLEFT`.
                FORWARDLEFT_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for MANUAL_CONTROL.<EntryPoint>(forwardLeft)
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_leftstickforwardright()
    {
        // IDLE behavior
        // uml: LEFTSTICKFORWARDRIGHT TransitionTo(MANUAL_CONTROL.<EntryPoint>(forwardRight))
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            IDLE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `MANUAL_CONTROL.<EntryPoint>(forwardRight)`.
            MANUAL_CONTROL_enter();
            // MANUAL_CONTROL.<EntryPoint>(forwardRight) is a pseudo state and cannot have an `enter` trigger.
            
            // MANUAL_CONTROL.<EntryPoint>(forwardRight) behavior
            // uml: TransitionTo(FORWARDRIGHT)
            {
                // Step 1: Exit states until we reach `MANUAL_CONTROL` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `FORWARDRIGHT`.
                FORWARDRIGHT_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for MANUAL_CONTROL.<EntryPoint>(forwardRight)
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_leftstickidle()
    {
        // IDLE behavior
        // uml: LEFTSTICKIDLE / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_leftstickleft()
    {
        // IDLE behavior
        // uml: LEFTSTICKLEFT TransitionTo(MANUAL_CONTROL.<EntryPoint>(left))
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            IDLE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `MANUAL_CONTROL.<EntryPoint>(left)`.
            MANUAL_CONTROL_enter();
            // MANUAL_CONTROL.<EntryPoint>(left) is a pseudo state and cannot have an `enter` trigger.
            
            // MANUAL_CONTROL.<EntryPoint>(left) behavior
            // uml: TransitionTo(LEFT)
            {
                // Step 1: Exit states until we reach `MANUAL_CONTROL` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `LEFT`.
                LEFT_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for MANUAL_CONTROL.<EntryPoint>(left)
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_leftstickright()
    {
        // IDLE behavior
        // uml: LEFTSTICKRIGHT TransitionTo(MANUAL_CONTROL.<EntryPoint>(right))
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            IDLE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `MANUAL_CONTROL.<EntryPoint>(right)`.
            MANUAL_CONTROL_enter();
            // MANUAL_CONTROL.<EntryPoint>(right) is a pseudo state and cannot have an `enter` trigger.
            
            // MANUAL_CONTROL.<EntryPoint>(right) behavior
            // uml: TransitionTo(RIGHT)
            {
                // Step 1: Exit states until we reach `MANUAL_CONTROL` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `RIGHT`.
                RIGHT_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for MANUAL_CONTROL.<EntryPoint>(right)
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state MANUAL_CONTROL
    ////////////////////////////////////////////////////////////////////////////////
    
    private void MANUAL_CONTROL_enter()
    {
        this.stateId = StateId.MANUAL_CONTROL;
    }
    
    private void MANUAL_CONTROL_exit()
    {
        // MANUAL_CONTROL behavior
        // uml: exit / { fireEvent("setSpeedLeft", 0);\nfireEvent("setSpeedRight", 0); }
        {
            // Step 1: execute action `fireEvent("setSpeedLeft", 0);\nfireEvent("setSpeedRight", 0);`
            fireEvent("setSpeedLeft", 0);
            fireEvent("setSpeedRight", 0);
        } // end of behavior for MANUAL_CONTROL
        
        this.stateId = StateId.ROOT;
    }
    
    private void MANUAL_CONTROL_leftstickbackward()
    {
        // MANUAL_CONTROL behavior
        // uml: LEFTSTICKBACKWARD TransitionTo(BACKWARD)
        {
            // Step 1: Exit states until we reach `MANUAL_CONTROL` state (Least Common Ancestor for transition).
            exitUpToStateHandler(StateId.MANUAL_CONTROL);
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `BACKWARD`.
            BACKWARD_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for MANUAL_CONTROL
        
        // No ancestor handles this event.
    }
    
    private void MANUAL_CONTROL_leftstickbackwardleft()
    {
        // MANUAL_CONTROL behavior
        // uml: LEFTSTICKBACKWARDLEFT TransitionTo(BACKWARDLEFT)
        {
            // Step 1: Exit states until we reach `MANUAL_CONTROL` state (Least Common Ancestor for transition).
            exitUpToStateHandler(StateId.MANUAL_CONTROL);
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `BACKWARDLEFT`.
            BACKWARDLEFT_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for MANUAL_CONTROL
        
        // No ancestor handles this event.
    }
    
    private void MANUAL_CONTROL_leftstickbackwardright()
    {
        // MANUAL_CONTROL behavior
        // uml: LEFTSTICKBACKWARDRIGHT TransitionTo(BACKWARDRIGHT)
        {
            // Step 1: Exit states until we reach `MANUAL_CONTROL` state (Least Common Ancestor for transition).
            exitUpToStateHandler(StateId.MANUAL_CONTROL);
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `BACKWARDRIGHT`.
            BACKWARDRIGHT_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for MANUAL_CONTROL
        
        // No ancestor handles this event.
    }
    
    private void MANUAL_CONTROL_leftstickforward()
    {
        // MANUAL_CONTROL behavior
        // uml: LEFTSTICKFORWARD TransitionTo(FORWARD)
        {
            // Step 1: Exit states until we reach `MANUAL_CONTROL` state (Least Common Ancestor for transition).
            exitUpToStateHandler(StateId.MANUAL_CONTROL);
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `FORWARD`.
            FORWARD_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for MANUAL_CONTROL
        
        // No ancestor handles this event.
    }
    
    private void MANUAL_CONTROL_leftstickforwardleft()
    {
        // MANUAL_CONTROL behavior
        // uml: LEFTSTICKFORWARDLEFT TransitionTo(FORWARDLEFT)
        {
            // Step 1: Exit states until we reach `MANUAL_CONTROL` state (Least Common Ancestor for transition).
            exitUpToStateHandler(StateId.MANUAL_CONTROL);
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `FORWARDLEFT`.
            FORWARDLEFT_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for MANUAL_CONTROL
        
        // No ancestor handles this event.
    }
    
    private void MANUAL_CONTROL_leftstickforwardright()
    {
        // MANUAL_CONTROL behavior
        // uml: LEFTSTICKFORWARDRIGHT TransitionTo(FORWARDRIGHT)
        {
            // Step 1: Exit states until we reach `MANUAL_CONTROL` state (Least Common Ancestor for transition).
            exitUpToStateHandler(StateId.MANUAL_CONTROL);
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `FORWARDRIGHT`.
            FORWARDRIGHT_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for MANUAL_CONTROL
        
        // No ancestor handles this event.
    }
    
    private void MANUAL_CONTROL_leftstickidle()
    {
        // MANUAL_CONTROL behavior
        // uml: LEFTSTICKIDLE TransitionTo(IDLE)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            exitUpToStateHandler(StateId.ROOT);
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `IDLE`.
            IDLE_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for MANUAL_CONTROL
        
        // No ancestor handles this event.
    }
    
    private void MANUAL_CONTROL_leftstickleft()
    {
        // MANUAL_CONTROL behavior
        // uml: LEFTSTICKLEFT TransitionTo(LEFT)
        {
            // Step 1: Exit states until we reach `MANUAL_CONTROL` state (Least Common Ancestor for transition).
            exitUpToStateHandler(StateId.MANUAL_CONTROL);
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `LEFT`.
            LEFT_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for MANUAL_CONTROL
        
        // No ancestor handles this event.
    }
    
    private void MANUAL_CONTROL_leftstickright()
    {
        // MANUAL_CONTROL behavior
        // uml: LEFTSTICKRIGHT TransitionTo(RIGHT)
        {
            // Step 1: Exit states until we reach `MANUAL_CONTROL` state (Least Common Ancestor for transition).
            exitUpToStateHandler(StateId.MANUAL_CONTROL);
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `RIGHT`.
            RIGHT_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for MANUAL_CONTROL
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state BACKWARD
    ////////////////////////////////////////////////////////////////////////////////
    
    private void BACKWARD_enter()
    {
        this.stateId = StateId.BACKWARD;
        
        // BACKWARD behavior
        // uml: enter / { updateProcess();\nfireEvent("setSpeedLeft", -speed);\nfireEvent("setSpeedRight", -speed); }
        {
            // Step 1: execute action `updateProcess();\nfireEvent("setSpeedLeft", -speed);\nfireEvent("setSpeedRight", -speed);`
            updateProcess();
            fireEvent("setSpeedLeft", -this.vars.speed);
            fireEvent("setSpeedRight", -this.vars.speed);
        } // end of behavior for BACKWARD
    }
    
    private void BACKWARD_exit()
    {
        this.stateId = StateId.MANUAL_CONTROL;
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state BACKWARDLEFT
    ////////////////////////////////////////////////////////////////////////////////
    
    private void BACKWARDLEFT_enter()
    {
        this.stateId = StateId.BACKWARDLEFT;
        
        // BACKWARDLEFT behavior
        // uml: enter / { updateProcess();\nfireEvent("setSpeedLeft", 0);\nfireEvent("setSpeedRight", -speed); }
        {
            // Step 1: execute action `updateProcess();\nfireEvent("setSpeedLeft", 0);\nfireEvent("setSpeedRight", -speed);`
            updateProcess();
            fireEvent("setSpeedLeft", 0);
            fireEvent("setSpeedRight", -this.vars.speed);
        } // end of behavior for BACKWARDLEFT
    }
    
    private void BACKWARDLEFT_exit()
    {
        this.stateId = StateId.MANUAL_CONTROL;
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state BACKWARDRIGHT
    ////////////////////////////////////////////////////////////////////////////////
    
    private void BACKWARDRIGHT_enter()
    {
        this.stateId = StateId.BACKWARDRIGHT;
        
        // BACKWARDRIGHT behavior
        // uml: enter / { updateProcess();\nfireEvent("setSpeedLeft", -speed);\nfireEvent("setSpeedRight", 0); }
        {
            // Step 1: execute action `updateProcess();\nfireEvent("setSpeedLeft", -speed);\nfireEvent("setSpeedRight", 0);`
            updateProcess();
            fireEvent("setSpeedLeft", -this.vars.speed);
            fireEvent("setSpeedRight", 0);
        } // end of behavior for BACKWARDRIGHT
    }
    
    private void BACKWARDRIGHT_exit()
    {
        this.stateId = StateId.MANUAL_CONTROL;
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state FORWARD
    ////////////////////////////////////////////////////////////////////////////////
    
    private void FORWARD_enter()
    {
        this.stateId = StateId.FORWARD;
        
        // FORWARD behavior
        // uml: enter / { updateProcess();\nfireEvent("setSpeedLeft", speed);\nfireEvent("setSpeedRight", speed); }
        {
            // Step 1: execute action `updateProcess();\nfireEvent("setSpeedLeft", speed);\nfireEvent("setSpeedRight", speed);`
            updateProcess();
            fireEvent("setSpeedLeft", this.vars.speed);
            fireEvent("setSpeedRight", this.vars.speed);
        } // end of behavior for FORWARD
    }
    
    private void FORWARD_exit()
    {
        this.stateId = StateId.MANUAL_CONTROL;
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state FORWARDLEFT
    ////////////////////////////////////////////////////////////////////////////////
    
    private void FORWARDLEFT_enter()
    {
        this.stateId = StateId.FORWARDLEFT;
        
        // FORWARDLEFT behavior
        // uml: enter / { updateProcess();\nfireEvent("setSpeedLeft", 0);\nfireEvent("setSpeedRight", speed); }
        {
            // Step 1: execute action `updateProcess();\nfireEvent("setSpeedLeft", 0);\nfireEvent("setSpeedRight", speed);`
            updateProcess();
            fireEvent("setSpeedLeft", 0);
            fireEvent("setSpeedRight", this.vars.speed);
        } // end of behavior for FORWARDLEFT
    }
    
    private void FORWARDLEFT_exit()
    {
        this.stateId = StateId.MANUAL_CONTROL;
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state FORWARDRIGHT
    ////////////////////////////////////////////////////////////////////////////////
    
    private void FORWARDRIGHT_enter()
    {
        this.stateId = StateId.FORWARDRIGHT;
        
        // FORWARDRIGHT behavior
        // uml: enter / { updateProcess();\nfireEvent("setSpeedLeft", speed);\nfireEvent("setSpeedRight", 0); }
        {
            // Step 1: execute action `updateProcess();\nfireEvent("setSpeedLeft", speed);\nfireEvent("setSpeedRight", 0);`
            updateProcess();
            fireEvent("setSpeedLeft", this.vars.speed);
            fireEvent("setSpeedRight", 0);
        } // end of behavior for FORWARDRIGHT
    }
    
    private void FORWARDRIGHT_exit()
    {
        this.stateId = StateId.MANUAL_CONTROL;
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state LEFT
    ////////////////////////////////////////////////////////////////////////////////
    
    private void LEFT_enter()
    {
        this.stateId = StateId.LEFT;
        
        // LEFT behavior
        // uml: enter / { updateProcess();\nfireEvent("setSpeedLeft", -speed);\nfireEvent("setSpeedRight", speed); }
        {
            // Step 1: execute action `updateProcess();\nfireEvent("setSpeedLeft", -speed);\nfireEvent("setSpeedRight", speed);`
            updateProcess();
            fireEvent("setSpeedLeft", -this.vars.speed);
            fireEvent("setSpeedRight", this.vars.speed);
        } // end of behavior for LEFT
    }
    
    private void LEFT_exit()
    {
        this.stateId = StateId.MANUAL_CONTROL;
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state RIGHT
    ////////////////////////////////////////////////////////////////////////////////
    
    private void RIGHT_enter()
    {
        this.stateId = StateId.RIGHT;
        
        // RIGHT behavior
        // uml: enter / { updateProcess();\nfireEvent("setSpeedLeft", speed);\nfireEvent("setSpeedRight", -speed); }
        {
            // Step 1: execute action `updateProcess();\nfireEvent("setSpeedLeft", speed);\nfireEvent("setSpeedRight", -speed);`
            updateProcess();
            fireEvent("setSpeedLeft", this.vars.speed);
            fireEvent("setSpeedRight", -this.vars.speed);
        } // end of behavior for RIGHT
    }
    
    private void RIGHT_exit()
    {
        this.stateId = StateId.MANUAL_CONTROL;
    }
    
    // Thread safe.
    public static String stateIdToString(StateId id)
    {
        switch (id)
        {
            case ROOT: return "ROOT";
            case IDLE: return "IDLE";
            case MANUAL_CONTROL: return "MANUAL_CONTROL";
            case BACKWARD: return "BACKWARD";
            case BACKWARDLEFT: return "BACKWARDLEFT";
            case BACKWARDRIGHT: return "BACKWARDRIGHT";
            case FORWARD: return "FORWARD";
            case FORWARDLEFT: return "FORWARDLEFT";
            case FORWARDRIGHT: return "FORWARDRIGHT";
            case LEFT: return "LEFT";
            case RIGHT: return "RIGHT";
            default: return "?";
        }
    }
    
    // Thread safe.
    public static String eventIdToString(EventId id)
    {
        switch (id)
        {
            case LEFTSTICKBACKWARD: return "LEFTSTICKBACKWARD";
            case LEFTSTICKBACKWARDLEFT: return "LEFTSTICKBACKWARDLEFT";
            case LEFTSTICKBACKWARDRIGHT: return "LEFTSTICKBACKWARDRIGHT";
            case LEFTSTICKFORWARD: return "LEFTSTICKFORWARD";
            case LEFTSTICKFORWARDLEFT: return "LEFTSTICKFORWARDLEFT";
            case LEFTSTICKFORWARDRIGHT: return "LEFTSTICKFORWARDRIGHT";
            case LEFTSTICKIDLE: return "LEFTSTICKIDLE";
            case LEFTSTICKLEFT: return "LEFTSTICKLEFT";
            case LEFTSTICKRIGHT: return "LEFTSTICKRIGHT";
            default: return "?";
        }
    }

    ////////////////////////////////////////////////////////////////////////////////
    // Inserted code by csx script
    ////////////////////////////////////////////////////////////////////////////////
    
    protected String[] getAllowedEvents(StateId id) {
        return switch (id) {
            case ROOT -> new String[0];  // No events
            case IDLE -> new String[]{"LEFTSTICKIDLE", "LEFTSTICKFORWARD", "LEFTSTICKFORWARDRIGHT", "LEFTSTICKRIGHT", "LEFTSTICKBACKWARDRIGHT", "LEFTSTICKBACKWARD", "LEFTSTICKBACKWARDLEFT", "LEFTSTICKLEFT", "LEFTSTICKFORWARDLEFT"};
            case MANUAL_CONTROL -> new String[]{"LEFTSTICKIDLE", "LEFTSTICKFORWARD", "LEFTSTICKFORWARDRIGHT", "LEFTSTICKRIGHT", "LEFTSTICKBACKWARDRIGHT", "LEFTSTICKBACKWARD", "LEFTSTICKBACKWARDLEFT", "LEFTSTICKLEFT", "LEFTSTICKFORWARDLEFT"};
            case BACKWARD -> new String[]{"LEFTSTICKIDLE", "LEFTSTICKFORWARD", "LEFTSTICKFORWARDRIGHT", "LEFTSTICKRIGHT", "LEFTSTICKBACKWARDRIGHT", "LEFTSTICKBACKWARD", "LEFTSTICKBACKWARDLEFT", "LEFTSTICKLEFT", "LEFTSTICKFORWARDLEFT"};
            case BACKWARDLEFT -> new String[]{"LEFTSTICKIDLE", "LEFTSTICKFORWARD", "LEFTSTICKFORWARDRIGHT", "LEFTSTICKRIGHT", "LEFTSTICKBACKWARDRIGHT", "LEFTSTICKBACKWARD", "LEFTSTICKBACKWARDLEFT", "LEFTSTICKLEFT", "LEFTSTICKFORWARDLEFT"};
            case BACKWARDRIGHT -> new String[]{"LEFTSTICKIDLE", "LEFTSTICKFORWARD", "LEFTSTICKFORWARDRIGHT", "LEFTSTICKRIGHT", "LEFTSTICKBACKWARDRIGHT", "LEFTSTICKBACKWARD", "LEFTSTICKBACKWARDLEFT", "LEFTSTICKLEFT", "LEFTSTICKFORWARDLEFT"};
            case FORWARD -> new String[]{"LEFTSTICKIDLE", "LEFTSTICKFORWARD", "LEFTSTICKFORWARDRIGHT", "LEFTSTICKRIGHT", "LEFTSTICKBACKWARDRIGHT", "LEFTSTICKBACKWARD", "LEFTSTICKBACKWARDLEFT", "LEFTSTICKLEFT", "LEFTSTICKFORWARDLEFT"};
            case FORWARDLEFT -> new String[]{"LEFTSTICKIDLE", "LEFTSTICKFORWARD", "LEFTSTICKFORWARDRIGHT", "LEFTSTICKRIGHT", "LEFTSTICKBACKWARDRIGHT", "LEFTSTICKBACKWARD", "LEFTSTICKBACKWARDLEFT", "LEFTSTICKLEFT", "LEFTSTICKFORWARDLEFT"};
            case FORWARDRIGHT -> new String[]{"LEFTSTICKIDLE", "LEFTSTICKFORWARD", "LEFTSTICKFORWARDRIGHT", "LEFTSTICKRIGHT", "LEFTSTICKBACKWARDRIGHT", "LEFTSTICKBACKWARD", "LEFTSTICKBACKWARDLEFT", "LEFTSTICKLEFT", "LEFTSTICKFORWARDLEFT"};
            case LEFT -> new String[]{"LEFTSTICKIDLE", "LEFTSTICKFORWARD", "LEFTSTICKFORWARDRIGHT", "LEFTSTICKRIGHT", "LEFTSTICKBACKWARDRIGHT", "LEFTSTICKBACKWARD", "LEFTSTICKBACKWARDLEFT", "LEFTSTICKLEFT", "LEFTSTICKFORWARDLEFT"};
            case RIGHT -> new String[]{"LEFTSTICKIDLE", "LEFTSTICKFORWARD", "LEFTSTICKFORWARDRIGHT", "LEFTSTICKRIGHT", "LEFTSTICKBACKWARDRIGHT", "LEFTSTICKBACKWARD", "LEFTSTICKBACKWARDLEFT", "LEFTSTICKLEFT", "LEFTSTICKFORWARDLEFT"};
            default -> new String[0];
        };
    }
    
    @Override
    protected String[] getAllEventNames()
    {
        EventId[] values = EventId.values();
        String[] names = new String[values.length];
        
        for (int i = 0; i < values.length; i++)
            names[i] = translateEventName(values[i].name());
        
        return names;
    }
    
    @Override
    protected String[] getAllStateNames()
    {
        StateId[] values = StateId.values();
        String[] names = new String[values.length];
        
        for (int i = 0; i < values.length; i++)
            names[i] = values[i].name();
        
        return names;
    }
    
    @Override
    protected String getCurrentStateString()
    {
        return stateIdToString(this.stateId);
    }
    
    @Override
    protected String[] getBaseAllowedEventsForCurrentState()
    {
        return getAllowedEvents(this.stateId);
    }
    
    // Allow sending strings to dispatchEvent(), with translate functionality
    @Override
    protected void dispatchEvent(String eventName)
    {
        String baseEventName = translateToBaseEventName(eventName);
        dispatchEvent(EventId.valueOf(baseEventName));
    }
    
    @Override
    protected void startSm()
    {
        start();
    }
    
    // See function name
    @SuppressWarnings("unused")
    private void suppressUnusedExitUpToStateHandler()
    {
        exitUpToStateHandler(StateId.ROOT);
    }
    
    ////////////////////////////////////////////////////////////////////////////////
    // End of csx-inserted code
    ////////////////////////////////////////////////////////////////////////////////
}
