// Autogenerated with StateSmith 0.19.0-alpha-1+3da98b58a6e506bc06d88cba576dcc4df8809849.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

package tankpack;

// Generated state machine
public class Sm_Turret_Generated extends StateMachine
{
    public enum EventId
    {
        RIGHTSTICKIDLE,
        RIGHTSTICKLEFT,
        RIGHTSTICKRIGHT,
    }
    
    public final int EventIdCount = 3;
    
    public enum StateId
    {
        ROOT,
        IDLE,
        MOVING,
        LEFT,
        RIGHT,
    }
    
    public final int StateIdCount = 5;
    
    // Used internally by state machine. Feel free to inspect, but don't modify.
    public StateId stateId;
    
    // State machine variables. Can be used for inputs, outputs, user variables...
    public class Vars
    {
        // These variables can be referenced in diagram and are automatically prefixed with "this.vars." during code generation
        // Protected variables, must be set by inheriting class
        protected int speed = 0;
        
        // Private variables, only used locally
    }
    
    // Variables. Can be used for inputs, outputs, user variables...
    public Vars vars = new Vars();
    
    // State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
    public Sm_Turret_Generated()
    {
    }
    
    // Starts the state machine. Must be called before dispatching events. Not thread safe.
    public void start()
    {
        ROOT_enter();
        // ROOT behavior
        // uml: TransitionTo(ROOT.<InitialState>)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
            // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
            
            // ROOT.<InitialState> behavior
            // uml: TransitionTo(IDLE)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `IDLE`.
                IDLE_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for ROOT.<InitialState>
        } // end of behavior for ROOT
    }
    
    // Dispatches an event to the state machine. Not thread safe.
    // Note! This function assumes that the `eventId` parameter is valid.
    public void dispatchEvent(EventId eventId)
    {
        switch (this.stateId)
        {
            // STATE: Sm_Turret_Generated
            case ROOT:
                // No events handled by this state (or its ancestors).
                break;
            
            // STATE: IDLE
            case IDLE:
                switch (eventId)
                {
                    case RIGHTSTICKIDLE: IDLE_rightstickidle(); break;
                    case RIGHTSTICKRIGHT: IDLE_rightstickright(); break;
                    case RIGHTSTICKLEFT: IDLE_rightstickleft(); break;
                }
                break;
            
            // STATE: MOVING
            case MOVING:
                switch (eventId)
                {
                    case RIGHTSTICKIDLE: MOVING_rightstickidle(); break;
                    case RIGHTSTICKRIGHT: MOVING_rightstickright(); break;
                    case RIGHTSTICKLEFT: MOVING_rightstickleft(); break;
                }
                break;
            
            // STATE: LEFT
            case LEFT:
                switch (eventId)
                {
                    case RIGHTSTICKIDLE: MOVING_rightstickidle(); break; // First ancestor handler for this event
                    case RIGHTSTICKRIGHT: MOVING_rightstickright(); break; // First ancestor handler for this event
                    case RIGHTSTICKLEFT: MOVING_rightstickleft(); break; // First ancestor handler for this event
                }
                break;
            
            // STATE: RIGHT
            case RIGHT:
                switch (eventId)
                {
                    case RIGHTSTICKIDLE: MOVING_rightstickidle(); break; // First ancestor handler for this event
                    case RIGHTSTICKRIGHT: MOVING_rightstickright(); break; // First ancestor handler for this event
                    case RIGHTSTICKLEFT: MOVING_rightstickleft(); break; // First ancestor handler for this event
                }
                break;
        }
        
    }
    
    // This function is used when StateSmith doesn't know what the active leaf state is at
    // compile time due to sub states or when multiple states need to be exited.
    private void exitUpToStateHandler(StateId desiredState)
    {
        while (this.stateId != desiredState)
        {
            switch (this.stateId)
            {
                case IDLE: IDLE_exit(); break;
                
                case MOVING: MOVING_exit(); break;
                
                case LEFT: LEFT_exit(); break;
                
                case RIGHT: RIGHT_exit(); break;
                
                default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
            }
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state ROOT
    ////////////////////////////////////////////////////////////////////////////////
    
    private void ROOT_enter()
    {
        this.stateId = StateId.ROOT;
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state IDLE
    ////////////////////////////////////////////////////////////////////////////////
    
    private void IDLE_enter()
    {
        this.stateId = StateId.IDLE;
        
        // IDLE behavior
        // uml: enter / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for IDLE
    }
    
    private void IDLE_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void IDLE_rightstickidle()
    {
        // IDLE behavior
        // uml: RIGHTSTICKIDLE / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_rightstickleft()
    {
        // IDLE behavior
        // uml: RIGHTSTICKLEFT TransitionTo(MOVING.<EntryPoint>(left))
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            IDLE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `MOVING.<EntryPoint>(left)`.
            MOVING_enter();
            // MOVING.<EntryPoint>(left) is a pseudo state and cannot have an `enter` trigger.
            
            // MOVING.<EntryPoint>(left) behavior
            // uml: TransitionTo(LEFT)
            {
                // Step 1: Exit states until we reach `MOVING` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `LEFT`.
                LEFT_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for MOVING.<EntryPoint>(left)
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_rightstickright()
    {
        // IDLE behavior
        // uml: RIGHTSTICKRIGHT TransitionTo(MOVING.<EntryPoint>(right))
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            IDLE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `MOVING.<EntryPoint>(right)`.
            MOVING_enter();
            // MOVING.<EntryPoint>(right) is a pseudo state and cannot have an `enter` trigger.
            
            // MOVING.<EntryPoint>(right) behavior
            // uml: TransitionTo(RIGHT)
            {
                // Step 1: Exit states until we reach `MOVING` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `RIGHT`.
                RIGHT_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for MOVING.<EntryPoint>(right)
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state MOVING
    ////////////////////////////////////////////////////////////////////////////////
    
    private void MOVING_enter()
    {
        this.stateId = StateId.MOVING;
    }
    
    private void MOVING_exit()
    {
        // MOVING behavior
        // uml: exit / { fireEvent("setSpeedTurret", 0); }
        {
            // Step 1: execute action `fireEvent("setSpeedTurret", 0);`
            fireEvent("setSpeedTurret", 0);
        } // end of behavior for MOVING
        
        this.stateId = StateId.ROOT;
    }
    
    private void MOVING_rightstickidle()
    {
        // MOVING behavior
        // uml: RIGHTSTICKIDLE TransitionTo(IDLE)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            exitUpToStateHandler(StateId.ROOT);
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `IDLE`.
            IDLE_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for MOVING
        
        // No ancestor handles this event.
    }
    
    private void MOVING_rightstickleft()
    {
        // MOVING behavior
        // uml: RIGHTSTICKLEFT TransitionTo(LEFT)
        {
            // Step 1: Exit states until we reach `MOVING` state (Least Common Ancestor for transition).
            exitUpToStateHandler(StateId.MOVING);
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `LEFT`.
            LEFT_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for MOVING
        
        // No ancestor handles this event.
    }
    
    private void MOVING_rightstickright()
    {
        // MOVING behavior
        // uml: RIGHTSTICKRIGHT TransitionTo(RIGHT)
        {
            // Step 1: Exit states until we reach `MOVING` state (Least Common Ancestor for transition).
            exitUpToStateHandler(StateId.MOVING);
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `RIGHT`.
            RIGHT_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for MOVING
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state LEFT
    ////////////////////////////////////////////////////////////////////////////////
    
    private void LEFT_enter()
    {
        this.stateId = StateId.LEFT;
        
        // LEFT behavior
        // uml: enter / { updateProcess();\nfireEvent("setSpeedTurret", -speed); }
        {
            // Step 1: execute action `updateProcess();\nfireEvent("setSpeedTurret", -speed);`
            updateProcess();
            fireEvent("setSpeedTurret", -this.vars.speed);
        } // end of behavior for LEFT
    }
    
    private void LEFT_exit()
    {
        this.stateId = StateId.MOVING;
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state RIGHT
    ////////////////////////////////////////////////////////////////////////////////
    
    private void RIGHT_enter()
    {
        this.stateId = StateId.RIGHT;
        
        // RIGHT behavior
        // uml: enter / { updateProcess();\nfireEvent("setSpeedTurret", speed); }
        {
            // Step 1: execute action `updateProcess();\nfireEvent("setSpeedTurret", speed);`
            updateProcess();
            fireEvent("setSpeedTurret", this.vars.speed);
        } // end of behavior for RIGHT
    }
    
    private void RIGHT_exit()
    {
        this.stateId = StateId.MOVING;
    }
    
    // Thread safe.
    public static String stateIdToString(StateId id)
    {
        switch (id)
        {
            case ROOT: return "ROOT";
            case IDLE: return "IDLE";
            case MOVING: return "MOVING";
            case LEFT: return "LEFT";
            case RIGHT: return "RIGHT";
            default: return "?";
        }
    }
    
    // Thread safe.
    public static String eventIdToString(EventId id)
    {
        switch (id)
        {
            case RIGHTSTICKIDLE: return "RIGHTSTICKIDLE";
            case RIGHTSTICKLEFT: return "RIGHTSTICKLEFT";
            case RIGHTSTICKRIGHT: return "RIGHTSTICKRIGHT";
            default: return "?";
        }
    }

    ////////////////////////////////////////////////////////////////////////////////
    // Inserted code by csx script
    ////////////////////////////////////////////////////////////////////////////////
    
    protected String[] getAllowedEvents(StateId id) {
        return switch (id) {
            case ROOT -> new String[0];  // No events
            case IDLE -> new String[]{"RIGHTSTICKIDLE", "RIGHTSTICKRIGHT", "RIGHTSTICKLEFT"};
            case MOVING -> new String[]{"RIGHTSTICKIDLE", "RIGHTSTICKRIGHT", "RIGHTSTICKLEFT"};
            case LEFT -> new String[]{"RIGHTSTICKIDLE", "RIGHTSTICKRIGHT", "RIGHTSTICKLEFT"};
            case RIGHT -> new String[]{"RIGHTSTICKIDLE", "RIGHTSTICKRIGHT", "RIGHTSTICKLEFT"};
            default -> new String[0];
        };
    }
    
    @Override
    protected String[] getAllEventNames()
    {
        EventId[] values = EventId.values();
        String[] names = new String[values.length];
        
        for (int i = 0; i < values.length; i++)
            names[i] = translateEventName(values[i].name());
        
        return names;
    }
    
    @Override
    protected String[] getAllStateNames()
    {
        StateId[] values = StateId.values();
        String[] names = new String[values.length];
        
        for (int i = 0; i < values.length; i++)
            names[i] = values[i].name();
        
        return names;
    }
    
    @Override
    protected String getCurrentStateString()
    {
        return stateIdToString(this.stateId);
    }
    
    @Override
    protected String[] getBaseAllowedEventsForCurrentState()
    {
        return getAllowedEvents(this.stateId);
    }
    
    // Allow sending strings to dispatchEvent(), with translate functionality
    @Override
    protected void dispatchEvent(String eventName)
    {
        String baseEventName = translateToBaseEventName(eventName);
        dispatchEvent(EventId.valueOf(baseEventName));
    }
    
    @Override
    protected void startSm()
    {
        start();
    }
    
    // See function name
    @SuppressWarnings("unused")
    private void suppressUnusedExitUpToStateHandler()
    {
        exitUpToStateHandler(StateId.ROOT);
    }
    
    ////////////////////////////////////////////////////////////////////////////////
    // End of csx-inserted code
    ////////////////////////////////////////////////////////////////////////////////
}
