// Autogenerated with StateSmith 0.19.0-alpha-1+3da98b58a6e506bc06d88cba576dcc4df8809849.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

package tankpack;

// Generated state machine
public class Sm_TurretDrive_Generated extends StateMachine
{
//  ////////////////////////////////////////////////////////////////////////////////
    // Class code
    ////////////////////////////////////////////////////////////////////////////////
    
    // Must be overridden by inheriting class
    protected void adjustSpeed()
    {
    }
    
    // Must be overridden by inheriting class
    protected int speedToVolume(int speed)
    {
        return 0;
    }

    ////////////////////////////////////////////////////////////////////////////////
    // End of class code
    ////////////////////////////////////////////////////////////////////////////////


    public enum EventId
    {
        DO, // The `do` event is special. State event handlers do not consume this event (ancestors all get it too) unless a transition occurs.
        RIGHTSTICKIDLE,
        RIGHTSTICKLEFT,
        RIGHTSTICKRIGHT,
    }
    
    public final int EventIdCount = 4;
    
    public enum StateId
    {
        ROOT,
        IDLE,
        RUNNING,
        ACCELERATING,
        DECELERATING,
        MOVING,
    }
    
    public final int StateIdCount = 6;
    
    // Used internally by state machine. Feel free to inspect, but don't modify.
    public StateId stateId;
    
    // State machine variables. Can be used for inputs, outputs, user variables...
    public class Vars
    {
        // These variables can be referenced in diagram and are automatically prefixed with "this.vars." during code generation
        // Protected variables, must be set by inheriting class
        protected Driver_Sound ds;
        protected int currentSpeed;
        protected int targetSpeed;
        
        // Private variables, only used locally
        private final long WAITTIME = (1000L / DOTIME()) * DOTIME(); // Set / Approach x ms, must be divisible by Main.DoPeriod, if DOTIME > x, WAITTIME will be 0
        private final int QUICKFADE = 600; // ms
        private final int SLOWFADE = 3000; // ms
        private long playTime;
    }
    
    // Variables. Can be used for inputs, outputs, user variables...
    public Vars vars = new Vars();
    
    // State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
    public Sm_TurretDrive_Generated()
    {
    }
    
    // Starts the state machine. Must be called before dispatching events. Not thread safe.
    public void start()
    {
        ROOT_enter();
        // ROOT behavior
        // uml: TransitionTo(ROOT.<InitialState>)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
            // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
            
            // ROOT.<InitialState> behavior
            // uml: TransitionTo(IDLE)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `IDLE`.
                IDLE_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for ROOT.<InitialState>
        } // end of behavior for ROOT
    }
    
    // Dispatches an event to the state machine. Not thread safe.
    // Note! This function assumes that the `eventId` parameter is valid.
    public void dispatchEvent(EventId eventId)
    {
        switch (this.stateId)
        {
            // STATE: Sm_TurretDrive_Generated
            case ROOT:
                // No events handled by this state (or its ancestors).
                break;
            
            // STATE: IDLE
            case IDLE:
                switch (eventId)
                {
                    case RIGHTSTICKRIGHT: IDLE_rightstickright(); break;
                    case RIGHTSTICKIDLE: IDLE_rightstickidle(); break;
                    case RIGHTSTICKLEFT: IDLE_rightstickleft(); break;
                }
                break;
            
            // STATE: RUNNING
            case RUNNING:
                switch (eventId)
                {
                    case RIGHTSTICKRIGHT: RUNNING_rightstickright(); break;
                    case RIGHTSTICKLEFT: RUNNING_rightstickleft(); break;
                    case RIGHTSTICKIDLE: RUNNING_rightstickidle(); break;
                    case DO: RUNNING_do(); break;
                }
                break;
            
            // STATE: ACCELERATING
            case ACCELERATING:
                switch (eventId)
                {
                    case DO: ACCELERATING_do(); break;
                    case RIGHTSTICKRIGHT: RUNNING_rightstickright(); break; // First ancestor handler for this event
                    case RIGHTSTICKLEFT: RUNNING_rightstickleft(); break; // First ancestor handler for this event
                    case RIGHTSTICKIDLE: RUNNING_rightstickidle(); break; // First ancestor handler for this event
                }
                break;
            
            // STATE: DECELERATING
            case DECELERATING:
                switch (eventId)
                {
                    case DO: DECELERATING_do(); break;
                    case RIGHTSTICKRIGHT: RUNNING_rightstickright(); break; // First ancestor handler for this event
                    case RIGHTSTICKLEFT: RUNNING_rightstickleft(); break; // First ancestor handler for this event
                    case RIGHTSTICKIDLE: RUNNING_rightstickidle(); break; // First ancestor handler for this event
                }
                break;
            
            // STATE: MOVING
            case MOVING:
                switch (eventId)
                {
                    case DO: MOVING_do(); break;
                    case RIGHTSTICKRIGHT: RUNNING_rightstickright(); break; // First ancestor handler for this event
                    case RIGHTSTICKLEFT: RUNNING_rightstickleft(); break; // First ancestor handler for this event
                    case RIGHTSTICKIDLE: RUNNING_rightstickidle(); break; // First ancestor handler for this event
                }
                break;
        }
        
    }
    
    // This function is used when StateSmith doesn't know what the active leaf state is at
    // compile time due to sub states or when multiple states need to be exited.
    private void exitUpToStateHandler(StateId desiredState)
    {
        while (this.stateId != desiredState)
        {
            switch (this.stateId)
            {
                case IDLE: IDLE_exit(); break;
                
                case RUNNING: RUNNING_exit(); break;
                
                case ACCELERATING: ACCELERATING_exit(); break;
                
                case DECELERATING: DECELERATING_exit(); break;
                
                case MOVING: MOVING_exit(); break;
                
                default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
            }
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state ROOT
    ////////////////////////////////////////////////////////////////////////////////
    
    private void ROOT_enter()
    {
        this.stateId = StateId.ROOT;
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state IDLE
    ////////////////////////////////////////////////////////////////////////////////
    
    private void IDLE_enter()
    {
        this.stateId = StateId.IDLE;
        
        // IDLE behavior
        // uml: enter / { updateProcess();\ncurrentSpeed = 1;\ntargetSpeed = 0;\nadjustSpeed(); // Make sure speed is set to 0 }
        {
            // Step 1: execute action `updateProcess();\ncurrentSpeed = 1;\ntargetSpeed = 0;\nadjustSpeed(); // Make sure speed is set to 0`
            updateProcess();
            this.vars.currentSpeed = 1;
            this.vars.targetSpeed = 0;
            adjustSpeed(); // Make sure speed is set to 0<EOF>
        } // end of behavior for IDLE
    }
    
    private void IDLE_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void IDLE_rightstickidle()
    {
        // IDLE behavior
        // uml: (RIGHTSTICKRIGHT, RIGHTSTICKIDLE, RIGHTSTICKLEFT) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for IDLE
        
        // IDLE behavior
        // uml: (RIGHTSTICKRIGHT, RIGHTSTICKIDLE, RIGHTSTICKLEFT) [targetSpeed >= 10] TransitionTo(ACCELERATING)
        if (this.vars.targetSpeed >= 10)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            IDLE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ACCELERATING`.
            RUNNING_enter();
            ACCELERATING_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_rightstickleft()
    {
        // IDLE behavior
        // uml: (RIGHTSTICKRIGHT, RIGHTSTICKIDLE, RIGHTSTICKLEFT) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for IDLE
        
        // IDLE behavior
        // uml: (RIGHTSTICKRIGHT, RIGHTSTICKIDLE, RIGHTSTICKLEFT) [targetSpeed >= 10] TransitionTo(ACCELERATING)
        if (this.vars.targetSpeed >= 10)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            IDLE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ACCELERATING`.
            RUNNING_enter();
            ACCELERATING_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    private void IDLE_rightstickright()
    {
        // IDLE behavior
        // uml: (RIGHTSTICKRIGHT, RIGHTSTICKIDLE, RIGHTSTICKLEFT) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for IDLE
        
        // IDLE behavior
        // uml: (RIGHTSTICKRIGHT, RIGHTSTICKIDLE, RIGHTSTICKLEFT) [targetSpeed >= 10] TransitionTo(ACCELERATING)
        if (this.vars.targetSpeed >= 10)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            IDLE_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ACCELERATING`.
            RUNNING_enter();
            ACCELERATING_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for IDLE
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state RUNNING
    ////////////////////////////////////////////////////////////////////////////////
    
    private void RUNNING_enter()
    {
        this.stateId = StateId.RUNNING;
    }
    
    private void RUNNING_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void RUNNING_do()
    {
        // RUNNING behavior
        // uml: do [currentSpeed != targetSpeed] / { ds.setMaxVolume("turret", \n speedToVolume(targetSpeed));\nadjustSpeed(); }
        if (this.vars.currentSpeed != this.vars.targetSpeed)
        {
            // Step 1: execute action `ds.setMaxVolume("turret", \n speedToVolume(targetSpeed));\nadjustSpeed();`
            this.vars.ds.setMaxVolume("turret", 
             speedToVolume(this.vars.targetSpeed));
            adjustSpeed();
        } // end of behavior for RUNNING
        
        // No ancestor handles this event.
    }
    
    private void RUNNING_rightstickidle()
    {
        // RUNNING behavior
        // uml: RIGHTSTICKIDLE / { updateProcess();\ntargetSpeed = 0; }
        {
            // Step 1: execute action `updateProcess();\ntargetSpeed = 0;`
            updateProcess();
            this.vars.targetSpeed = 0;
        } // end of behavior for RUNNING
        
        // No ancestor handles this event.
    }
    
    private void RUNNING_rightstickleft()
    {
        // RUNNING behavior
        // uml: (RIGHTSTICKRIGHT, RIGHTSTICKLEFT) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for RUNNING
        
        // No ancestor handles this event.
    }
    
    private void RUNNING_rightstickright()
    {
        // RUNNING behavior
        // uml: (RIGHTSTICKRIGHT, RIGHTSTICKLEFT) / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for RUNNING
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state ACCELERATING
    ////////////////////////////////////////////////////////////////////////////////
    
    private void ACCELERATING_enter()
    {
        this.stateId = StateId.ACCELERATING;
        
        // ACCELERATING behavior
        // uml: enter / { updateProcess();\nplayTime = 0;\nds.fadeIn("turret", SLOWFADE); }
        {
            // Step 1: execute action `updateProcess();\nplayTime = 0;\nds.fadeIn("turret", SLOWFADE);`
            updateProcess();
            this.vars.playTime = 0;
            this.vars.ds.fadeIn("turret", this.vars.SLOWFADE);
        } // end of behavior for ACCELERATING
    }
    
    private void ACCELERATING_exit()
    {
        this.stateId = StateId.RUNNING;
    }
    
    private void ACCELERATING_do()
    {
        boolean consume_event = false;
        
        // ACCELERATING behavior
        // uml: do / { playTime += DOTIME(); }
        {
            // `do` events are not normally consumed.
            // Step 1: execute action `playTime += DOTIME();`
            this.vars.playTime += DOTIME();
        } // end of behavior for ACCELERATING
        
        // ACCELERATING behavior
        // uml: do [playTime >= WAITTIME] TransitionTo(MOVING)
        if (this.vars.playTime >= this.vars.WAITTIME)
        {
            // Step 1: Exit states until we reach `RUNNING` state (Least Common Ancestor for transition).
            ACCELERATING_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `MOVING`.
            MOVING_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ACCELERATING
        
        // ACCELERATING behavior
        // uml: do [targetSpeed == 0] TransitionTo(DECELERATING)
        if (this.vars.targetSpeed == 0)
        {
            // Step 1: Exit states until we reach `RUNNING` state (Least Common Ancestor for transition).
            ACCELERATING_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `DECELERATING`.
            DECELERATING_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ACCELERATING
        
        // Check if event has been consumed before calling ancestor handler.
        if (!consume_event)
        {
            RUNNING_do();
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state DECELERATING
    ////////////////////////////////////////////////////////////////////////////////
    
    private void DECELERATING_enter()
    {
        this.stateId = StateId.DECELERATING;
        
        // DECELERATING behavior
        // uml: enter / { updateProcess();\nplayTime = 0;\nds.fadeOut("turret", QUICKFADE); }
        {
            // Step 1: execute action `updateProcess();\nplayTime = 0;\nds.fadeOut("turret", QUICKFADE);`
            updateProcess();
            this.vars.playTime = 0;
            this.vars.ds.fadeOut("turret", this.vars.QUICKFADE);
        } // end of behavior for DECELERATING
    }
    
    private void DECELERATING_exit()
    {
        this.stateId = StateId.RUNNING;
    }
    
    private void DECELERATING_do()
    {
        boolean consume_event = false;
        
        // DECELERATING behavior
        // uml: do / { playTime += DOTIME(); }
        {
            // `do` events are not normally consumed.
            // Step 1: execute action `playTime += DOTIME();`
            this.vars.playTime += DOTIME();
        } // end of behavior for DECELERATING
        
        // DECELERATING behavior
        // uml: do [targetSpeed > 0] TransitionTo(ACCELERATING)
        if (this.vars.targetSpeed > 0)
        {
            // Step 1: Exit states until we reach `RUNNING` state (Least Common Ancestor for transition).
            DECELERATING_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ACCELERATING`.
            ACCELERATING_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for DECELERATING
        
        // DECELERATING behavior
        // uml: do [playTime >= WAITTIME] TransitionTo(IDLE)
        if (this.vars.playTime >= this.vars.WAITTIME)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            exitUpToStateHandler(StateId.ROOT);
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `IDLE`.
            IDLE_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for DECELERATING
        
        // Check if event has been consumed before calling ancestor handler.
        if (!consume_event)
        {
            RUNNING_do();
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state MOVING
    ////////////////////////////////////////////////////////////////////////////////
    
    private void MOVING_enter()
    {
        this.stateId = StateId.MOVING;
        
        // MOVING behavior
        // uml: enter / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for MOVING
    }
    
    private void MOVING_exit()
    {
        this.stateId = StateId.RUNNING;
    }
    
    private void MOVING_do()
    {
        boolean consume_event = false;
        
        // MOVING behavior
        // uml: do [targetSpeed == 0] TransitionTo(DECELERATING)
        if (this.vars.targetSpeed == 0)
        {
            // Step 1: Exit states until we reach `RUNNING` state (Least Common Ancestor for transition).
            MOVING_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `DECELERATING`.
            DECELERATING_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for MOVING
        
        // Check if event has been consumed before calling ancestor handler.
        if (!consume_event)
        {
            RUNNING_do();
        }
    }
    
    // Thread safe.
    public static String stateIdToString(StateId id)
    {
        switch (id)
        {
            case ROOT: return "ROOT";
            case IDLE: return "IDLE";
            case RUNNING: return "RUNNING";
            case ACCELERATING: return "ACCELERATING";
            case DECELERATING: return "DECELERATING";
            case MOVING: return "MOVING";
            default: return "?";
        }
    }
    
    // Thread safe.
    public static String eventIdToString(EventId id)
    {
        switch (id)
        {
            case DO: return "DO";
            case RIGHTSTICKIDLE: return "RIGHTSTICKIDLE";
            case RIGHTSTICKLEFT: return "RIGHTSTICKLEFT";
            case RIGHTSTICKRIGHT: return "RIGHTSTICKRIGHT";
            default: return "?";
        }
    }

    ////////////////////////////////////////////////////////////////////////////////
    // Inserted code by csx script
    ////////////////////////////////////////////////////////////////////////////////
    
    protected String[] getAllowedEvents(StateId id) {
        return switch (id) {
            case ROOT -> new String[0];  // No events
            case IDLE -> new String[]{"RIGHTSTICKRIGHT", "RIGHTSTICKIDLE", "RIGHTSTICKLEFT"};
            case RUNNING -> new String[]{"RIGHTSTICKRIGHT", "RIGHTSTICKLEFT", "RIGHTSTICKIDLE", "DO"};
            case ACCELERATING -> new String[]{"DO", "RIGHTSTICKRIGHT", "RIGHTSTICKLEFT", "RIGHTSTICKIDLE"};
            case DECELERATING -> new String[]{"DO", "RIGHTSTICKRIGHT", "RIGHTSTICKLEFT", "RIGHTSTICKIDLE"};
            case MOVING -> new String[]{"DO", "RIGHTSTICKRIGHT", "RIGHTSTICKLEFT", "RIGHTSTICKIDLE"};
            default -> new String[0];
        };
    }
    
    @Override
    protected String[] getAllEventNames()
    {
        EventId[] values = EventId.values();
        String[] names = new String[values.length];
        
        for (int i = 0; i < values.length; i++)
            names[i] = translateEventName(values[i].name());
        
        return names;
    }
    
    @Override
    protected String[] getAllStateNames()
    {
        StateId[] values = StateId.values();
        String[] names = new String[values.length];
        
        for (int i = 0; i < values.length; i++)
            names[i] = values[i].name();
        
        return names;
    }
    
    @Override
    protected String getCurrentStateString()
    {
        return stateIdToString(this.stateId);
    }
    
    @Override
    protected String[] getBaseAllowedEventsForCurrentState()
    {
        return getAllowedEvents(this.stateId);
    }
    
    // Allow sending strings to dispatchEvent(), with translate functionality
    @Override
    protected void dispatchEvent(String eventName)
    {
        String baseEventName = translateToBaseEventName(eventName);
        dispatchEvent(EventId.valueOf(baseEventName));
    }
    
    @Override
    protected void startSm()
    {
        start();
    }
    
    // See function name
    @SuppressWarnings("unused")
    private void suppressUnusedExitUpToStateHandler()
    {
        exitUpToStateHandler(StateId.ROOT);
    }
    
    ////////////////////////////////////////////////////////////////////////////////
    // End of csx-inserted code
    ////////////////////////////////////////////////////////////////////////////////
}
