// Autogenerated with StateSmith 0.19.0+ebc88ca27511ff019dec4076062d7ebc9acd4ee9.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

package tankpack;

// Generated state machine
public class Sm_WifiMngr_Generated extends StateMachine
{
//  ////////////////////////////////////////////////////////////////////////////////
    // Class code
    ////////////////////////////////////////////////////////////////////////////////
    
    // Must be overridden by inheriting class
    protected void readWifiSettings()
    {
    }
    
    // Must be overridden by inheriting class
    protected boolean checkConnection()
    {
        return false;
    }
    
    // Must be overridden by inheriting class
    protected void scanWifi()
    {
    }
    
    // Must be overridden by inheriting class
    protected void connectWifi()
    {
    }

    ////////////////////////////////////////////////////////////////////////////////
    // End of class code
    ////////////////////////////////////////////////////////////////////////////////


    public enum EventId
    {
        DO, // The `do` event is special. State event handlers do not consume this event (ancestors all get it too) unless a transition occurs.
        RESTARTWIFI,
    }
    
    public final int EventIdCount = 2;
    
    public enum StateId
    {
        ROOT,
        DISCONNECTED,
        INIT,
        OPERATING,
        CONNECTED,
        CONNECTING,
        SCANNING,
    }
    
    public final int StateIdCount = 7;
    
    // Used internally by state machine. Feel free to inspect, but don't modify.
    public StateId stateId;
    
    // State machine variables. Can be used for inputs, outputs, user variables...
    public class Vars
    {
        // These variables can be referenced in diagram and are automatically prefixed with "this.vars." during code generation
        // Protected variables, must be set by inheriting class
        
        // Private variables, only used locally
        private long timer;
        private boolean connected;
    }
    
    // Variables. Can be used for inputs, outputs, user variables...
    public Vars vars = new Vars();
    
    // State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
    public Sm_WifiMngr_Generated()
    {
    }
    
    // Starts the state machine. Must be called before dispatching events. Not thread safe.
    public void start()
    {
        ROOT_enter();
        // ROOT behavior
        // uml: TransitionTo(ROOT.<InitialState>)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
            // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
            
            // ROOT.<InitialState> behavior
            // uml: TransitionTo(INIT)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `INIT`.
                INIT_enter();
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for ROOT.<InitialState>
        } // end of behavior for ROOT
    }
    
    // Dispatches an event to the state machine. Not thread safe.
    // Note! This function assumes that the `eventId` parameter is valid.
    public void dispatchEvent(EventId eventId)
    {
        switch (this.stateId)
        {
            // STATE: Sm_WifiMngr_Generated
            case ROOT:
                // No events handled by this state (or its ancestors).
                break;
            
            // STATE: DISCONNECTED
            case DISCONNECTED:
                switch (eventId)
                {
                    case RESTARTWIFI: DISCONNECTED_restartwifi(); break;
                }
                break;
            
            // STATE: INIT
            case INIT:
                switch (eventId)
                {
                    case DO: INIT_do(); break;
                    case RESTARTWIFI: INIT_restartwifi(); break;
                }
                break;
            
            // STATE: OPERATING
            case OPERATING:
                switch (eventId)
                {
                    case DO: OPERATING_do(); break;
                    case RESTARTWIFI: OPERATING_restartwifi(); break;
                }
                break;
            
            // STATE: CONNECTED
            case CONNECTED:
                switch (eventId)
                {
                    case DO: CONNECTED_do(); break;
                    case RESTARTWIFI: OPERATING_restartwifi(); break; // First ancestor handler for this event
                }
                break;
            
            // STATE: CONNECTING
            case CONNECTING:
                switch (eventId)
                {
                    case DO: CONNECTING_do(); break;
                    case RESTARTWIFI: OPERATING_restartwifi(); break; // First ancestor handler for this event
                }
                break;
            
            // STATE: SCANNING
            case SCANNING:
                switch (eventId)
                {
                    case DO: SCANNING_do(); break;
                    case RESTARTWIFI: OPERATING_restartwifi(); break; // First ancestor handler for this event
                }
                break;
        }
        
    }
    
    // This function is used when StateSmith doesn't know what the active leaf state is at
    // compile time due to sub states or when multiple states need to be exited.
    private void exitUpToStateHandler(StateId desiredState)
    {
        while (this.stateId != desiredState)
        {
            switch (this.stateId)
            {
                case DISCONNECTED: DISCONNECTED_exit(); break;
                
                case INIT: INIT_exit(); break;
                
                case OPERATING: OPERATING_exit(); break;
                
                case CONNECTED: CONNECTED_exit(); break;
                
                case CONNECTING: CONNECTING_exit(); break;
                
                case SCANNING: SCANNING_exit(); break;
                
                default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
            }
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state ROOT
    ////////////////////////////////////////////////////////////////////////////////
    
    private void ROOT_enter()
    {
        this.stateId = StateId.ROOT;
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state DISCONNECTED
    ////////////////////////////////////////////////////////////////////////////////
    
    private void DISCONNECTED_enter()
    {
        this.stateId = StateId.DISCONNECTED;
        
        // DISCONNECTED behavior
        // uml: enter / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for DISCONNECTED
    }
    
    private void DISCONNECTED_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void DISCONNECTED_restartwifi()
    {
        // DISCONNECTED behavior
        // uml: restartWifi TransitionTo(INIT)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            DISCONNECTED_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `INIT`.
            INIT_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for DISCONNECTED
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state INIT
    ////////////////////////////////////////////////////////////////////////////////
    
    private void INIT_enter()
    {
        this.stateId = StateId.INIT;
        
        // INIT behavior
        // uml: enter / { updateProcess();\nreadWifiSettings();\ntimer = 0; }
        {
            // Step 1: execute action `updateProcess();\nreadWifiSettings();\ntimer = 0;`
            updateProcess();
            readWifiSettings();
            this.vars.timer = 0;
        } // end of behavior for INIT
    }
    
    private void INIT_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void INIT_do()
    {
        // INIT behavior
        // uml: do / { timer += DOTIME(); }
        {
            // Step 1: execute action `timer += DOTIME();`
            this.vars.timer += DOTIME();
        } // end of behavior for INIT
        
        // INIT behavior
        // uml: do [timer >= 5000] / { connected = checkConnection(); }
        if (this.vars.timer >= 5000)
        {
            // Step 1: execute action `connected = checkConnection();`
            this.vars.connected = checkConnection();
        } // end of behavior for INIT
        
        // INIT behavior
        // uml: do [timer >= 5000 && connected] TransitionTo(CONNECTED)
        if (this.vars.timer >= 5000 && this.vars.connected)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            INIT_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `CONNECTED`.
            OPERATING_enter();
            CONNECTED_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for INIT
        
        // INIT behavior
        // uml: do [timer >= 5000 && !connected] TransitionTo(SCANNING)
        if (this.vars.timer >= 5000 && !this.vars.connected)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            INIT_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `SCANNING`.
            OPERATING_enter();
            SCANNING_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for INIT
        
        // No ancestor handles this event.
    }
    
    private void INIT_restartwifi()
    {
        // INIT behavior
        // uml: restartWifi / { updateProcess(); }
        {
            // Step 1: execute action `updateProcess();`
            updateProcess();
        } // end of behavior for INIT
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state OPERATING
    ////////////////////////////////////////////////////////////////////////////////
    
    private void OPERATING_enter()
    {
        this.stateId = StateId.OPERATING;
    }
    
    private void OPERATING_exit()
    {
        this.stateId = StateId.ROOT;
    }
    
    private void OPERATING_do()
    {
        // OPERATING behavior
        // uml: do / { timer += DOTIME(); }
        {
            // Step 1: execute action `timer += DOTIME();`
            this.vars.timer += DOTIME();
        } // end of behavior for OPERATING
        
        // No ancestor handles this event.
    }
    
    private void OPERATING_restartwifi()
    {
        // OPERATING behavior
        // uml: restartWifi TransitionTo(INIT)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            exitUpToStateHandler(StateId.ROOT);
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `INIT`.
            INIT_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for OPERATING
        
        // No ancestor handles this event.
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state CONNECTED
    ////////////////////////////////////////////////////////////////////////////////
    
    private void CONNECTED_enter()
    {
        this.stateId = StateId.CONNECTED;
        
        // CONNECTED behavior
        // uml: enter / { updateProcess();\nfireEvent("wifiConnected");\ntimer = 0; }
        {
            // Step 1: execute action `updateProcess();\nfireEvent("wifiConnected");\ntimer = 0;`
            updateProcess();
            fireEvent("wifiConnected");
            this.vars.timer = 0;
        } // end of behavior for CONNECTED
    }
    
    private void CONNECTED_exit()
    {
        this.stateId = StateId.OPERATING;
    }
    
    private void CONNECTED_do()
    {
        boolean consume_event = false;
        
        // CONNECTED behavior
        // uml: do [timer >= 60000] / { connected = checkConnection();\ntimer = 0; }
        if (this.vars.timer >= 60000)
        {
            // `do` events are not normally consumed.
            // Step 1: execute action `connected = checkConnection();\ntimer = 0;`
            this.vars.connected = checkConnection();
            this.vars.timer = 0;
        } // end of behavior for CONNECTED
        
        // CONNECTED behavior
        // uml: do [!connected] / { fireEvent("wifiDisconnected"); } TransitionTo(DISCONNECTED)
        if (!this.vars.connected)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            exitUpToStateHandler(StateId.ROOT);
            
            // Step 2: Transition action: `fireEvent("wifiDisconnected");`.
            fireEvent("wifiDisconnected");
            
            // Step 3: Enter/move towards transition target `DISCONNECTED`.
            DISCONNECTED_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for CONNECTED
        
        // Check if event has been consumed before calling ancestor handler.
        if (!consume_event)
        {
            OPERATING_do();
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state CONNECTING
    ////////////////////////////////////////////////////////////////////////////////
    
    private void CONNECTING_enter()
    {
        this.stateId = StateId.CONNECTING;
        
        // CONNECTING behavior
        // uml: enter / { updateProcess();\nconnectWifi();\ntimer = 0; }
        {
            // Step 1: execute action `updateProcess();\nconnectWifi();\ntimer = 0;`
            updateProcess();
            connectWifi();
            this.vars.timer = 0;
        } // end of behavior for CONNECTING
    }
    
    private void CONNECTING_exit()
    {
        this.stateId = StateId.OPERATING;
    }
    
    private void CONNECTING_do()
    {
        boolean consume_event = false;
        
        // CONNECTING behavior
        // uml: do [timer >= 10000] / { connected = checkConnection(); }
        if (this.vars.timer >= 10000)
        {
            // `do` events are not normally consumed.
            // Step 1: execute action `connected = checkConnection();`
            this.vars.connected = checkConnection();
        } // end of behavior for CONNECTING
        
        // CONNECTING behavior
        // uml: do [timer >= 10000 && connected] TransitionTo(CONNECTED)
        if (this.vars.timer >= 10000 && this.vars.connected)
        {
            // Step 1: Exit states until we reach `OPERATING` state (Least Common Ancestor for transition).
            CONNECTING_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `CONNECTED`.
            CONNECTED_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for CONNECTING
        
        // CONNECTING behavior
        // uml: do [timer >= 10000 && !connected] TransitionTo(DISCONNECTED)
        if (this.vars.timer >= 10000 && !this.vars.connected)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            exitUpToStateHandler(StateId.ROOT);
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `DISCONNECTED`.
            DISCONNECTED_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for CONNECTING
        
        // Check if event has been consumed before calling ancestor handler.
        if (!consume_event)
        {
            OPERATING_do();
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state SCANNING
    ////////////////////////////////////////////////////////////////////////////////
    
    private void SCANNING_enter()
    {
        this.stateId = StateId.SCANNING;
        
        // SCANNING behavior
        // uml: enter / { updateProcess();\nscanWifi();\ntimer = 0; }
        {
            // Step 1: execute action `updateProcess();\nscanWifi();\ntimer = 0;`
            updateProcess();
            scanWifi();
            this.vars.timer = 0;
        } // end of behavior for SCANNING
    }
    
    private void SCANNING_exit()
    {
        this.stateId = StateId.OPERATING;
    }
    
    private void SCANNING_do()
    {
        boolean consume_event = false;
        
        // SCANNING behavior
        // uml: do [timer >= 5000] TransitionTo(CONNECTING)
        if (this.vars.timer >= 5000)
        {
            // Step 1: Exit states until we reach `OPERATING` state (Least Common Ancestor for transition).
            SCANNING_exit();
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `CONNECTING`.
            CONNECTING_enter();
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for SCANNING
        
        // Check if event has been consumed before calling ancestor handler.
        if (!consume_event)
        {
            OPERATING_do();
        }
    }
    
    // Thread safe.
    public static String stateIdToString(StateId id)
    {
        switch (id)
        {
            case ROOT: return "ROOT";
            case DISCONNECTED: return "DISCONNECTED";
            case INIT: return "INIT";
            case OPERATING: return "OPERATING";
            case CONNECTED: return "CONNECTED";
            case CONNECTING: return "CONNECTING";
            case SCANNING: return "SCANNING";
            default: return "?";
        }
    }
    
    // Thread safe.
    public static String eventIdToString(EventId id)
    {
        switch (id)
        {
            case DO: return "DO";
            case RESTARTWIFI: return "RESTARTWIFI";
            default: return "?";
        }
    }

    ////////////////////////////////////////////////////////////////////////////////
    // Inserted code by csx script
    ////////////////////////////////////////////////////////////////////////////////
    
    protected String[] getAllowedEvents(StateId id) {
        return switch (id) {
            case ROOT -> new String[0];  // No events
            case DISCONNECTED -> new String[]{"RESTARTWIFI"};
            case INIT -> new String[]{"DO", "RESTARTWIFI"};
            case OPERATING -> new String[]{"DO", "RESTARTWIFI"};
            case CONNECTED -> new String[]{"DO", "RESTARTWIFI"};
            case CONNECTING -> new String[]{"DO", "RESTARTWIFI"};
            case SCANNING -> new String[]{"DO", "RESTARTWIFI"};
            default -> new String[0];
        };
    }
    
    @Override
    protected String[] getAllEventNames()
    {
        EventId[] values = EventId.values();
        String[] names = new String[values.length];
        
        for (int i = 0; i < values.length; i++)
            names[i] = translateEventName(values[i].name());
        
        return names;
    }
    
    @Override
    protected String[] getAllStateNames()
    {
        StateId[] values = StateId.values();
        String[] names = new String[values.length];
        
        for (int i = 0; i < values.length; i++)
            names[i] = values[i].name();
        
        return names;
    }
    
    @Override
    protected String getCurrentStateString()
    {
        return stateIdToString(this.stateId);
    }
    
    @Override
    protected String[] getBaseAllowedEventsForCurrentState()
    {
        return getAllowedEvents(this.stateId);
    }
    
    // Allow sending strings to dispatchEvent(), with translate functionality
    @Override
    protected void dispatchEvent(String eventName)
    {
        String baseEventName = translateToBaseEventName(eventName);
        dispatchEvent(EventId.valueOf(baseEventName));
    }
    
    @Override
    protected void startSm()
    {
        start();
    }
    
    // See function name
    @SuppressWarnings("unused")
    private void suppressUnusedExitUpToStateHandler()
    {
        exitUpToStateHandler(StateId.ROOT);
    }
    
    ////////////////////////////////////////////////////////////////////////////////
    // End of csx-inserted code
    ////////////////////////////////////////////////////////////////////////////////
}
